import type {
  ChangePuzzle,
  CoinInfo,
  CountingChallenge,
  MoneyQuizQuestion,
  NoteInfo,
  ShoppingItem,
} from './types';

export const INDIAN_COINS: readonly CoinInfo[] = [
  {
    value: 1,
    label: '₹1',
    nameKey: 'math.money.coins.one',
    color: '#E2E8F0',
    rimColor: '#94A3B8',
    diameter: 64,
    metalKey: 'math.money.metals.steel',
    funFactKey: 'math.money.coins.oneFact',
  },
  {
    value: 2,
    label: '₹2',
    nameKey: 'math.money.coins.two',
    color: '#CBD5E1',
    rimColor: '#64748B',
    diameter: 72,
    metalKey: 'math.money.metals.steel',
    funFactKey: 'math.money.coins.twoFact',
  },
  {
    value: 5,
    label: '₹5',
    nameKey: 'math.money.coins.five',
    color: '#FDE047',
    rimColor: '#CA8A04',
    diameter: 80,
    metalKey: 'math.money.metals.brass',
    funFactKey: 'math.money.coins.fiveFact',
  },
  {
    value: 10,
    label: '₹10',
    nameKey: 'math.money.coins.ten',
    color: '#E2E8F0',
    rimColor: '#CA8A04',
    innerColor: '#FEF08A',
    diameter: 88,
    metalKey: 'math.money.metals.bimetal',
    funFactKey: 'math.money.coins.tenFact',
    isBiMetallic: true,
  },
  {
    value: 20,
    label: '₹20',
    nameKey: 'math.money.coins.twenty',
    color: '#FEF08A',
    rimColor: '#E2E8F0',
    innerColor: '#F8FAFC',
    diameter: 96,
    metalKey: 'math.money.metals.dodecagon',
    funFactKey: 'math.money.coins.twentyFact',
    isBiMetallic: true,
  },
];

export const INDIAN_NOTES: readonly NoteInfo[] = [
  {
    value: 10,
    label: '₹10',
    nameKey: 'math.money.notes.ten',
    baseColor: '#8D6E63',
    bgGradient: ['#D7CCC8', '#8D6E63'],
    motifKey: 'math.money.motifs.konark',
    colorNameKey: 'math.money.colors.chocolateBrown',
  },
  {
    value: 20,
    label: '₹20',
    nameKey: 'math.money.notes.twenty',
    baseColor: '#C0CA33',
    bgGradient: ['#F0F4C3', '#C0CA33'],
    motifKey: 'math.money.motifs.ellora',
    colorNameKey: 'math.money.colors.greenishYellow',
  },
  {
    value: 50,
    label: '₹50',
    nameKey: 'math.money.notes.fifty',
    baseColor: '#00ACC1',
    bgGradient: ['#B2EBF2', '#00ACC1'],
    motifKey: 'math.money.motifs.hampi',
    colorNameKey: 'math.money.colors.fluorescentBlue',
  },
  {
    value: 100,
    label: '₹100',
    nameKey: 'math.money.notes.hundred',
    baseColor: '#8E24AA',
    bgGradient: ['#E1BEE7', '#8E24AA'],
    motifKey: 'math.money.motifs.ranikivav',
    colorNameKey: 'math.money.colors.lavender',
  },
  {
    value: 200,
    label: '₹200',
    nameKey: 'math.money.notes.twoHundred',
    baseColor: '#FB8C00',
    bgGradient: ['#FFE0B2', '#FB8C00'],
    motifKey: 'math.money.motifs.sanchi',
    colorNameKey: 'math.money.colors.brightOrange',
  },
  {
    value: 500,
    label: '₹500',
    nameKey: 'math.money.notes.fiveHundred',
    baseColor: '#546E7A',
    bgGradient: ['#CFD8DC', '#546E7A'],
    motifKey: 'math.money.motifs.redfort',
    colorNameKey: 'math.money.colors.stoneGrey',
  },
];

export const COIN_EQUIVALENCES = [
  {
    targetValue: 5,
    unitCount: 5,
    unitValue: 1,
    promptKey: 'math.money.equiv.fiveOne',
    speechText: 'Five ₹1 coins make ₹5! (1 + 1 + 1 + 1 + 1 = 5)',
  },
  {
    targetValue: 10,
    unitCount: 2,
    unitValue: 5,
    promptKey: 'math.money.equiv.tenFive',
    speechText: 'Two ₹5 coins make ₹10! (5 + 5 = 10)',
  },
  {
    targetValue: 20,
    unitCount: 2,
    unitValue: 10,
    promptKey: 'math.money.equiv.twentyTen',
    speechText: 'Two ₹10 coins make ₹20! (10 + 10 = 20)',
  },
  {
    targetValue: 20,
    unitCount: 4,
    unitValue: 5,
    promptKey: 'math.money.equiv.twentyFive',
    speechText: 'Four ₹5 coins make ₹20! (5 + 5 + 5 + 5 = 20)',
  },
];

export const COUNTING_CHALLENGES: readonly CountingChallenge[] = [
  {
    id: 'count_3',
    targetAmount: 3,
    promptKey: 'math.money.count.pay3',
    allowedCoins: [1, 2],
    allowedNotes: [],
    explanationKey: 'math.money.count.exp3',
  },
  {
    id: 'count_5',
    targetAmount: 5,
    promptKey: 'math.money.count.pay5',
    allowedCoins: [1, 2, 5],
    allowedNotes: [],
    explanationKey: 'math.money.count.exp5',
  },
  {
    id: 'count_10',
    targetAmount: 10,
    promptKey: 'math.money.count.pay10',
    allowedCoins: [2, 5, 10],
    allowedNotes: [10],
    explanationKey: 'math.money.count.exp10',
  },
  {
    id: 'count_15',
    targetAmount: 15,
    promptKey: 'math.money.count.pay15',
    allowedCoins: [5, 10],
    allowedNotes: [10],
    explanationKey: 'math.money.count.exp15',
  },
  {
    id: 'count_20',
    targetAmount: 20,
    promptKey: 'math.money.count.pay20',
    allowedCoins: [5, 10, 20],
    allowedNotes: [10, 20],
    explanationKey: 'math.money.count.exp20',
  },
  {
    id: 'count_35',
    targetAmount: 35,
    promptKey: 'math.money.count.pay35',
    allowedCoins: [5, 10],
    allowedNotes: [10, 20],
    explanationKey: 'math.money.count.exp35',
  },
];

export const SHOPPING_ITEMS: readonly ShoppingItem[] = [
  {
    id: 'apple',
    nameKey: 'math.money.shop.apple',
    defaultName: 'Fresh Apple',
    emoji: '🍎',
    price: 5,
    category: 'fruit',
  },
  {
    id: 'pencil',
    nameKey: 'math.money.shop.pencil',
    defaultName: 'Color Pencil',
    emoji: '✏️',
    price: 8,
    category: 'stationery',
  },
  {
    id: 'banana',
    nameKey: 'math.money.shop.banana',
    defaultName: 'Sweet Banana',
    emoji: '🍌',
    price: 10,
    category: 'fruit',
  },
  {
    id: 'icecream',
    nameKey: 'math.money.shop.icecream',
    defaultName: 'Ice Cream',
    emoji: '🍦',
    price: 12,
    category: 'food',
  },
  {
    id: 'chocolate',
    nameKey: 'math.money.shop.chocolate',
    defaultName: 'Yummy Chocolate',
    emoji: '🍫',
    price: 15,
    category: 'food',
  },
  {
    id: 'cupcake',
    nameKey: 'math.money.shop.cupcake',
    defaultName: 'Berry Cupcake',
    emoji: '🧁',
    price: 18,
    category: 'food',
  },
  {
    id: 'milk',
    nameKey: 'math.money.shop.milk',
    defaultName: 'Bottle of Milk',
    emoji: '🥛',
    price: 20,
    category: 'food',
  },
  {
    id: 'teddy',
    nameKey: 'math.money.shop.teddy',
    defaultName: 'Teddy Bear',
    emoji: '🧸',
    price: 25,
    category: 'toy',
  },
  {
    id: 'book',
    nameKey: 'math.money.shop.book',
    defaultName: 'Story Book',
    emoji: '📖',
    price: 30,
    category: 'stationery',
  },
  {
    id: 'football',
    nameKey: 'math.money.shop.football',
    defaultName: 'Soccer Football',
    emoji: '⚽',
    price: 35,
    category: 'toy',
  },
];

export const CHANGE_PUZZLES: readonly ChangePuzzle[] = [
  {
    id: 'ch_1',
    item: {
      id: 'pencil',
      nameKey: 'math.money.shop.pencil',
      defaultName: 'Color Pencil',
      emoji: '✏️',
      price: 7,
      category: 'stationery',
    },
    paidAmount: 10,
    changeAmount: 3,
    options: [1, 3, 5],
    explanationKey: 'math.money.change.exp1',
  },
  {
    id: 'ch_2',
    item: {
      id: 'apple',
      nameKey: 'math.money.shop.apple',
      defaultName: 'Fresh Apple',
      emoji: '🍎',
      price: 4,
      category: 'fruit',
    },
    paidAmount: 5,
    changeAmount: 1,
    options: [1, 2, 4],
    explanationKey: 'math.money.change.exp2',
  },
  {
    id: 'ch_3',
    item: {
      id: 'chocolate',
      nameKey: 'math.money.shop.chocolate',
      defaultName: 'Yummy Chocolate',
      emoji: '🍫',
      price: 15,
      category: 'food',
    },
    paidAmount: 20,
    changeAmount: 5,
    options: [3, 5, 10],
    explanationKey: 'math.money.change.exp3',
  },
  {
    id: 'ch_4',
    item: {
      id: 'icecream',
      nameKey: 'math.money.shop.icecream',
      defaultName: 'Ice Cream',
      emoji: '🍦',
      price: 12,
      category: 'food',
    },
    paidAmount: 20,
    changeAmount: 8,
    options: [6, 8, 10],
    explanationKey: 'math.money.change.exp4',
  },
  {
    id: 'ch_5',
    item: {
      id: 'book',
      nameKey: 'math.money.shop.book',
      defaultName: 'Story Book',
      emoji: '📖',
      price: 30,
      category: 'stationery',
    },
    paidAmount: 50,
    changeAmount: 20,
    options: [10, 20, 30],
    explanationKey: 'math.money.change.exp5',
  },
];

export const MONEY_QUIZ_QUESTIONS: readonly MoneyQuizQuestion[] = [
  {
    id: 'mq_1',
    type: 'identify_coin',
    questionKey: 'math.money.quiz.qCoin5',
    coins: [5],
    options: [
      {id: 'a', text: '₹2', isCorrect: false},
      {id: 'b', text: '₹5', isCorrect: true},
      {id: 'c', text: '₹10', isCorrect: false},
      {id: 'd', text: '₹1', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expCoin5',
  },
  {
    id: 'mq_2',
    type: 'count_total',
    questionKey: 'math.money.quiz.qCountOneOneOne',
    coins: [1, 1, 1],
    options: [
      {id: 'a', text: '₹2', isCorrect: false},
      {id: 'b', text: '₹3', isCorrect: true},
      {id: 'c', text: '₹5', isCorrect: false},
      {id: 'd', text: '₹1', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expCountOneOneOne',
  },
  {
    id: 'mq_3',
    type: 'equivalence',
    questionKey: 'math.money.quiz.qHowMany1In5',
    options: [
      {id: 'a', text: '3 coins', isCorrect: false},
      {id: 'b', text: '5 coins', isCorrect: true},
      {id: 'c', text: '10 coins', isCorrect: false},
      {id: 'd', text: '2 coins', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expHowMany1In5',
  },
  {
    id: 'mq_4',
    type: 'count_total',
    questionKey: 'math.money.quiz.qCountFiveFive',
    coins: [5, 5],
    options: [
      {id: 'a', text: '₹5', isCorrect: false},
      {id: 'b', text: '₹10', isCorrect: true},
      {id: 'c', text: '₹15', isCorrect: false},
      {id: 'd', text: '₹20', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expCountFiveFive',
  },
  {
    id: 'mq_5',
    type: 'identify_note',
    questionKey: 'math.money.quiz.qNote50',
    notes: [50],
    options: [
      {id: 'a', text: '₹10', isCorrect: false},
      {id: 'b', text: '₹50', isCorrect: true},
      {id: 'c', text: '₹100', isCorrect: false},
      {id: 'd', text: '₹500', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expNote50',
  },
  {
    id: 'mq_6',
    type: 'shopping',
    questionKey: 'math.money.quiz.qCanBuyMilk20',
    options: [
      {id: 'a', text: 'Yes, exactly! 👍', isCorrect: true},
      {id: 'b', text: 'No, need ₹10 more', isCorrect: false},
      {id: 'c', text: 'No, it costs ₹50', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expCanBuyMilk20',
  },
  {
    id: 'mq_7',
    type: 'change',
    questionKey: 'math.money.quiz.qChange7From10',
    options: [
      {id: 'a', text: '₹1', isCorrect: false},
      {id: 'b', text: '₹3', isCorrect: true},
      {id: 'c', text: '₹5', isCorrect: false},
      {id: 'd', text: '₹7', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expChange7From10',
  },
  {
    id: 'mq_8',
    type: 'count_total',
    questionKey: 'math.money.quiz.qCountTenTen',
    coins: [10, 10],
    options: [
      {id: 'a', text: '₹10', isCorrect: false},
      {id: 'b', text: '₹15', isCorrect: false},
      {id: 'c', text: '₹20', isCorrect: true},
      {id: 'd', text: '₹25', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expCountTenTen',
  },
  {
    id: 'mq_9',
    type: 'identify_coin',
    questionKey: 'math.money.quiz.qCoinBimetal10',
    coins: [10],
    options: [
      {id: 'a', text: '₹1', isCorrect: false},
      {id: 'b', text: '₹2', isCorrect: false},
      {id: 'c', text: '₹5', isCorrect: false},
      {id: 'd', text: '₹10', isCorrect: true},
    ],
    explanationKey: 'math.money.quiz.expCoinBimetal10',
  },
  {
    id: 'mq_10',
    type: 'change',
    questionKey: 'math.money.quiz.qChange15From20',
    options: [
      {id: 'a', text: '₹2', isCorrect: false},
      {id: 'b', text: '₹5', isCorrect: true},
      {id: 'c', text: '₹10', isCorrect: false},
      {id: 'd', text: '₹15', isCorrect: false},
    ],
    explanationKey: 'math.money.quiz.expChange15From20',
  },
];
