import type {MathLesson} from './types';

export const MATH_LESSONS: readonly MathLesson[] = [
  {
    id: 'numbers',
    order: 1,
    icon: '🔢',
    accent: '#4DB7E8',
    titleTa: 'எண்களை கற்போம்',
    titleEn: 'Learn Numbers',
    subtitleTa: 'எண்களை அறிந்து கொள்',
    subtitleEn: 'Discover numbers',
    introTa: 'வணக்கம்! நான் உன் கணித நண்பன். எண்களை விளையாடி கற்போம்!',
    introEn:
      'Hello! Today we learn numbers. Look carefully. Let us count together!',
  },
  {
    id: 'counting',
    order: 2,
    icon: '🔢',
    accent: '#FF9F1C',
    titleTa: 'எண்ணுதல்',
    titleEn: 'Counting',
    subtitleTa: 'பழங்கள், விலங்குகள், பொம்மைகள்',
    subtitleEn: 'Fruits, animals, toys',
    introTa: 'இன்று பல விதமான பொருட்களை எண்ணுவோம். ஒவ்வொன்றையும் தொட்டு எண்ணு!',
    introEn: 'Hello! Today we count things. Tap each one. Count with me!',
  },
  {
    id: 'missing',
    order: 3,
    icon: '🔍',
    accent: '#8B5CF6',
    titleTa: 'காணாமல் போன எண்',
    titleEn: 'Missing Number',
    subtitleTa: 'விடுபட்ட எண்ணை கண்டுபிடி',
    subtitleEn: 'Find the missing number',
    introTa: 'எண் வரிசையில் ஒரு எண் மறைந்திருக்கும். அதை கண்டுபிடிப்போம்!',
    introEn: 'One number is missing in the row. Let us find it!',
  },
  {
    id: 'sequence',
    order: 4,
    icon: '🔢',
    accent: '#0F8B8D',
    titleTa: 'எண் வரிசை',
    titleEn: 'Number Sequence',
    subtitleTa: 'சிறியது மற்றும் பெரியது',
    subtitleEn: 'Smallest and biggest',
    introTa: 'பல எண்களில் சிறியது அல்லது பெரியது எது என்று தேர்வு செய்வோம்!',
    introEn: 'We will pick the smallest or biggest number in a group!',
  },
  {
    id: 'matching',
    order: 5,
    icon: '🎯',
    accent: '#E4578C',
    titleTa: 'எண் பொருத்தம்',
    titleEn: 'Number Matching',
    subtitleTa: 'எண்ணிக்கையை பொருத்து',
    subtitleEn: 'Match the count',
    introTa: 'பொருட்களை எண்ணி சரியான எண்ணைத் தேர்!',
    introEn: 'Count the objects and pick the right number!',
  },
  {
    id: 'compare',
    order: 6,
    icon: '⚖',
    accent: '#5B7CFA',
    titleTa: 'எண்களை ஒப்பிடு',
    titleEn: 'Compare Numbers',
    subtitleTa: 'பெரியது எது?',
    subtitleEn: 'Which is bigger?',
    introTa: 'இரண்டு எண்களில் பெரியது எது என்று பார்ப்போம்!',
    introEn: 'Let us see which of two numbers is bigger!',
  },
  {
    id: 'addition',
    order: 7,
    icon: '➕',
    accent: '#3D9A5F',
    titleTa: 'கூட்டல்',
    titleEn: 'Addition',
    subtitleTa: 'சேர்த்து எண்ணு',
    subtitleEn: 'Add them up',
    introTa: 'இரண்டு எண்களை சேர்த்து மொத்தம் கண்டுபிடிப்போம்!',
    introEn: 'We will add two numbers together!',
  },
  {
    id: 'subtraction',
    order: 8,
    icon: '➖',
    accent: '#FF6B4A',
    titleTa: 'கழித்தல்',
    titleEn: 'Subtraction',
    subtitleTa: 'எடுத்தால் எத்தனை?',
    subtitleEn: 'How many left?',
    introTa: 'சில பொருட்களை எடுத்தால் எத்தனை மீதம் என்று காண்போம்!',
    introEn: 'If we take some away, how many are left?',
  },
  {
    id: 'shapes',
    order: 9,
    icon: '🔷',
    accent: '#4DB7E8',
    titleTa: 'வடிவங்கள்',
    titleEn: 'Shapes',
    subtitleTa: 'வட்டம், சதுரம், முக்கோணம்',
    subtitleEn: 'Circles, squares, triangles',
    introTa: 'அழகான வடிவங்களை அறிந்து கொள்வோம்!',
    introEn: 'Let us learn beautiful shapes!',
  },
  {
    id: 'colors',
    order: 10,
    icon: '🎨',
    accent: '#E4578C',
    titleTa: 'நிறங்கள்',
    titleEn: 'Colors',
    subtitleTa: 'சிவப்பு, நீலம், பச்சை',
    subtitleEn: 'Red, blue, green',
    introTa: 'வண்ணமயமான நிறங்களை கற்போம்!',
    introEn: 'Let us learn colorful names!',
  },
  {
    id: 'big-small',
    order: 11,
    icon: '📏',
    accent: '#FF9F1C',
    titleTa: 'பெரியது & சிறியது',
    titleEn: 'Big and Small',
    subtitleTa: 'ஒப்பிட்டு பார்',
    subtitleEn: 'Compare sizes',
    introTa: 'பெரியது மற்றும் சிறியது எது என்று தேர்வு செய்வோம்!',
    introEn: 'We will pick what is big and what is small!',
  },
  {
    id: 'patterns',
    order: 12,
    icon: '🔢',
    accent: '#8B5CF6',
    titleTa: 'வடிவ வரிசை',
    titleEn: 'Patterns',
    subtitleTa: 'அடுத்து என்ன வரும்?',
    subtitleEn: 'What comes next?',
    introTa: 'வடிவ வரிசையை பார்த்து அடுத்து என்ன வரும் என்று கண்டுபிடிப்போம்!',
    introEn: 'Look at the pattern and find what comes next!',
  },
  {
    id: 'practice',
    order: 13,
    icon: '🏆',
    accent: '#F4B400',
    titleTa: 'பயிற்சி மண்டலம்',
    titleEn: 'Practice Zone',
    subtitleTa: 'எல்லா பாடங்களும் கலந்து',
    subtitleEn: 'Mixed practice',
    introTa:
      'பயிற்சி மண்டலம்! பல வகை கேள்விகள் வரும். எவ்வளவு நேரம் வேண்டுமானாலும் பயிற்சி செய்!',
    introEn:
      'Practice zone! Many kinds of questions — practice as long as you like!',
  },
];

export function getLesson(id: string) {
  const lesson = MATH_LESSONS.find(item => item.id === id);
  if (!lesson) {
    throw new Error(`Unknown math lesson: ${id}`);
  }
  return lesson;
}
