import type {
  ClockStep,
  DayOfWeekInfo,
  DayPartInfo,
  MonthInfo,
  SeasonInfo,
  TimeQuizQuestion,
  TimeTopicMeta,
} from '../entities/timeEntities';

export const TIME_TOPICS: readonly TimeTopicMeta[] = [
  {
    id: 'clock',
    titleKey: 'time.topics.clock.title',
    descriptionKey: 'time.topics.clock.desc',
    icon: '⏰',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    targetScreen: 'ClockLesson',
  },
  {
    id: 'day-parts',
    titleKey: 'time.topics.dayParts.title',
    descriptionKey: 'time.topics.dayParts.desc',
    icon: '🌅',
    accentColor: '#F59E0B',
    bgLightColor: '#FFFBEB',
    targetScreen: 'DayPartsLesson',
  },
  {
    id: 'days',
    titleKey: 'time.topics.days.title',
    descriptionKey: 'time.topics.days.desc',
    icon: '📅',
    accentColor: '#10B981',
    bgLightColor: '#ECFDF5',
    targetScreen: 'DaysLesson',
  },
  {
    id: 'months',
    titleKey: 'time.topics.months.title',
    descriptionKey: 'time.topics.months.desc',
    icon: '📆',
    accentColor: '#8B5CF6',
    bgLightColor: '#F5F3FF',
    targetScreen: 'MonthsLesson',
  },
  {
    id: 'seasons',
    titleKey: 'time.topics.seasons.title',
    descriptionKey: 'time.topics.seasons.desc',
    icon: '🌦️',
    accentColor: '#EC4899',
    bgLightColor: '#FDF2F8',
    targetScreen: 'SeasonsLesson',
  },
  {
    id: 'calendar',
    titleKey: 'time.topics.calendar.title',
    descriptionKey: 'time.topics.calendar.desc',
    icon: '🗓️',
    accentColor: '#06B6D4',
    bgLightColor: '#ECFEFF',
    targetScreen: 'CalendarLesson',
  },
  {
    id: 'quiz',
    titleKey: 'time.topics.quiz.title',
    descriptionKey: 'time.topics.quiz.desc',
    icon: '🎯',
    accentColor: '#6366F1',
    bgLightColor: '#EEF2FF',
    targetScreen: 'TimeQuiz',
  },
];

export const CLOCK_LESSONS: readonly ClockStep[] = [
  {
    id: 'intro_hands',
    hour: 3,
    minute: 0,
    titleKey: 'time.clock.introHandsTitle',
    explanationKey: 'time.clock.introHandsDesc',
    speechText:
      'A clock has two main hands! The short blue hand tells the hour. The long red hand tells the minute.',
  },
  {
    id: 'oclock_3',
    hour: 3,
    minute: 0,
    titleKey: 'time.clock.oclock3Title',
    explanationKey: 'time.clock.oclock3Desc',
    speechText:
      'When the long minute hand points to 12, it is o clock! Here, the short hand points to 3, so it is 3 o clock (3:00)!',
  },
  {
    id: 'half_past_3',
    hour: 3,
    minute: 30,
    titleKey: 'time.clock.halfPast3Title',
    explanationKey: 'time.clock.halfPast3Desc',
    speechText:
      'When the minute hand points down to 6, 30 minutes have passed! This is 3:30 or half past 3.',
  },
  {
    id: 'oclock_4',
    hour: 4,
    minute: 0,
    titleKey: 'time.clock.oclock4Title',
    explanationKey: 'time.clock.oclock4Desc',
    speechText:
      'Now look! The hour hand points at 4 and minute hand at 12. It is 4 o clock (4:00)!',
  },
  {
    id: 'half_past_5',
    hour: 5,
    minute: 30,
    titleKey: 'time.clock.halfPast5Title',
    explanationKey: 'time.clock.halfPast5Desc',
    speechText:
      'Here the short hand is between 5 and 6, and the long hand points to 6. That is 5:30 (half past 5)!',
  },
];

export const CLOCK_CHALLENGES: readonly {
  readonly id: string;
  readonly targetHour: number;
  readonly targetMinute: number;
  readonly promptKey: string;
  readonly explanationKey: string;
}[] = [
  {
    id: 'challenge_1',
    targetHour: 3,
    targetMinute: 0,
    promptKey: 'time.clock.challenge.set300',
    explanationKey: 'time.clock.challenge.set300Exp',
  },
  {
    id: 'challenge_2',
    targetHour: 3,
    targetMinute: 30,
    promptKey: 'time.clock.challenge.set330',
    explanationKey: 'time.clock.challenge.set330Exp',
  },
  {
    id: 'challenge_3',
    targetHour: 4,
    targetMinute: 0,
    promptKey: 'time.clock.challenge.set400',
    explanationKey: 'time.clock.challenge.set400Exp',
  },
  {
    id: 'challenge_4',
    targetHour: 5,
    targetMinute: 30,
    promptKey: 'time.clock.challenge.set530',
    explanationKey: 'time.clock.challenge.set530Exp',
  },
  {
    id: 'challenge_5',
    targetHour: 7,
    targetMinute: 0,
    promptKey: 'time.clock.challenge.set700',
    explanationKey: 'time.clock.challenge.set700Exp',
  },
  {
    id: 'challenge_6',
    targetHour: 9,
    targetMinute: 30,
    promptKey: 'time.clock.challenge.set930',
    explanationKey: 'time.clock.challenge.set930Exp',
  },
];

export const DAY_PARTS: readonly DayPartInfo[] = [
  {
    id: 'morning',
    nameKey: 'time.dayParts.morning.name',
    icon: '🌅',
    timeRange: '6:00 AM – 12:00 PM',
    skyGradient: ['#FDE68A', '#FEF3C7'],
    descriptionKey: 'time.dayParts.morning.desc',
    activities: [
      {icon: '🛏️', titleKey: 'time.dayParts.morning.act1'},
      {icon: '🪥', titleKey: 'time.dayParts.morning.act2'},
      {icon: '🥣', titleKey: 'time.dayParts.morning.act3'},
      {icon: '🎒', titleKey: 'time.dayParts.morning.act4'},
    ],
  },
  {
    id: 'afternoon',
    nameKey: 'time.dayParts.afternoon.name',
    icon: '☀️',
    timeRange: '12:00 PM – 5:00 PM',
    skyGradient: ['#60A5FA', '#BAE6FD'],
    descriptionKey: 'time.dayParts.afternoon.desc',
    activities: [
      {icon: '🍱', titleKey: 'time.dayParts.afternoon.act1'},
      {icon: '📚', titleKey: 'time.dayParts.afternoon.act2'},
      {icon: '🎨', titleKey: 'time.dayParts.afternoon.act3'},
      {icon: '🍎', titleKey: 'time.dayParts.afternoon.act4'},
    ],
  },
  {
    id: 'evening',
    nameKey: 'time.dayParts.evening.name',
    icon: '🌆',
    timeRange: '5:00 PM – 8:00 PM',
    skyGradient: ['#FB923C', '#F472B6'],
    descriptionKey: 'time.dayParts.evening.desc',
    activities: [
      {icon: '⚽', titleKey: 'time.dayParts.evening.act1'},
      {icon: '🚲', titleKey: 'time.dayParts.evening.act2'},
      {icon: '📖', titleKey: 'time.dayParts.evening.act3'},
      {icon: '🍲', titleKey: 'time.dayParts.evening.act4'},
    ],
  },
  {
    id: 'night',
    nameKey: 'time.dayParts.night.name',
    icon: '🌙',
    timeRange: '8:00 PM – 6:00 AM',
    skyGradient: ['#1E1B4B', '#312E81'],
    descriptionKey: 'time.dayParts.night.desc',
    activities: [
      {icon: '✨', titleKey: 'time.dayParts.night.act1'},
      {icon: '📚', titleKey: 'time.dayParts.night.act2'},
      {icon: '🧸', titleKey: 'time.dayParts.night.act3'},
      {icon: '😴', titleKey: 'time.dayParts.night.act4'},
    ],
  },
];

export const DAYS_OF_WEEK: readonly DayOfWeekInfo[] = [
  {
    id: 'monday',
    dayIndex: 1,
    nameKey: 'time.days.monday',
    shortNameKey: 'time.days.mon',
    color: '#EF4444',
    icon: '🎒',
    activityKey: 'time.days.mondayAct',
  },
  {
    id: 'tuesday',
    dayIndex: 2,
    nameKey: 'time.days.tuesday',
    shortNameKey: 'time.days.tue',
    color: '#F97316',
    icon: '🎨',
    activityKey: 'time.days.tuesdayAct',
  },
  {
    id: 'wednesday',
    dayIndex: 3,
    nameKey: 'time.days.wednesday',
    shortNameKey: 'time.days.wed',
    color: '#EAB308',
    icon: '🎵',
    activityKey: 'time.days.wednesdayAct',
  },
  {
    id: 'thursday',
    dayIndex: 4,
    nameKey: 'time.days.thursday',
    shortNameKey: 'time.days.thu',
    color: '#10B981',
    icon: '🔬',
    activityKey: 'time.days.thursdayAct',
  },
  {
    id: 'friday',
    dayIndex: 5,
    nameKey: 'time.days.friday',
    shortNameKey: 'time.days.fri',
    color: '#06B6D4',
    icon: '⚽',
    activityKey: 'time.days.fridayAct',
  },
  {
    id: 'saturday',
    dayIndex: 6,
    nameKey: 'time.days.saturday',
    shortNameKey: 'time.days.sat',
    color: '#8B5CF6',
    icon: '🍦',
    activityKey: 'time.days.saturdayAct',
  },
  {
    id: 'sunday',
    dayIndex: 0,
    nameKey: 'time.days.sunday',
    shortNameKey: 'time.days.sun',
    color: '#EC4899',
    icon: '🎪',
    activityKey: 'time.days.sundayAct',
  },
];

export const MONTHS_OF_YEAR: readonly MonthInfo[] = [
  {
    id: 'january',
    monthIndex: 0,
    nameKey: 'time.months.january',
    shortNameKey: 'time.months.jan',
    daysCount: 31,
    seasonId: 'winter',
    icon: '❄️',
    color: '#38BDF8',
    highlightKey: 'time.months.janHighlight',
  },
  {
    id: 'february',
    monthIndex: 1,
    nameKey: 'time.months.february',
    shortNameKey: 'time.months.feb',
    daysCount: 28,
    seasonId: 'winter',
    icon: '❤️',
    color: '#F472B6',
    highlightKey: 'time.months.febHighlight',
  },
  {
    id: 'march',
    monthIndex: 2,
    nameKey: 'time.months.march',
    shortNameKey: 'time.months.mar',
    daysCount: 31,
    seasonId: 'summer',
    icon: '🌱',
    color: '#4ADE80',
    highlightKey: 'time.months.marHighlight',
  },
  {
    id: 'april',
    monthIndex: 3,
    nameKey: 'time.months.april',
    shortNameKey: 'time.months.apr',
    daysCount: 30,
    seasonId: 'summer',
    icon: '🌸',
    color: '#FB7185',
    highlightKey: 'time.months.aprHighlight',
  },
  {
    id: 'may',
    monthIndex: 4,
    nameKey: 'time.months.may',
    shortNameKey: 'time.months.mayShort',
    daysCount: 31,
    seasonId: 'summer',
    icon: '☀️',
    color: '#FBBF24',
    highlightKey: 'time.months.mayHighlight',
  },
  {
    id: 'june',
    monthIndex: 5,
    nameKey: 'time.months.june',
    shortNameKey: 'time.months.jun',
    daysCount: 30,
    seasonId: 'rainy',
    icon: '🌧️',
    color: '#60A5FA',
    highlightKey: 'time.months.junHighlight',
  },
  {
    id: 'july',
    monthIndex: 6,
    nameKey: 'time.months.july',
    shortNameKey: 'time.months.jul',
    daysCount: 31,
    seasonId: 'rainy',
    icon: '🌈',
    color: '#A78BFA',
    highlightKey: 'time.months.julHighlight',
  },
  {
    id: 'august',
    monthIndex: 7,
    nameKey: 'time.months.august',
    shortNameKey: 'time.months.aug',
    daysCount: 31,
    seasonId: 'rainy',
    icon: '🪁',
    color: '#34D399',
    highlightKey: 'time.months.augHighlight',
  },
  {
    id: 'september',
    monthIndex: 8,
    nameKey: 'time.months.september',
    shortNameKey: 'time.months.sep',
    daysCount: 30,
    seasonId: 'autumn',
    icon: '🍂',
    color: '#FB923C',
    highlightKey: 'time.months.sepHighlight',
  },
  {
    id: 'october',
    monthIndex: 9,
    nameKey: 'time.months.october',
    shortNameKey: 'time.months.oct',
    daysCount: 31,
    seasonId: 'autumn',
    icon: '🎃',
    color: '#F97316',
    highlightKey: 'time.months.octHighlight',
  },
  {
    id: 'november',
    monthIndex: 10,
    nameKey: 'time.months.november',
    shortNameKey: 'time.months.nov',
    daysCount: 30,
    seasonId: 'winter',
    icon: '🧣',
    color: '#818CF8',
    highlightKey: 'time.months.novHighlight',
  },
  {
    id: 'december',
    monthIndex: 11,
    nameKey: 'time.months.december',
    shortNameKey: 'time.months.dec',
    daysCount: 31,
    seasonId: 'winter',
    icon: '🎄',
    color: '#10B981',
    highlightKey: 'time.months.decHighlight',
  },
];

export const SEASONS_DATA: readonly SeasonInfo[] = [
  {
    id: 'summer',
    nameKey: 'time.seasons.summer.name',
    icon: '☀️',
    color: '#F59E0B',
    bgGradient: ['#FEF3C7', '#FDE68A'],
    monthsKey: 'time.seasons.summer.months',
    weatherKey: 'time.seasons.summer.weather',
    clothesKey: 'time.seasons.summer.clothes',
    activitiesKey: 'time.seasons.summer.activities',
    funFactKey: 'time.seasons.summer.funFact',
    visualElements: ['🕶️', '🍦', '🏖️', '🍉', '🌻'],
  },
  {
    id: 'rainy',
    nameKey: 'time.seasons.rainy.name',
    icon: '🌧️',
    color: '#3B82F6',
    bgGradient: ['#E0F2FE', '#BAE6FD'],
    monthsKey: 'time.seasons.rainy.months',
    weatherKey: 'time.seasons.rainy.weather',
    clothesKey: 'time.seasons.rainy.clothes',
    activitiesKey: 'time.seasons.rainy.activities',
    funFactKey: 'time.seasons.rainy.funFact',
    visualElements: ['☔', '🐸', '🌈', '⛵', '🌧️'],
  },
  {
    id: 'autumn',
    nameKey: 'time.seasons.autumn.name',
    icon: '🍂',
    color: '#EA580C',
    bgGradient: ['#FFEDD5', '#FED7AA'],
    monthsKey: 'time.seasons.autumn.months',
    weatherKey: 'time.seasons.autumn.weather',
    clothesKey: 'time.seasons.autumn.clothes',
    activitiesKey: 'time.seasons.autumn.activities',
    funFactKey: 'time.seasons.autumn.funFact',
    visualElements: ['🍁', '🎃', '🐿️', '🌾', '🍄'],
  },
  {
    id: 'winter',
    nameKey: 'time.seasons.winter.name',
    icon: '❄️',
    color: '#0284C7',
    bgGradient: ['#F0F9FF', '#E0F2FE'],
    monthsKey: 'time.seasons.winter.months',
    weatherKey: 'time.seasons.winter.weather',
    clothesKey: 'time.seasons.winter.clothes',
    activitiesKey: 'time.seasons.winter.activities',
    funFactKey: 'time.seasons.winter.funFact',
    visualElements: ['⛄', '🧣', '🧤', '☕', '🎄'],
  },
];

export const TIME_QUIZ_QUESTIONS: readonly TimeQuizQuestion[] = [
  {
    id: 'q_clock_300',
    type: 'clock_identify',
    questionKey: 'time.quiz.qClock300',
    clockHour: 3,
    clockMinute: 0,
    options: [
      {id: 'a', text: '3:00', isCorrect: true},
      {id: 'b', text: '12:00', isCorrect: false},
      {id: 'c', text: '3:30', isCorrect: false},
      {id: 'd', text: '4:00', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expClock300',
  },
  {
    id: 'q_day_after_tue',
    type: 'day_sequence',
    questionKey: 'time.quiz.qDayAfterTue',
    options: [
      {id: 'a', labelKey: 'time.days.monday', isCorrect: false},
      {id: 'b', labelKey: 'time.days.wednesday', isCorrect: true},
      {id: 'c', labelKey: 'time.days.thursday', isCorrect: false},
      {id: 'd', labelKey: 'time.days.friday', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expDayAfterTue',
  },
  {
    id: 'q_clock_530',
    type: 'clock_identify',
    questionKey: 'time.quiz.qClock530',
    clockHour: 5,
    clockMinute: 30,
    options: [
      {id: 'a', text: '5:00', isCorrect: false},
      {id: 'b', text: '6:30', isCorrect: false},
      {id: 'c', text: '5:30', isCorrect: true},
      {id: 'd', text: '6:00', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expClock530',
  },
  {
    id: 'q_yesterday_scenario',
    type: 'yesterday_tomorrow',
    questionKey: 'time.quiz.qYesterdayMon',
    options: [
      {id: 'a', labelKey: 'time.days.sunday', isCorrect: true},
      {id: 'b', labelKey: 'time.days.tuesday', isCorrect: false},
      {id: 'c', labelKey: 'time.days.wednesday', isCorrect: false},
      {id: 'd', labelKey: 'time.days.saturday', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expYesterdayMon',
  },
  {
    id: 'q_tomorrow_scenario',
    type: 'yesterday_tomorrow',
    questionKey: 'time.quiz.qTomorrowFri',
    options: [
      {id: 'a', labelKey: 'time.days.thursday', isCorrect: false},
      {id: 'b', labelKey: 'time.days.saturday', isCorrect: true},
      {id: 'c', labelKey: 'time.days.sunday', isCorrect: false},
      {id: 'd', labelKey: 'time.days.monday', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expTomorrowFri',
  },
  {
    id: 'q_first_month',
    type: 'month_sequence',
    questionKey: 'time.quiz.qFirstMonth',
    options: [
      {id: 'a', labelKey: 'time.months.january', isCorrect: true},
      {id: 'b', labelKey: 'time.months.december', isCorrect: false},
      {id: 'c', labelKey: 'time.months.march', isCorrect: false},
      {id: 'd', labelKey: 'time.months.july', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expFirstMonth',
  },
  {
    id: 'q_month_after_aug',
    type: 'month_sequence',
    questionKey: 'time.quiz.qMonthAfterAug',
    options: [
      {id: 'a', labelKey: 'time.months.july', isCorrect: false},
      {id: 'b', labelKey: 'time.months.october', isCorrect: false},
      {id: 'c', labelKey: 'time.months.september', isCorrect: true},
      {id: 'd', labelKey: 'time.months.november', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expMonthAfterAug',
  },
  {
    id: 'q_season_umbrella',
    type: 'season_match',
    questionKey: 'time.quiz.qSeasonUmbrella',
    options: [
      {
        id: 'a',
        labelKey: 'time.seasons.summer.name',
        icon: '☀️',
        isCorrect: false,
      },
      {
        id: 'b',
        labelKey: 'time.seasons.rainy.name',
        icon: '🌧️',
        isCorrect: true,
      },
      {
        id: 'c',
        labelKey: 'time.seasons.winter.name',
        icon: '❄️',
        isCorrect: false,
      },
      {
        id: 'd',
        labelKey: 'time.seasons.autumn.name',
        icon: '🍂',
        isCorrect: false,
      },
    ],
    explanationKey: 'time.quiz.expSeasonUmbrella',
  },
  {
    id: 'q_day_parts_breakfast',
    type: 'day_part',
    questionKey: 'time.quiz.qDayPartsBreakfast',
    options: [
      {
        id: 'a',
        labelKey: 'time.dayParts.morning.name',
        icon: '🌅',
        isCorrect: true,
      },
      {
        id: 'b',
        labelKey: 'time.dayParts.afternoon.name',
        icon: '☀️',
        isCorrect: false,
      },
      {
        id: 'c',
        labelKey: 'time.dayParts.evening.name',
        icon: '🌆',
        isCorrect: false,
      },
      {
        id: 'd',
        labelKey: 'time.dayParts.night.name',
        icon: '🌙',
        isCorrect: false,
      },
    ],
    explanationKey: 'time.quiz.expDayPartsBreakfast',
  },
  {
    id: 'q_clock_400',
    type: 'clock_identify',
    questionKey: 'time.quiz.qClock400',
    clockHour: 4,
    clockMinute: 0,
    options: [
      {id: 'a', text: '4:00', isCorrect: true},
      {id: 'b', text: '12:20', isCorrect: false},
      {id: 'c', text: '4:30', isCorrect: false},
      {id: 'd', text: '3:00', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expClock400',
  },
  {
    id: 'q_calendar_days_week',
    type: 'calendar_read',
    questionKey: 'time.quiz.qCalendarDaysWeek',
    options: [
      {id: 'a', text: '5', isCorrect: false},
      {id: 'b', text: '7', isCorrect: true},
      {id: 'c', text: '12', isCorrect: false},
      {id: 'd', text: '30', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expCalendarDaysWeek',
  },
  {
    id: 'q_months_in_year',
    type: 'calendar_read',
    questionKey: 'time.quiz.qMonthsInYear',
    options: [
      {id: 'a', text: '7', isCorrect: false},
      {id: 'b', text: '10', isCorrect: false},
      {id: 'c', text: '12', isCorrect: true},
      {id: 'd', text: '24', isCorrect: false},
    ],
    explanationKey: 'time.quiz.expMonthsInYear',
  },
];
