import type {
  ShapeAroundUsItem,
  ShapeComparisonItem,
  ShapeCountItem,
  ShapeDefinition,
  ShapeMatchingPair,
  ShapePatternItem,
  ShapePuzzleItem,
  ShapeQuizQuestion,
  ShapeRecognitionItem,
  ShapeSortingLevel,
  ShapeSubModuleConfig,
} from '../entities/shapeEntities';

export const SHAPES_SUB_MODULES: readonly ShapeSubModuleConfig[] = [
  {
    id: 'learn_shapes',
    titleKey: 'shapes.submodules.learnShapes',
    subtitleKey: 'shapes.submodules.learnShapesSub',
    emoji: '🔍',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    orderIndex: 1,
    routeName: 'LearnShapes',
  },
  {
    id: 'recognition',
    titleKey: 'shapes.submodules.recognition',
    subtitleKey: 'shapes.submodules.recognitionSub',
    emoji: '👀',
    accentColor: '#8B5CF6',
    bgLightColor: '#F5F3FF',
    orderIndex: 2,
    routeName: 'ShapeRecognition',
  },
  {
    id: 'matching',
    titleKey: 'shapes.submodules.matching',
    subtitleKey: 'shapes.submodules.matchingSub',
    emoji: '🧩',
    accentColor: '#EC4899',
    bgLightColor: '#FDF2F8',
    orderIndex: 3,
    routeName: 'ShapeMatching',
  },
  {
    id: 'properties',
    titleKey: 'shapes.submodules.properties',
    subtitleKey: 'shapes.submodules.propertiesSub',
    emoji: '📐',
    accentColor: '#10B981',
    bgLightColor: '#ECFDF5',
    orderIndex: 4,
    routeName: 'ShapeProperties',
  },
  {
    id: 'sorting',
    titleKey: 'shapes.submodules.sorting',
    subtitleKey: 'shapes.submodules.sortingSub',
    emoji: '📦',
    accentColor: '#F59E0B',
    bgLightColor: '#FFFBEB',
    orderIndex: 5,
    routeName: 'ShapeSorting',
  },
  {
    id: 'compare',
    titleKey: 'shapes.submodules.compare',
    subtitleKey: 'shapes.submodules.compareSub',
    emoji: '⚖️',
    accentColor: '#0EA5E9',
    bgLightColor: '#F0F9FF',
    orderIndex: 6,
    routeName: 'ShapeCompare',
  },
  {
    id: 'around_us',
    titleKey: 'shapes.submodules.aroundUs',
    subtitleKey: 'shapes.submodules.aroundUsSub',
    emoji: '🏠',
    accentColor: '#14B8A6',
    bgLightColor: '#F0FDFA',
    orderIndex: 7,
    routeName: 'ShapesAroundUs',
  },
  {
    id: 'count',
    titleKey: 'shapes.submodules.count',
    subtitleKey: 'shapes.submodules.countSub',
    emoji: '🔢',
    accentColor: '#6366F1',
    bgLightColor: '#EEF2FF',
    orderIndex: 8,
    routeName: 'ShapeCount',
  },
  {
    id: 'patterns',
    titleKey: 'shapes.submodules.patterns',
    subtitleKey: 'shapes.submodules.patternsSub',
    emoji: '🔄',
    accentColor: '#F97316',
    bgLightColor: '#FFF7ED',
    orderIndex: 9,
    routeName: 'ShapePatterns',
  },
  {
    id: 'puzzles',
    titleKey: 'shapes.submodules.puzzles',
    subtitleKey: 'shapes.submodules.puzzlesSub',
    emoji: '🧠',
    accentColor: '#D946EF',
    bgLightColor: '#FDF4FF',
    orderIndex: 10,
    routeName: 'ShapePuzzles',
  },
  {
    id: 'challenge',
    titleKey: 'shapes.submodules.challenge',
    subtitleKey: 'shapes.submodules.challengeSub',
    emoji: '🏆',
    accentColor: '#EA580C',
    bgLightColor: '#FFF7ED',
    orderIndex: 11,
    routeName: 'ShapeChallenge',
  },
];

export const SHAPES_DATA: readonly ShapeDefinition[] = [
  {
    id: 'circle',
    name: 'Circle',
    emoji: '⭕',
    color: '#EF4444',
    lightColor: '#FEE2E2',
    darkColor: '#B91C1C',
    sides: 0,
    corners: 0,
    isCurved: true,
    description: 'A circle is completely round with no sides and no corners!',
    audioPronunciation:
      'Circle. A circle is round and has no straight sides or corners.',
    sideLabels: [],
    cornerLabels: [],
    realWorldExamples: [
      {
        id: 'ball',
        name: 'Soccer Ball',
        emoji: '⚽',
        description: 'A round ball that rolls smoothly',
      },
      {
        id: 'coin',
        name: 'Golden Coin',
        emoji: '🪙',
        description: 'A round shiny coin in your pocket',
      },
      {
        id: 'plate',
        name: 'Dinner Plate',
        emoji: '🍽️',
        description: 'A round plate for yummy meals',
      },
      {
        id: 'clock',
        name: 'Wall Clock',
        emoji: '⏰',
        description: 'A round clock that tells time',
      },
    ],
    funFact: 'A wheel is shaped like a circle so it can roll without bumping!',
  },
  {
    id: 'square',
    name: 'Square',
    emoji: '⬜',
    color: '#3B82F6',
    lightColor: '#DBEAFE',
    darkColor: '#1D4ED8',
    sides: 4,
    corners: 4,
    isCurved: false,
    description: 'A square has 4 equal straight sides and 4 square corners!',
    audioPronunciation: 'Square. A square has 4 equal sides and 4 corners.',
    sideLabels: ['Top Side', 'Right Side', 'Bottom Side', 'Left Side'],
    cornerLabels: [
      'Top-Left Corner',
      'Top-Right Corner',
      'Bottom-Right Corner',
      'Bottom-Left Corner',
    ],
    realWorldExamples: [
      {
        id: 'window',
        name: 'Window Frame',
        emoji: '🪟',
        description: 'A square glass window pane',
      },
      {
        id: 'tile',
        name: 'Floor Tile',
        emoji: '🧱',
        description: 'A square tile that fits neatly',
      },
      {
        id: 'gift',
        name: 'Gift Box',
        emoji: '🎁',
        description: 'A square box wrapped with a bow',
      },
      {
        id: 'dice',
        name: 'Game Die',
        emoji: '🎲',
        description: 'A square cube with dots',
      },
    ],
    funFact: 'All 4 sides of a square are always the exact same length!',
  },
  {
    id: 'triangle',
    name: 'Triangle',
    emoji: '🔺',
    color: '#EAB308',
    lightColor: '#FEF9C3',
    darkColor: '#A16207',
    sides: 3,
    corners: 3,
    isCurved: false,
    description: 'A triangle has 3 straight sides and 3 pointy corners!',
    audioPronunciation:
      'Triangle. A triangle has 3 straight sides and 3 corners.',
    sideLabels: ['Left Slant', 'Right Slant', 'Flat Bottom'],
    cornerLabels: [
      'Top Peak Corner',
      'Bottom-Right Corner',
      'Bottom-Left Corner',
    ],
    realWorldExamples: [
      {
        id: 'pizza',
        name: 'Pizza Slice',
        emoji: '🍕',
        description: 'A yummy triangular slice of pizza',
      },
      {
        id: 'sign',
        name: 'Traffic Warning Sign',
        emoji: '🚦',
        description: 'A triangle sign on the road',
      },
      {
        id: 'roof',
        name: 'House Roof',
        emoji: '🏠',
        description: 'A triangular pointy roof',
      },
      {
        id: 'watermelon',
        name: 'Watermelon Slice',
        emoji: '🍉',
        description: 'A fresh triangle slice of fruit',
      },
    ],
    funFact:
      'The pyramids of Egypt have triangular faces that reach toward the sky!',
  },
  {
    id: 'rectangle',
    name: 'Rectangle',
    emoji: '▭',
    color: '#10B981',
    lightColor: '#D1FAE5',
    darkColor: '#047857',
    sides: 4,
    corners: 4,
    isCurved: false,
    description: 'A rectangle has 2 long sides, 2 short sides, and 4 corners!',
    audioPronunciation:
      'Rectangle. A rectangle has 2 long sides, 2 short sides, and 4 corners.',
    sideLabels: [
      'Top Long Side',
      'Right Short Side',
      'Bottom Long Side',
      'Left Short Side',
    ],
    cornerLabels: [
      'Top-Left Corner',
      'Top-Right Corner',
      'Bottom-Right Corner',
      'Bottom-Left Corner',
    ],
    realWorldExamples: [
      {
        id: 'door',
        name: 'Room Door',
        emoji: '🚪',
        description: 'A tall rectangle door',
      },
      {
        id: 'book',
        name: 'Storybook',
        emoji: '📖',
        description: 'A rectangular reading book',
      },
      {
        id: 'tv',
        name: 'Television Screen',
        emoji: '📺',
        description: 'A wide rectangle television screen',
      },
      {
        id: 'phone',
        name: 'Mobile Phone',
        emoji: '📱',
        description: 'A handheld rectangle smartphone',
      },
    ],
    funFact:
      'Every square is a special rectangle, but not every rectangle is a square!',
  },
  {
    id: 'oval',
    name: 'Oval',
    emoji: '🥚',
    color: '#F97316',
    lightColor: '#FFEDD5',
    darkColor: '#C2410C',
    sides: 0,
    corners: 0,
    isCurved: true,
    description:
      'An oval looks like a stretched, egg-shaped circle with no corners!',
    audioPronunciation:
      'Oval. An oval is curved like an egg with zero corners.',
    sideLabels: [],
    cornerLabels: [],
    realWorldExamples: [
      {
        id: 'egg',
        name: 'Bird Egg',
        emoji: '🥚',
        description: 'A smooth oval egg in a nest',
      },
      {
        id: 'rugby',
        name: 'Rugby Ball',
        emoji: '🏉',
        description: 'An oval sports ball',
      },
      {
        id: 'mirror',
        name: 'Vanity Mirror',
        emoji: '🪞',
        description: 'An elegant oval wall mirror',
      },
    ],
    funFact:
      'Watermelons and rugby balls are shaped like 3D ovals called ellipsoids!',
  },
  {
    id: 'star',
    name: 'Star',
    emoji: '⭐',
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    darkColor: '#B45309',
    sides: 10,
    corners: 5,
    isCurved: false,
    description: 'A star has 5 glowing points that twinkle in the sky!',
    audioPronunciation: 'Star. A 5-pointed star twinkles in the sky.',
    sideLabels: ['Side 1', 'Side 2', 'Side 3', 'Side 4', 'Side 5'],
    cornerLabels: [
      'Top Point',
      'Upper Right Point',
      'Lower Right Point',
      'Lower Left Point',
      'Upper Left Point',
    ],
    realWorldExamples: [
      {
        id: 'star_decor',
        name: 'Tree Star',
        emoji: '🌟',
        description: 'A bright star decoration',
      },
      {
        id: 'starfish',
        name: 'Ocean Starfish',
        emoji: '⭐',
        description: 'A star-shaped sea creature',
      },
    ],
    funFact:
      'Real stars in space are giant balls of burning gas that look like points from Earth!',
  },
  {
    id: 'heart',
    name: 'Heart',
    emoji: '❤️',
    color: '#EC4899',
    lightColor: '#FCE7F3',
    darkColor: '#BE185D',
    sides: 2,
    corners: 2,
    isCurved: true,
    description: 'A heart has 2 curved top arches meeting at a bottom tip!',
    audioPronunciation:
      'Heart. A heart shape has two rounded arches that meet at a point.',
    sideLabels: ['Left Arch', 'Right Arch'],
    cornerLabels: ['Top Dip', 'Bottom Point'],
    realWorldExamples: [
      {
        id: 'card',
        name: 'Greeting Card',
        emoji: '💌',
        description: 'A card filled with love hearts',
      },
      {
        id: 'balloon',
        name: 'Heart Balloon',
        emoji: '🎈',
        description: 'A floating heart balloon',
      },
    ],
    funFact:
      'The heart shape has been used for hundreds of years as a symbol of love and kindness.',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    emoji: '♦️',
    color: '#8B5CF6',
    lightColor: '#EDE9FE',
    darkColor: '#6D28D9',
    sides: 4,
    corners: 4,
    isCurved: false,
    description:
      'A diamond (or rhombus) has 4 slanted sides like a soaring kite!',
    audioPronunciation:
      'Diamond. A diamond shape has 4 slanted sides and 4 pointy corners.',
    sideLabels: ['Top Left', 'Top Right', 'Bottom Right', 'Bottom Left'],
    cornerLabels: [
      'Top Corner',
      'Right Corner',
      'Bottom Corner',
      'Left Corner',
    ],
    realWorldExamples: [
      {
        id: 'kite',
        name: 'Flying Kite',
        emoji: '🪁',
        description: 'A colorful diamond kite in the breeze',
      },
      {
        id: 'gem',
        name: 'Shiny Crystal Gem',
        emoji: '💎',
        description: 'A sparkling diamond jewel',
      },
    ],
    funFact:
      'Diamonds are the hardest natural minerals on the entire planet Earth!',
  },
  {
    id: 'crescent',
    name: 'Crescent',
    emoji: '🌙',
    color: '#6366F1',
    lightColor: '#EEF2FF',
    darkColor: '#4338CA',
    sides: 2,
    corners: 2,
    isCurved: true,
    description: 'A crescent curves like the silver night moon or a banana!',
    audioPronunciation:
      'Crescent. A crescent curves like the glowing night moon.',
    sideLabels: ['Outer Curve', 'Inner Curve'],
    cornerLabels: ['Top Tip', 'Bottom Tip'],
    realWorldExamples: [
      {
        id: 'moon',
        name: 'Crescent Moon',
        emoji: '🌙',
        description: 'The glowing crescent moon at night',
      },
      {
        id: 'croissant',
        name: 'Bakery Croissant',
        emoji: '🥐',
        description: 'A flaky crescent-shaped pastry',
      },
    ],
    funFact:
      'The moon appears as a crescent when the sun lights up only a sliver of it!',
  },
  {
    id: 'hexagon',
    name: 'Hexagon',
    emoji: '⬢',
    color: '#14B8A6',
    lightColor: '#F0FDFA',
    darkColor: '#0F766E',
    sides: 6,
    corners: 6,
    isCurved: false,
    description:
      'A hexagon has 6 straight sides and 6 corners like a honeycomb cell!',
    audioPronunciation:
      'Hexagon. A hexagon has 6 straight sides and 6 corners.',
    sideLabels: ['Side 1', 'Side 2', 'Side 3', 'Side 4', 'Side 5', 'Side 6'],
    cornerLabels: [
      'Corner 1',
      'Corner 2',
      'Corner 3',
      'Corner 4',
      'Corner 5',
      'Corner 6',
    ],
    realWorldExamples: [
      {
        id: 'honeycomb',
        name: 'Bee Honeycomb',
        emoji: '🍯',
        description: 'Hexagon cells built by honeybees',
      },
      {
        id: 'nut',
        name: 'Metal Bolt Nut',
        emoji: '🔩',
        description: 'A 6-sided hexagon wrench bolt',
      },
    ],
    funFact:
      'Honeybees build hexagon combs because hexagons pack the most honey with the least wax!',
  },
  {
    id: 'pentagon',
    name: 'Pentagon',
    emoji: '⬡',
    color: '#EA580C',
    lightColor: '#FFF7ED',
    darkColor: '#C2410C',
    sides: 5,
    corners: 5,
    isCurved: false,
    description:
      'A pentagon has 5 straight sides and 5 corners like a house outline!',
    audioPronunciation:
      'Pentagon. A pentagon has 5 straight sides and 5 corners.',
    sideLabels: ['Side 1', 'Side 2', 'Side 3', 'Side 4', 'Side 5'],
    cornerLabels: ['Corner 1', 'Corner 2', 'Corner 3', 'Corner 4', 'Corner 5'],
    realWorldExamples: [
      {
        id: 'soccer_patch',
        name: 'Soccer Ball Patch',
        emoji: '⚽',
        description: 'Black pentagon patches on soccer balls',
      },
      {
        id: 'birdhouse',
        name: 'Bird House Front',
        emoji: '🏠',
        description: 'A 5-sided house shape',
      },
    ],
    funFact: 'Penta means five in ancient Greek!',
  },
];

export const SHAPE_RECOGNITION_ITEMS: readonly ShapeRecognitionItem[] = [
  {
    id: 'rec_circle',
    prompt: 'Which one is a Circle?',
    targetShapeId: 'circle',
    options: [
      {
        id: 'opt1',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        rotationDeg: 0,
        scale: 1,
      },
      {
        id: 'opt2',
        shapeId: 'circle',
        emoji: '⭕',
        color: '#EF4444',
        rotationDeg: 45,
        scale: 1.1,
      },
      {
        id: 'opt3',
        shapeId: 'square',
        emoji: '⬜',
        color: '#3B82F6',
        rotationDeg: 0,
        scale: 0.9,
      },
    ],
  },
  {
    id: 'rec_triangle_rotated',
    prompt: 'Find the Triangle (even when tilted)!',
    targetShapeId: 'triangle',
    options: [
      {
        id: 'opt1',
        shapeId: 'square',
        emoji: '⬜',
        color: '#10B981',
        rotationDeg: 45,
        scale: 1,
      },
      {
        id: 'opt2',
        shapeId: 'rectangle',
        emoji: '▭',
        color: '#EC4899',
        rotationDeg: 90,
        scale: 1,
      },
      {
        id: 'opt3',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        rotationDeg: 180,
        scale: 1.2,
      },
    ],
  },
  {
    id: 'rec_square_tilted',
    prompt: 'Which shape is a Square?',
    targetShapeId: 'square',
    options: [
      {
        id: 'opt1',
        shapeId: 'square',
        emoji: '⬜',
        color: '#3B82F6',
        rotationDeg: 15,
        scale: 1,
      },
      {
        id: 'opt2',
        shapeId: 'circle',
        emoji: '⭕',
        color: '#EF4444',
        rotationDeg: 0,
        scale: 1,
      },
      {
        id: 'opt3',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        rotationDeg: 0,
        scale: 1,
      },
    ],
  },
  {
    id: 'rec_rectangle',
    prompt: 'Tap the Rectangle with 2 long sides!',
    targetShapeId: 'rectangle',
    options: [
      {
        id: 'opt1',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        rotationDeg: 0,
        scale: 1,
      },
      {
        id: 'opt2',
        shapeId: 'rectangle',
        emoji: '▭',
        color: '#10B981',
        rotationDeg: 0,
        scale: 1.1,
      },
      {
        id: 'opt3',
        shapeId: 'circle',
        emoji: '⭕',
        color: '#EF4444',
        rotationDeg: 0,
        scale: 1,
      },
    ],
  },
  {
    id: 'rec_star',
    prompt: 'Which shape is a Star with 5 points?',
    targetShapeId: 'star',
    options: [
      {
        id: 'opt1',
        shapeId: 'star',
        emoji: '⭐',
        color: '#F59E0B',
        rotationDeg: 30,
        scale: 1.1,
      },
      {
        id: 'opt2',
        shapeId: 'heart',
        emoji: '❤️',
        color: '#EC4899',
        rotationDeg: 0,
        scale: 1,
      },
      {
        id: 'opt3',
        shapeId: 'diamond',
        emoji: '♦️',
        color: '#8B5CF6',
        rotationDeg: 0,
        scale: 1,
      },
    ],
  },
];

export const SHAPE_MATCHING_PAIRS: readonly ShapeMatchingPair[] = [
  {
    id: 'pair_circle',
    shapeId: 'circle',
    shapeName: 'Circle',
    leftEmoji: '🔴',
    leftColor: '#EF4444',
    rightEmoji: '🔵',
    rightColor: '#3B82F6',
  },
  {
    id: 'pair_square',
    shapeId: 'square',
    shapeName: 'Square',
    leftEmoji: '🟦',
    leftColor: '#3B82F6',
    rightEmoji: '🟨',
    rightColor: '#EAB308',
  },
  {
    id: 'pair_triangle',
    shapeId: 'triangle',
    shapeName: 'Triangle',
    leftEmoji: '🔺',
    leftColor: '#EAB308',
    rightEmoji: '🟢',
    rightColor: '#10B981',
  },
  {
    id: 'pair_star',
    shapeId: 'star',
    shapeName: 'Star',
    leftEmoji: '⭐',
    leftColor: '#F59E0B',
    rightEmoji: '🌟',
    rightColor: '#EC4899',
  },
];

export const SHAPE_SORTING_LEVELS: readonly ShapeSortingLevel[] = [
  {
    id: 'sort_lvl_1',
    levelNumber: 1,
    title: 'Sort 2 Shapes',
    containers: [
      {
        id: 'box_circle',
        targetShapeId: 'circle',
        title: 'Circles ⭕',
        emoji: '⭕',
        color: '#EF4444',
      },
      {
        id: 'box_triangle',
        targetShapeId: 'triangle',
        title: 'Triangles 🔺',
        emoji: '🔺',
        color: '#EAB308',
      },
    ],
    items: [
      {
        id: 'i1',
        shapeId: 'circle',
        emoji: '🔴',
        color: '#EF4444',
        size: 'medium',
      },
      {
        id: 'i2',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        size: 'medium',
      },
      {
        id: 'i3',
        shapeId: 'circle',
        emoji: '🔵',
        color: '#3B82F6',
        size: 'large',
      },
      {
        id: 'i4',
        shapeId: 'triangle',
        emoji: '📐',
        color: '#10B981',
        size: 'small',
      },
    ],
  },
  {
    id: 'sort_lvl_2',
    levelNumber: 2,
    title: 'Sort 3 Shapes',
    containers: [
      {
        id: 'box_circle',
        targetShapeId: 'circle',
        title: 'Circles ⭕',
        emoji: '⭕',
        color: '#EF4444',
      },
      {
        id: 'box_square',
        targetShapeId: 'square',
        title: 'Squares ⬜',
        emoji: '⬜',
        color: '#3B82F6',
      },
      {
        id: 'box_triangle',
        targetShapeId: 'triangle',
        title: 'Triangles 🔺',
        emoji: '🔺',
        color: '#EAB308',
      },
    ],
    items: [
      {
        id: 'i1',
        shapeId: 'square',
        emoji: '🟦',
        color: '#3B82F6',
        size: 'medium',
      },
      {
        id: 'i2',
        shapeId: 'circle',
        emoji: '🔴',
        color: '#EF4444',
        size: 'medium',
      },
      {
        id: 'i3',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        size: 'small',
      },
      {
        id: 'i4',
        shapeId: 'square',
        emoji: '🟨',
        color: '#F59E0B',
        size: 'large',
      },
      {
        id: 'i5',
        shapeId: 'circle',
        emoji: '🟡',
        color: '#EAB308',
        size: 'small',
      },
    ],
  },
  {
    id: 'sort_lvl_3',
    levelNumber: 3,
    title: 'Sort 4 Shapes',
    containers: [
      {
        id: 'box_circle',
        targetShapeId: 'circle',
        title: 'Circles',
        emoji: '⭕',
        color: '#EF4444',
      },
      {
        id: 'box_square',
        targetShapeId: 'square',
        title: 'Squares',
        emoji: '⬜',
        color: '#3B82F6',
      },
      {
        id: 'box_triangle',
        targetShapeId: 'triangle',
        title: 'Triangles',
        emoji: '🔺',
        color: '#EAB308',
      },
      {
        id: 'box_star',
        targetShapeId: 'star',
        title: 'Stars',
        emoji: '⭐',
        color: '#F59E0B',
      },
    ],
    items: [
      {
        id: 'i1',
        shapeId: 'star',
        emoji: '⭐',
        color: '#F59E0B',
        size: 'medium',
      },
      {
        id: 'i2',
        shapeId: 'circle',
        emoji: '🔴',
        color: '#EF4444',
        size: 'large',
      },
      {
        id: 'i3',
        shapeId: 'square',
        emoji: '🟦',
        color: '#3B82F6',
        size: 'medium',
      },
      {
        id: 'i4',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        size: 'small',
      },
      {id: 'i5', shapeId: 'star', emoji: '🌟', color: '#EC4899', size: 'large'},
      {
        id: 'i6',
        shapeId: 'square',
        emoji: '🟩',
        color: '#10B981',
        size: 'small',
      },
    ],
  },
];

export const SHAPE_COMPARISON_ITEMS: readonly ShapeComparisonItem[] = [
  {
    id: 'cmp_1',
    question: 'Which shape has MORE corners?',
    promptAudio: 'Which shape has more corners?',
    shapeA: SHAPES_DATA[2]!, // Triangle (3)
    shapeB: SHAPES_DATA[1]!, // Square (4)
    correctShapeId: 'square',
    explanation: 'A Square has 4 corners, which is more than a Triangle (3)!',
  },
  {
    id: 'cmp_2',
    question: 'Which shape has NO corners and is completely round?',
    promptAudio: 'Which shape has no corners and is completely round?',
    shapeA: SHAPES_DATA[0]!, // Circle (0)
    shapeB: SHAPES_DATA[2]!, // Triangle (3)
    correctShapeId: 'circle',
    explanation: 'A Circle has 0 corners and curves all the way around!',
  },
  {
    id: 'cmp_3',
    question: 'Which shape has FEWER sides?',
    promptAudio: 'Which shape has fewer sides?',
    shapeA: SHAPES_DATA[2]!, // Triangle (3)
    shapeB: SHAPES_DATA[9]!, // Hexagon (6)
    correctShapeId: 'triangle',
    explanation: 'A Triangle has only 3 sides, while a Hexagon has 6 sides!',
  },
  {
    id: 'cmp_4',
    question: 'Which shape has 6 sides like a bee honeycomb?',
    promptAudio: 'Which shape has 6 sides like a honeycomb?',
    shapeA: SHAPES_DATA[9]!, // Hexagon (6)
    shapeB: SHAPES_DATA[10]!, // Pentagon (5)
    correctShapeId: 'hexagon',
    explanation: 'A Hexagon has 6 sides!',
  },
];

export const SHAPES_AROUND_US_ITEMS: readonly ShapeAroundUsItem[] = [
  {
    id: 'around_pizza',
    objectName: 'Yummy Pizza Slice',
    objectEmoji: '🍕',
    correctShapeId: 'triangle',
    correctShapeName: 'Triangle',
    options: [
      {shapeId: 'circle', name: 'Circle', emoji: '⭕'},
      {shapeId: 'triangle', name: 'Triangle', emoji: '🔺'},
      {shapeId: 'square', name: 'Square', emoji: '⬜'},
    ],
  },
  {
    id: 'around_door',
    objectName: 'Tall Room Door',
    objectEmoji: '🚪',
    correctShapeId: 'rectangle',
    correctShapeName: 'Rectangle',
    options: [
      {shapeId: 'rectangle', name: 'Rectangle', emoji: '▭'},
      {shapeId: 'circle', name: 'Circle', emoji: '⭕'},
      {shapeId: 'triangle', name: 'Triangle', emoji: '🔺'},
    ],
  },
  {
    id: 'around_coin',
    objectName: 'Golden Coin',
    objectEmoji: '🪙',
    correctShapeId: 'circle',
    correctShapeName: 'Circle',
    options: [
      {shapeId: 'square', name: 'Square', emoji: '⬜'},
      {shapeId: 'circle', name: 'Circle', emoji: '⭕'},
      {shapeId: 'star', name: 'Star', emoji: '⭐'},
    ],
  },
  {
    id: 'around_kite',
    objectName: 'Flying Kite',
    objectEmoji: '🪁',
    correctShapeId: 'diamond',
    correctShapeName: 'Diamond',
    options: [
      {shapeId: 'diamond', name: 'Diamond', emoji: '♦️'},
      {shapeId: 'circle', name: 'Circle', emoji: '⭕'},
      {shapeId: 'rectangle', name: 'Rectangle', emoji: '▭'},
    ],
  },
  {
    id: 'around_gift',
    objectName: 'Square Gift Box',
    objectEmoji: '🎁',
    correctShapeId: 'square',
    correctShapeName: 'Square',
    options: [
      {shapeId: 'triangle', name: 'Triangle', emoji: '🔺'},
      {shapeId: 'square', name: 'Square', emoji: '⬜'},
      {shapeId: 'oval', name: 'Oval', emoji: '🥚'},
    ],
  },
];

export const SHAPE_COUNT_ITEMS: readonly ShapeCountItem[] = [
  {
    id: 'cnt_1',
    targetShapeId: 'circle',
    targetShapeName: 'Circles',
    targetEmoji: '⭕',
    displayedItems: [
      {id: '1', shapeId: 'circle', emoji: '🔴', color: '#EF4444'},
      {id: '2', shapeId: 'triangle', emoji: '🔺', color: '#EAB308'},
      {id: '3', shapeId: 'circle', emoji: '🔵', color: '#3B82F6'},
      {id: '4', shapeId: 'circle', emoji: '🟡', color: '#F59E0B'},
      {id: '5', shapeId: 'square', emoji: '🟩', color: '#10B981'},
    ],
    correctCount: 3,
    options: [2, 3, 4],
  },
  {
    id: 'cnt_2',
    targetShapeId: 'triangle',
    targetShapeName: 'Triangles',
    targetEmoji: '🔺',
    displayedItems: [
      {id: '1', shapeId: 'triangle', emoji: '🔺', color: '#EAB308'},
      {id: '2', shapeId: 'circle', emoji: '🔴', color: '#EF4444'},
      {id: '3', shapeId: 'triangle', emoji: '📐', color: '#10B981'},
      {id: '4', shapeId: 'square', emoji: '🟦', color: '#3B82F6'},
      {id: '5', shapeId: 'triangle', emoji: '🍕', color: '#F97316'},
      {id: '6', shapeId: 'triangle', emoji: '🔺', color: '#EAB308'},
    ],
    correctCount: 4,
    options: [3, 4, 5],
  },
  {
    id: 'cnt_3',
    targetShapeId: 'square',
    targetShapeName: 'Squares',
    targetEmoji: '⬜',
    displayedItems: [
      {id: '1', shapeId: 'square', emoji: '🟦', color: '#3B82F6'},
      {id: '2', shapeId: 'star', emoji: '⭐', color: '#F59E0B'},
      {id: '3', shapeId: 'square', emoji: '🟨', color: '#EAB308'},
      {id: '4', shapeId: 'circle', emoji: '🔴', color: '#EF4444'},
    ],
    correctCount: 2,
    options: [1, 2, 3],
  },
];

export const SHAPE_PATTERNS: readonly ShapePatternItem[] = [
  {
    id: 'pat_1',
    patternType: 'AB',
    sequence: [
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'triangle', emoji: '🔺'},
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'triangle', emoji: '🔺'},
    ],
    correctShapeId: 'circle',
    correctEmoji: '🔴',
    options: [
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'triangle', emoji: '🔺'},
      {shapeId: 'square', emoji: '🟦'},
    ],
  },
  {
    id: 'pat_2',
    patternType: 'AAB',
    sequence: [
      {shapeId: 'square', emoji: '🟦'},
      {shapeId: 'square', emoji: '🟦'},
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'square', emoji: '🟦'},
      {shapeId: 'square', emoji: '🟦'},
    ],
    correctShapeId: 'circle',
    correctEmoji: '🔴',
    options: [
      {shapeId: 'triangle', emoji: '🔺'},
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'square', emoji: '🟦'},
    ],
  },
  {
    id: 'pat_3',
    patternType: 'ABC',
    sequence: [
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'triangle', emoji: '🔺'},
      {shapeId: 'square', emoji: '🟦'},
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'triangle', emoji: '🔺'},
    ],
    correctShapeId: 'square',
    correctEmoji: '🟦',
    options: [
      {shapeId: 'star', emoji: '⭐'},
      {shapeId: 'circle', emoji: '🔴'},
      {shapeId: 'square', emoji: '🟦'},
    ],
  },
  {
    id: 'pat_4',
    patternType: 'AABB',
    sequence: [
      {shapeId: 'star', emoji: '⭐'},
      {shapeId: 'star', emoji: '⭐'},
      {shapeId: 'heart', emoji: '❤️'},
      {shapeId: 'heart', emoji: '❤️'},
      {shapeId: 'star', emoji: '⭐'},
    ],
    correctShapeId: 'star',
    correctEmoji: '⭐',
    options: [
      {shapeId: 'star', emoji: '⭐'},
      {shapeId: 'heart', emoji: '❤️'},
      {shapeId: 'circle', emoji: '🔴'},
    ],
  },
];

export const SHAPE_PUZZLES: readonly ShapePuzzleItem[] = [
  {
    id: 'puz_odd_1',
    puzzleType: 'odd_one_out',
    prompt: 'Which shape is DIFFERENT from the others?',
    items: [
      {id: '1', shapeId: 'circle', emoji: '🔴', color: '#EF4444'},
      {id: '2', shapeId: 'circle', emoji: '🔵', color: '#3B82F6'},
      {
        id: '3',
        shapeId: 'triangle',
        emoji: '🔺',
        color: '#EAB308',
        isDifferent: true,
      },
      {id: '4', shapeId: 'circle', emoji: '🟢', color: '#10B981'},
    ],
    answerId: '3',
    explanation:
      'The triangle has 3 pointy corners, while all the others are round circles!',
  },
  {
    id: 'puz_odd_2',
    puzzleType: 'odd_one_out',
    prompt: 'Which shape does NOT belong in this group?',
    items: [
      {id: '1', shapeId: 'square', emoji: '🟦', color: '#3B82F6'},
      {id: '2', shapeId: 'rectangle', emoji: '▭', color: '#10B981'},
      {id: '3', shapeId: 'diamond', emoji: '♦️', color: '#8B5CF6'},
      {
        id: '4',
        shapeId: 'circle',
        emoji: '🔴',
        color: '#EF4444',
        isDifferent: true,
      },
    ],
    answerId: '4',
    explanation:
      'The circle has 0 straight sides, while all others have 4 straight sides!',
  },
  {
    id: 'puz_odd_3',
    puzzleType: 'odd_one_out',
    prompt: 'Find the shape with 5 points!',
    items: [
      {id: '1', shapeId: 'circle', emoji: '🔴', color: '#EF4444'},
      {
        id: '2',
        shapeId: 'star',
        emoji: '⭐',
        color: '#F59E0B',
        isDifferent: true,
      },
      {id: '3', shapeId: 'square', emoji: '🟦', color: '#3B82F6'},
      {id: '4', shapeId: 'triangle', emoji: '🔺', color: '#EAB308'},
    ],
    answerId: '2',
    explanation: 'The Star has 5 glowing points!',
  },
];

export const SHAPE_MEMORY_CARDS: readonly {
  readonly id: string;
  readonly shapeId: string;
  readonly emoji: string;
  readonly name: string;
  readonly matchKey: string;
}[] = [
  {
    id: 'c1',
    shapeId: 'circle',
    emoji: '🔴',
    name: 'Circle',
    matchKey: 'circle',
  },
  {
    id: 'c2',
    shapeId: 'circle',
    emoji: '⭕',
    name: 'Circle',
    matchKey: 'circle',
  },
  {
    id: 'c3',
    shapeId: 'square',
    emoji: '🟦',
    name: 'Square',
    matchKey: 'square',
  },
  {
    id: 'c4',
    shapeId: 'square',
    emoji: '⬜',
    name: 'Square',
    matchKey: 'square',
  },
  {
    id: 'c5',
    shapeId: 'triangle',
    emoji: '🔺',
    name: 'Triangle',
    matchKey: 'triangle',
  },
  {
    id: 'c6',
    shapeId: 'triangle',
    emoji: '📐',
    name: 'Triangle',
    matchKey: 'triangle',
  },
  {id: 'c7', shapeId: 'star', emoji: '⭐', name: 'Star', matchKey: 'star'},
  {id: 'c8', shapeId: 'star', emoji: '🌟', name: 'Star', matchKey: 'star'},
];

export const SUBMODULE_QUIZZES: Record<string, readonly ShapeQuizQuestion[]> = {
  learn_shapes: [
    {
      id: 'qz_ls_1',
      question: 'Which shape has 3 sides and 3 corners?',
      promptAudio: 'Which shape has 3 sides and 3 corners?',
      type: 'identify',
      targetEmoji: '🔺',
      options: [
        {id: 'circle', text: 'Circle', emoji: '⭕'},
        {id: 'triangle', text: 'Triangle', emoji: '🔺'},
        {id: 'square', text: 'Square', emoji: '⬜'},
      ],
      answerId: 'triangle',
      explanation: 'A Triangle has 3 sides and 3 corners 🔺!',
    },
    {
      id: 'qz_ls_2',
      question: 'Which shape is completely round with NO corners?',
      promptAudio: 'Which shape is completely round with no corners?',
      type: 'identify',
      targetEmoji: '⭕',
      options: [
        {id: 'square', text: 'Square', emoji: '⬜'},
        {id: 'circle', text: 'Circle', emoji: '⭕'},
        {id: 'rectangle', text: 'Rectangle', emoji: '▭'},
      ],
      answerId: 'circle',
      explanation: 'A Circle is round with 0 corners ⭕!',
    },
    {
      id: 'qz_ls_3',
      question: 'How many equal sides does a Square have?',
      promptAudio: 'How many equal sides does a square have?',
      type: 'count_sides',
      targetEmoji: '⬜',
      options: [
        {id: '3', text: '3 Sides', emoji: '3️⃣'},
        {id: '4', text: '4 Sides', emoji: '4️⃣'},
        {id: '5', text: '5 Sides', emoji: '5️⃣'},
      ],
      answerId: '4',
      explanation: 'A square has 4 equal straight sides ⬜!',
    },
  ],
  challenge: [
    {
      id: 'qz_ch_1',
      question: 'Which everyday object has a Triangle shape?',
      promptAudio: 'Which everyday object has a triangle shape?',
      type: 'match_object',
      options: [
        {id: 'ball', text: 'Soccer Ball', emoji: '⚽'},
        {id: 'pizza', text: 'Pizza Slice', emoji: '🍕'},
        {id: 'door', text: 'Room Door', emoji: '🚪'},
      ],
      answerId: 'pizza',
      explanation: 'A pizza slice is shaped like a triangle 🍕!',
    },
    {
      id: 'qz_ch_2',
      question: 'How many corners does a Hexagon have?',
      promptAudio: 'How many corners does a hexagon have?',
      type: 'count_corners',
      targetEmoji: '⬢',
      options: [
        {id: '4', text: '4 Corners'},
        {id: '5', text: '5 Corners'},
        {id: '6', text: '6 Corners'},
      ],
      answerId: '6',
      explanation: 'A Hexagon has 6 sides and 6 corners ⬢!',
    },
    {
      id: 'qz_ch_3',
      question: 'What comes next in the pattern: 🔴 🔺 🔴 🔺 ?',
      promptAudio:
        'What comes next in the pattern: Circle, Triangle, Circle, Triangle?',
      type: 'pattern',
      options: [
        {id: 'circle', text: 'Circle', emoji: '🔴'},
        {id: 'square', text: 'Square', emoji: '🟦'},
        {id: 'star', text: 'Star', emoji: '⭐'},
      ],
      answerId: 'circle',
      explanation:
        'The pattern repeats: Circle, Triangle, Circle, Triangle, Circle 🔴!',
    },
  ],
};
