import type {Country} from '../entities/Country';

export const CURATED_COUNTRIES: readonly Country[] = [
  {
    code: 'IN',
    name: 'India',
    officialName: 'Republic of India',
    flag: '🇮🇳',
    capital: 'New Delhi',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'Southern Asia',
    languages: ['Hindi', 'English'],
    currencies: ['Indian Rupee (₹)'],
    population: 1408000000,
    funFact:
      'India is famous for peacocks, tigers, yoga, and delicious samosas!',
  },
  {
    code: 'JP',
    name: 'Japan',
    officialName: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'Eastern Asia',
    languages: ['Japanese'],
    currencies: ['Japanese Yen (¥)'],
    population: 125000000,
    funFact:
      'Japan has super-fast bullet trains and beautiful cherry blossom trees!',
  },
  {
    code: 'FR',
    name: 'France',
    officialName: 'French Republic',
    flag: '🇫🇷',
    capital: 'Paris',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Western Europe',
    languages: ['French'],
    currencies: ['Euro (€)'],
    population: 67750000,
    funFact:
      'France is home to the Eiffel Tower and delicious baguettes and croissants!',
  },
  {
    code: 'EG',
    name: 'Egypt',
    officialName: 'Arab Republic of Egypt',
    flag: '🇪🇬',
    capital: 'Cairo',
    continent: 'Africa',
    region: 'Africa',
    subregion: 'Northern Africa',
    languages: ['Arabic'],
    currencies: ['Egyptian Pound (E£)'],
    population: 104000000,
    funFact:
      'Egypt is famous for ancient mummies, the Sphinx, and the Great Pyramids!',
  },
  {
    code: 'US',
    name: 'United States',
    officialName: 'United States of America',
    flag: '🇺🇸',
    capital: 'Washington, D.C.',
    continent: 'North America',
    region: 'Americas',
    subregion: 'North America',
    languages: ['English'],
    currencies: ['US Dollar ($)'],
    population: 331900000,
    funFact:
      'The United States has 50 states and famous places like Disneyland and Grand Canyon!',
  },
  {
    code: 'BR',
    name: 'Brazil',
    officialName: 'Federative Republic of Brazil',
    flag: '🇧🇷',
    capital: 'Brasília',
    continent: 'South America',
    region: 'Americas',
    subregion: 'South America',
    languages: ['Portuguese'],
    currencies: ['Brazilian Real (R$)'],
    population: 214300000,
    funFact:
      'Brazil has the world’s largest rainforest, the Amazon, full of colorful parrots!',
  },
  {
    code: 'AU',
    name: 'Australia',
    officialName: 'Commonwealth of Australia',
    flag: '🇦🇺',
    capital: 'Canberra',
    continent: 'Oceania',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    languages: ['English'],
    currencies: ['Australian Dollar ($)'],
    population: 25690000,
    funFact:
      'Australia is famous for cute kangaroos, koalas, and the Great Barrier Reef!',
  },
  {
    code: 'IT',
    name: 'Italy',
    officialName: 'Italian Republic',
    flag: '🇮🇹',
    capital: 'Rome',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Southern Europe',
    languages: ['Italian'],
    currencies: ['Euro (€)'],
    population: 59000000,
    funFact:
      'Italy is shaped like a boot and gave the world yummy pizza and gelato!',
  },
  {
    code: 'CN',
    name: 'China',
    officialName: "People's Republic of China",
    flag: '🇨🇳',
    capital: 'Beijing',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'Eastern Asia',
    languages: ['Mandarin Chinese'],
    currencies: ['Chinese Yuan (¥)'],
    population: 1412000000,
    funFact: 'China is home to cute giant pandas and the giant Great Wall!',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    officialName: 'United Kingdom of Great Britain and Northern Ireland',
    flag: '🇬🇧',
    capital: 'London',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Northern Europe',
    languages: ['English'],
    currencies: ['British Pound (£)'],
    population: 67300000,
    funFact: 'London has red double-decker buses and Big Ben clock tower!',
  },
  {
    code: 'CA',
    name: 'Canada',
    officialName: 'Canada',
    flag: '🇨🇦',
    capital: 'Ottawa',
    continent: 'North America',
    region: 'Americas',
    subregion: 'North America',
    languages: ['English', 'French'],
    currencies: ['Canadian Dollar ($)'],
    population: 38250000,
    funFact: 'Canada produces sweet maple syrup and has beautiful polar bears!',
  },
  {
    code: 'KR',
    name: 'South Korea',
    officialName: 'Republic of Korea',
    flag: '🇰🇷',
    capital: 'Seoul',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'Eastern Asia',
    languages: ['Korean'],
    currencies: ['South Korean Won (₩)'],
    population: 51740000,
    funFact:
      'South Korea is famous for K-pop music, Taekwondo, and robot technology!',
  },
  {
    code: 'MX',
    name: 'Mexico',
    officialName: 'United Mexican States',
    flag: '🇲🇽',
    capital: 'Mexico City',
    continent: 'North America',
    region: 'Americas',
    subregion: 'North America',
    languages: ['Spanish'],
    currencies: ['Mexican Peso ($)'],
    population: 126700000,
    funFact:
      'Mexico is famous for colorful piñatas, ancient Maya pyramids, and tacos!',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    officialName: 'Republic of South Africa',
    flag: '🇿🇦',
    capital: 'Pretoria',
    continent: 'Africa',
    region: 'Africa',
    subregion: 'Southern Africa',
    languages: ['English', 'Zulu', 'Afrikaans'],
    currencies: ['South African Rand (R)'],
    population: 59300000,
    funFact:
      'South Africa has penguins swimming on sandy beaches near Cape Town!',
  },
  {
    code: 'DE',
    name: 'Germany',
    officialName: 'Federal Republic of Germany',
    flag: '🇩🇪',
    capital: 'Berlin',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Western Europe',
    languages: ['German'],
    currencies: ['Euro (€)'],
    population: 83200000,
    funFact:
      'Germany has fairy-tale castles that inspired Disney Sleeping Beauty Castle!',
  },
  {
    code: 'ES',
    name: 'Spain',
    officialName: 'Kingdom of Spain',
    flag: '🇪🇸',
    capital: 'Madrid',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Southern Europe',
    languages: ['Spanish'],
    currencies: ['Euro (€)'],
    population: 47400000,
    funFact:
      'Spain is famous for flamenco dancing, sunny beaches, and paella rice!',
  },
  {
    code: 'AR',
    name: 'Argentina',
    officialName: 'Argentine Republic',
    flag: '🇦🇷',
    capital: 'Buenos Aires',
    continent: 'South America',
    region: 'Americas',
    subregion: 'South America',
    languages: ['Spanish'],
    currencies: ['Argentine Peso ($)'],
    population: 45800000,
    funFact:
      'Argentina is famous for soccer legend Messi and high Andes mountains!',
  },
  {
    code: 'PE',
    name: 'Peru',
    officialName: 'Republic of Peru',
    flag: '🇵🇪',
    capital: 'Lima',
    continent: 'South America',
    region: 'Americas',
    subregion: 'South America',
    languages: ['Spanish'],
    currencies: ['Peruvian Sol (S/)'],
    population: 33700000,
    funFact:
      'Peru is famous for fluffy llamas and the ancient mountain city of Machu Picchu!',
  },
  {
    code: 'TH',
    name: 'Thailand',
    officialName: 'Kingdom of Thailand',
    flag: '🇹🇭',
    capital: 'Bangkok',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    languages: ['Thai'],
    currencies: ['Thai Baht (฿)'],
    population: 71600000,
    funFact:
      'Thailand is known as the "Land of Smiles" and has friendly Asian elephants!',
  },
  {
    code: 'GR',
    name: 'Greece',
    officialName: 'Hellenic Republic',
    flag: '🇬🇷',
    capital: 'Athens',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Southern Europe',
    languages: ['Greek'],
    currencies: ['Euro (€)'],
    population: 10640000,
    funFact:
      'Greece is where the ancient Olympic Games were born over 2,700 years ago!',
  },
  {
    code: 'KE',
    name: 'Kenya',
    officialName: 'Republic of Kenya',
    flag: '🇰🇪',
    capital: 'Nairobi',
    continent: 'Africa',
    region: 'Africa',
    subregion: 'Eastern Africa',
    languages: ['Swahili', 'English'],
    currencies: ['Kenyan Shilling (KSh)'],
    population: 53000000,
    funFact:
      'Kenya is world famous for marathon runners and lions in national parks!',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    officialName: 'New Zealand',
    flag: '🇳🇿',
    capital: 'Wellington',
    continent: 'Oceania',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    languages: ['English', 'Māori'],
    currencies: ['New Zealand Dollar ($)'],
    population: 5120000,
    funFact:
      'New Zealand is home to the flightless Kiwi bird and sheep on green hills!',
  },
  {
    code: 'RU',
    name: 'Russia',
    officialName: 'Russian Federation',
    flag: '🇷🇺',
    capital: 'Moscow',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Eastern Europe',
    languages: ['Russian'],
    currencies: ['Russian Ruble (₽)'],
    population: 143400000,
    funFact:
      'Russia is the largest country by land area and spans 11 time zones!',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    officialName: 'Kingdom of Saudi Arabia',
    flag: '🇸🇦',
    capital: 'Riyadh',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'Western Asia',
    languages: ['Arabic'],
    currencies: ['Saudi Riyal (SR)'],
    population: 35900000,
    funFact: 'Saudi Arabia has vast desert sand dunes and friendly camels!',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    officialName: 'Swiss Confederation',
    flag: '🇨🇭',
    capital: 'Bern',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Western Europe',
    languages: ['German', 'French', 'Italian'],
    currencies: ['Swiss Franc (CHF)'],
    population: 8700000,
    funFact:
      'Switzerland is famous for delicious Swiss milk chocolate and high snowy Alps!',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    officialName: 'Kingdom of the Netherlands',
    flag: '🇳🇱',
    capital: 'Amsterdam',
    continent: 'Europe',
    region: 'Europe',
    subregion: 'Western Europe',
    languages: ['Dutch'],
    currencies: ['Euro (€)'],
    population: 17500000,
    funFact:
      'The Netherlands is famous for colorful tulip flower fields and historic windmills!',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    officialName: 'Federal Republic of Nigeria',
    flag: '🇳🇬',
    capital: 'Abuja',
    continent: 'Africa',
    region: 'Africa',
    subregion: 'Western Africa',
    languages: ['English'],
    currencies: ['Nigerian Naira (₦)'],
    population: 213400000,
    funFact:
      'Nigeria is the most populous country in Africa with rich music and movies!',
  },
  {
    code: 'SG',
    name: 'Singapore',
    officialName: 'Republic of Singapore',
    flag: '🇸🇬',
    capital: 'Singapore',
    continent: 'Asia',
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    languages: ['English', 'Malay', 'Mandarin', 'Tamil'],
    currencies: ['Singapore Dollar ($)'],
    population: 5450000,
    funFact:
      'Singapore has a giant supertree garden and a fountain waterfall inside its airport!',
  },
];
