import type {
  ColorItem,
  ColorMatchingItem,
  ColorMixingRecipe,
  ColoringPage,
  CreativeChallengeItem,
  DrawingQuizQuestion,
  DrawingSubModuleConfig,
  GuidedDrawingLesson,
  ShapeItem,
  SimpleObjectDrawingItem,
  TracingPath,
} from '../entities/drawingEntities';

export const DRAWING_SUB_MODULES: readonly DrawingSubModuleConfig[] = [
  {
    id: 'colors',
    titleKey: 'drawing.submodules.colors',
    subtitleKey: 'drawing.submodules.colorsSub',
    emoji: '🎨',
    accentColor: '#EF4444',
    bgLightColor: '#FEF2F2',
    orderIndex: 1,
    routeName: 'Colors',
  },
  {
    id: 'color_match',
    titleKey: 'drawing.submodules.colorMatch',
    subtitleKey: 'drawing.submodules.colorMatchSub',
    emoji: '🌈',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    orderIndex: 2,
    routeName: 'ColorMatch',
  },
  {
    id: 'color_mix',
    titleKey: 'drawing.submodules.colorMix',
    subtitleKey: 'drawing.submodules.colorMixSub',
    emoji: '🧪',
    accentColor: '#8B5CF6',
    bgLightColor: '#F5F3FF',
    orderIndex: 3,
    routeName: 'ColorMix',
  },
  {
    id: 'coloring',
    titleKey: 'drawing.submodules.coloring',
    subtitleKey: 'drawing.submodules.coloringSub',
    emoji: '🖍️',
    accentColor: '#EC4899',
    bgLightColor: '#FDF2F8',
    orderIndex: 4,
    routeName: 'Coloring',
  },
  {
    id: 'trace',
    titleKey: 'drawing.submodules.trace',
    subtitleKey: 'drawing.submodules.traceSub',
    emoji: '✏️',
    accentColor: '#10B981',
    bgLightColor: '#ECFDF5',
    orderIndex: 5,
    routeName: 'Trace',
  },
  {
    id: 'shapes',
    titleKey: 'drawing.submodules.shapes',
    subtitleKey: 'drawing.submodules.shapesSub',
    emoji: '🔷',
    accentColor: '#F59E0B',
    bgLightColor: '#FFFBEB',
    orderIndex: 6,
    routeName: 'Shapes',
  },
  {
    id: 'draw_objects',
    titleKey: 'drawing.submodules.drawObjects',
    subtitleKey: 'drawing.submodules.drawObjectsSub',
    emoji: '🐾',
    accentColor: '#14B8A6',
    bgLightColor: '#F0FDFA',
    orderIndex: 7,
    routeName: 'ObjectDrawing',
  },
  {
    id: 'guided_drawing',
    titleKey: 'drawing.submodules.guidedDrawing',
    subtitleKey: 'drawing.submodules.guidedDrawingSub',
    emoji: '🧑‍🎨',
    accentColor: '#6366F1',
    bgLightColor: '#EEF2FF',
    orderIndex: 8,
    routeName: 'GuidedDrawing',
  },
  {
    id: 'free_drawing',
    titleKey: 'drawing.submodules.freeDrawing',
    subtitleKey: 'drawing.submodules.freeDrawingSub',
    emoji: '🖼️',
    accentColor: '#0EA5E9',
    bgLightColor: '#F0F9FF',
    orderIndex: 9,
    routeName: 'FreeDrawing',
  },
  {
    id: 'creative_challenge',
    titleKey: 'drawing.submodules.creativeChallenge',
    subtitleKey: 'drawing.submodules.creativeChallengeSub',
    emoji: '🏆',
    accentColor: '#EA580C',
    bgLightColor: '#FFF7ED',
    orderIndex: 10,
    routeName: 'CreativeChallenge',
  },
];

export const COLORS_DATA: readonly ColorItem[] = [
  {
    id: 'red',
    name: 'Red',
    hex: '#EF4444',
    lightHex: '#FEE2E2',
    darkHex: '#B91C1C',
    isPrimary: true,
    objects: [
      {
        id: 'apple',
        name: 'Apple',
        emoji: '🍎',
        description: 'A sweet crunchy red apple',
      },
      {
        id: 'heart',
        name: 'Heart',
        emoji: '❤️',
        description: 'A warm red heart full of love',
      },
      {
        id: 'car',
        name: 'Red Car',
        emoji: '🚗',
        description: 'A speedy red race car',
      },
      {
        id: 'strawberry',
        name: 'Strawberry',
        emoji: '🍓',
        description: 'A delicious juicy strawberry',
      },
    ],
    audioPronunciation:
      'Red. R-E-D, Red. Red is bright and warm like a juicy apple!',
    funFact: 'Red is the first primary color!',
    soundHint: 'R - E - D',
  },
  {
    id: 'blue',
    name: 'Blue',
    hex: '#3B82F6',
    lightHex: '#DBEAFE',
    darkHex: '#1D4ED8',
    isPrimary: true,
    objects: [
      {
        id: 'ocean',
        name: 'Ocean',
        emoji: '🌊',
        description: 'Deep blue sparkling ocean waves',
      },
      {
        id: 'whale',
        name: 'Blue Whale',
        emoji: '🐋',
        description: 'The giant gentle blue whale',
      },
      {
        id: 'blueberries',
        name: 'Blueberries',
        emoji: '🫐',
        description: 'Sweet little blue berries',
      },
      {
        id: 'sky',
        name: 'Clear Sky',
        emoji: '🌌',
        description: 'The vast beautiful blue sky',
      },
    ],
    audioPronunciation:
      'Blue. B-L-U-E, Blue. Blue is cool and calm like the deep ocean!',
    funFact: 'Blue is a primary color found in the sky and sea.',
    soundHint: 'B - L - U - E',
  },
  {
    id: 'yellow',
    name: 'Yellow',
    hex: '#EAB308',
    lightHex: '#FEF9C3',
    darkHex: '#A16207',
    isPrimary: true,
    objects: [
      {
        id: 'sun',
        name: 'Sun',
        emoji: '☀️',
        description: 'The bright glowing morning sun',
      },
      {
        id: 'banana',
        name: 'Banana',
        emoji: '🍌',
        description: 'A sweet yellow ripe banana',
      },
      {
        id: 'lemon',
        name: 'Lemon',
        emoji: '🍋',
        description: 'A tangy sunny yellow lemon',
      },
      {
        id: 'sunflower',
        name: 'Sunflower',
        emoji: '🌻',
        description: 'A tall happy yellow sunflower',
      },
    ],
    audioPronunciation:
      'Yellow. Y-E-L-L-O-W, Yellow. Yellow is cheerful and bright like the sun!',
    funFact: 'Yellow is the third primary color that brings sunshine energy.',
    soundHint: 'Y - E - L - L - O - W',
  },
  {
    id: 'green',
    name: 'Green',
    hex: '#10B981',
    lightHex: '#D1FAE5',
    darkHex: '#047857',
    isPrimary: false,
    objects: [
      {
        id: 'tree',
        name: 'Tree',
        emoji: '🌳',
        description: 'A leafy green forest tree',
      },
      {
        id: 'frog',
        name: 'Frog',
        emoji: '🐸',
        description: 'A cute hopping green frog',
      },
      {
        id: 'leaf',
        name: 'Leaf',
        emoji: '🍃',
        description: 'A fresh green spring leaf',
      },
      {
        id: 'broccoli',
        name: 'Broccoli',
        emoji: '🥦',
        description: 'Healthy green super broccoli',
      },
    ],
    audioPronunciation:
      'Green. G-R-E-E-N, Green. Made by mixing Blue and Yellow!',
    funFact: 'Green is made by mixing Blue and Yellow!',
    soundHint: 'G - R - E - E - N',
  },
  {
    id: 'orange',
    name: 'Orange',
    hex: '#F97316',
    lightHex: '#FFEDD5',
    darkHex: '#C2410C',
    isPrimary: false,
    objects: [
      {
        id: 'orange_fruit',
        name: 'Orange',
        emoji: '🍊',
        description: 'A juicy round sweet orange',
      },
      {
        id: 'carrot',
        name: 'Carrot',
        emoji: '🥕',
        description: 'A crunchy orange garden carrot',
      },
      {
        id: 'fox',
        name: 'Fox',
        emoji: '🦊',
        description: 'A clever friendly orange fox',
      },
      {
        id: 'pumpkin',
        name: 'Pumpkin',
        emoji: '🎃',
        description: 'A big round orange pumpkin',
      },
    ],
    audioPronunciation:
      'Orange. O-R-A-N-G-E, Orange. Made by mixing Red and Yellow!',
    funFact: 'Orange is made by mixing Red and Yellow!',
    soundHint: 'O - R - A - N - G - E',
  },
  {
    id: 'purple',
    name: 'Purple',
    hex: '#8B5CF6',
    lightHex: '#EDE9FE',
    darkHex: '#6D28D9',
    isPrimary: false,
    objects: [
      {
        id: 'grapes',
        name: 'Grapes',
        emoji: '🍇',
        description: 'Sweet purple bunch of grapes',
      },
      {
        id: 'eggplant',
        name: 'Eggplant',
        emoji: '🍆',
        description: 'A glossy purple eggplant',
      },
      {
        id: 'crystal',
        name: 'Crystal',
        emoji: '🔮',
        description: 'A magical shiny purple crystal',
      },
      {
        id: 'butterfly',
        name: 'Butterfly',
        emoji: '🦋',
        description: 'A fluttery purple butterfly',
      },
    ],
    audioPronunciation:
      'Purple. P-U-R-P-L-E, Purple. Made by mixing Red and Blue!',
    funFact: 'Purple was once the color of royal kings and queens!',
    soundHint: 'P - U - R - P - L - E',
  },
  {
    id: 'pink',
    name: 'Pink',
    hex: '#EC4899',
    lightHex: '#FCE7F3',
    darkHex: '#BE185D',
    isPrimary: false,
    objects: [
      {
        id: 'flamingo',
        name: 'Flamingo',
        emoji: '🦩',
        description: 'A graceful tall pink flamingo',
      },
      {
        id: 'flower',
        name: 'Cherry Blossom',
        emoji: '🌸',
        description: 'A delicate pretty pink flower',
      },
      {
        id: 'donut',
        name: 'Frosted Donut',
        emoji: '🍩',
        description: 'A sweet donut with pink frosting',
      },
      {
        id: 'heart_pink',
        name: 'Pink Ribbon',
        emoji: '🎀',
        description: 'A lovely soft pink ribbon',
      },
    ],
    audioPronunciation: 'Pink. P-I-N-K, Pink. Made by mixing Red with White!',
    funFact: 'Pink is created when you add white to red.',
    soundHint: 'P - I - N - K',
  },
  {
    id: 'brown',
    name: 'Brown',
    hex: '#78350F',
    lightHex: '#FEF3C7',
    darkHex: '#451A03',
    isPrimary: false,
    objects: [
      {
        id: 'bear',
        name: 'Bear',
        emoji: '🐻',
        description: 'A fuzzy brown teddy bear',
      },
      {
        id: 'chocolate',
        name: 'Chocolate',
        emoji: '🍫',
        description: 'Delicious brown chocolate bar',
      },
      {
        id: 'coconut',
        name: 'Coconut',
        emoji: '🥥',
        description: 'A tropical brown coconut',
      },
      {
        id: 'wood',
        name: 'Wood Log',
        emoji: '🪵',
        description: 'Sturdy brown tree log',
      },
    ],
    audioPronunciation:
      'Brown. B-R-O-W-N, Brown. The earthy color of trees and chocolate!',
    funFact: 'Brown is the color of rich soil and wooden tree trunks.',
    soundHint: 'B - R - O - W - N',
  },
  {
    id: 'black',
    name: 'Black',
    hex: '#18181B',
    lightHex: '#F4F4F5',
    darkHex: '#09090B',
    isPrimary: false,
    objects: [
      {
        id: 'cat_black',
        name: 'Black Cat',
        emoji: '🐈‍⬛',
        description: 'A sleek friendly black cat',
      },
      {
        id: 'night',
        name: 'Night Sky',
        emoji: '🌃',
        description: 'The dark calm starry night',
      },
      {
        id: 'eight_ball',
        name: 'Magic 8 Ball',
        emoji: '🎱',
        description: 'A shiny black game ball',
      },
      {
        id: 'tire',
        name: 'Car Tire',
        emoji: '🛞',
        description: 'A sturdy black rubber tire',
      },
    ],
    audioPronunciation:
      'Black. B-L-A-C-K, Black. The darkest shade, like the midnight sky!',
    funFact: 'Black absorbs all colors of light.',
    soundHint: 'B - L - A - C - K',
  },
  {
    id: 'white',
    name: 'White',
    hex: '#F8FAFC',
    lightHex: '#FFFFFF',
    darkHex: '#CBD5E1',
    isPrimary: false,
    objects: [
      {
        id: 'snowman',
        name: 'Snowman',
        emoji: '⛄',
        description: 'A jolly white winter snowman',
      },
      {
        id: 'cloud',
        name: 'Cloud',
        emoji: '☁️',
        description: 'A fluffy white summer cloud',
      },
      {
        id: 'egg',
        name: 'Egg',
        emoji: '🥚',
        description: 'A smooth white morning egg',
      },
      {
        id: 'sheep',
        name: 'Sheep',
        emoji: '🐑',
        description: 'A soft fluffy white sheep',
      },
    ],
    audioPronunciation:
      'White. W-H-I-T-E, White. Pure and bright like fluffy clouds and snow!',
    funFact: 'White reflects all colors of light back to our eyes.',
    soundHint: 'W - H - I - T - E',
  },
  {
    id: 'gray',
    name: 'Gray',
    hex: '#64748B',
    lightHex: '#F1F5F9',
    darkHex: '#334155',
    isPrimary: false,
    objects: [
      {
        id: 'elephant',
        name: 'Elephant',
        emoji: '🐘',
        description: 'A mighty friendly gray elephant',
      },
      {
        id: 'mouse',
        name: 'Little Mouse',
        emoji: '🐭',
        description: 'A quick playful gray mouse',
      },
      {
        id: 'koala',
        name: 'Koala',
        emoji: '🐨',
        description: 'A cuddly gray koala bear',
      },
      {
        id: 'rock',
        name: 'River Rock',
        emoji: '🪨',
        description: 'A smooth gray river stone',
      },
    ],
    audioPronunciation:
      'Gray. G-R-A-Y, Gray. Made by mixing Black and White together!',
    funFact: 'Gray is the peaceful middle between black and white.',
    soundHint: 'G - R - A - Y',
  },
];

export const COLOR_MATCHING_ITEMS: readonly ColorMatchingItem[] = [
  {
    id: 'match_apple',
    prompt: 'What color is a ripe Apple?',
    targetColorId: 'red',
    targetHex: '#EF4444',
    objectName: 'Apple',
    objectEmoji: '🍎',
    options: [
      {colorId: 'blue', hex: '#3B82F6', name: 'Blue'},
      {colorId: 'red', hex: '#EF4444', name: 'Red'},
      {colorId: 'purple', hex: '#8B5CF6', name: 'Purple'},
    ],
  },
  {
    id: 'match_banana',
    prompt: 'What color is a tasty Banana?',
    targetColorId: 'yellow',
    targetHex: '#EAB308',
    objectName: 'Banana',
    objectEmoji: '🍌',
    options: [
      {colorId: 'yellow', hex: '#EAB308', name: 'Yellow'},
      {colorId: 'green', hex: '#10B981', name: 'Green'},
      {colorId: 'pink', hex: '#EC4899', name: 'Pink'},
    ],
  },
  {
    id: 'match_leaf',
    prompt: 'What color is a tree Leaf?',
    targetColorId: 'green',
    targetHex: '#10B981',
    objectName: 'Leaf',
    objectEmoji: '🍃',
    options: [
      {colorId: 'red', hex: '#EF4444', name: 'Red'},
      {colorId: 'green', hex: '#10B981', name: 'Green'},
      {colorId: 'orange', hex: '#F97316', name: 'Orange'},
    ],
  },
  {
    id: 'match_ocean',
    prompt: 'What color is the deep Ocean?',
    targetColorId: 'blue',
    targetHex: '#3B82F6',
    objectName: 'Ocean',
    objectEmoji: '🌊',
    options: [
      {colorId: 'brown', hex: '#78350F', name: 'Brown'},
      {colorId: 'blue', hex: '#3B82F6', name: 'Blue'},
      {colorId: 'yellow', hex: '#EAB308', name: 'Yellow'},
    ],
  },
  {
    id: 'match_carrot',
    prompt: 'What color is a crunchy Carrot?',
    targetColorId: 'orange',
    targetHex: '#F97316',
    objectName: 'Carrot',
    objectEmoji: '🥕',
    options: [
      {colorId: 'orange', hex: '#F97316', name: 'Orange'},
      {colorId: 'purple', hex: '#8B5CF6', name: 'Purple'},
      {colorId: 'blue', hex: '#3B82F6', name: 'Blue'},
    ],
  },
  {
    id: 'match_grapes',
    prompt: 'What color are sweet Grapes?',
    targetColorId: 'purple',
    targetHex: '#8B5CF6',
    objectName: 'Grapes',
    objectEmoji: '🍇',
    options: [
      {colorId: 'yellow', hex: '#EAB308', name: 'Yellow'},
      {colorId: 'purple', hex: '#8B5CF6', name: 'Purple'},
      {colorId: 'red', hex: '#EF4444', name: 'Red'},
    ],
  },
];

export const COLOR_MIXING_RECIPES: readonly ColorMixingRecipe[] = [
  {
    id: 'mix_orange',
    color1: {name: 'Red', hex: '#EF4444', emoji: '🔴'},
    color2: {name: 'Yellow', hex: '#EAB308', emoji: '🟡'},
    resultColor: {
      name: 'Orange',
      hex: '#F97316',
      emoji: '🟠',
      description: 'Red and Yellow blend into bright vibrant Orange!',
    },
    quizOptions: [
      {name: 'Green', hex: '#10B981', emoji: '🟢'},
      {name: 'Orange', hex: '#F97316', emoji: '🟠'},
      {name: 'Purple', hex: '#8B5CF6', emoji: '🟣'},
    ],
  },
  {
    id: 'mix_green',
    color1: {name: 'Blue', hex: '#3B82F6', emoji: '🔵'},
    color2: {name: 'Yellow', hex: '#EAB308', emoji: '🟡'},
    resultColor: {
      name: 'Green',
      hex: '#10B981',
      emoji: '🟢',
      description: 'Blue and Yellow swirl into fresh leafy Green!',
    },
    quizOptions: [
      {name: 'Orange', hex: '#F97316', emoji: '🟠'},
      {name: 'Green', hex: '#10B981', emoji: '🟢'},
      {name: 'Brown', hex: '#78350F', emoji: '🟤'},
    ],
  },
  {
    id: 'mix_purple',
    color1: {name: 'Red', hex: '#EF4444', emoji: '🔴'},
    color2: {name: 'Blue', hex: '#3B82F6', emoji: '🔵'},
    resultColor: {
      name: 'Purple',
      hex: '#8B5CF6',
      emoji: '🟣',
      description: 'Red and Blue mix into magical royal Purple!',
    },
    quizOptions: [
      {name: 'Purple', hex: '#8B5CF6', emoji: '🟣'},
      {name: 'Green', hex: '#10B981', emoji: '🟢'},
      {name: 'Pink', hex: '#EC4899', emoji: '🩷'},
    ],
  },
  {
    id: 'mix_pink',
    color1: {name: 'Red', hex: '#EF4444', emoji: '🔴'},
    color2: {name: 'White', hex: '#FFFFFF', emoji: '⚪'},
    resultColor: {
      name: 'Pink',
      hex: '#EC4899',
      emoji: '🩷',
      description: 'Adding White softens Red into lovely Pink!',
    },
    quizOptions: [
      {name: 'Orange', hex: '#F97316', emoji: '🟠'},
      {name: 'Pink', hex: '#EC4899', emoji: '🩷'},
      {name: 'Gray', hex: '#64748B', emoji: '🩶'},
    ],
  },
  {
    id: 'mix_gray',
    color1: {name: 'Black', hex: '#18181B', emoji: '⚫'},
    color2: {name: 'White', hex: '#FFFFFF', emoji: '⚪'},
    resultColor: {
      name: 'Gray',
      hex: '#64748B',
      emoji: '🩶',
      description: 'Black and White balance into smooth Elephant Gray!',
    },
    quizOptions: [
      {name: 'Brown', hex: '#78350F', emoji: '🟤'},
      {name: 'Gray', hex: '#64748B', emoji: '🩶'},
      {name: 'Blue', hex: '#3B82F6', emoji: '🔵'},
    ],
  },
];

export const COLORING_PAGES: readonly ColoringPage[] = [
  {
    id: 'apple',
    title: 'Color the Apple',
    category: 'fruits',
    difficulty: 1,
    emoji: '🍎',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'body',
        name: 'Apple Body',
        suggestedColorHex: '#EF4444',
        x: 40,
        y: 60,
        width: 160,
        height: 150,
        borderRadius: 80,
        shapeType: 'ellipse',
      },
      {
        id: 'stem',
        name: 'Stem',
        suggestedColorHex: '#78350F',
        x: 114,
        y: 20,
        width: 12,
        height: 45,
        borderRadius: 6,
        shapeType: 'rect',
      },
      {
        id: 'leaf',
        name: 'Leaf',
        suggestedColorHex: '#10B981',
        x: 125,
        y: 25,
        width: 50,
        height: 30,
        borderRadius: 15,
        shapeType: 'ellipse',
      },
    ],
  },
  {
    id: 'sun',
    title: 'Happy Sunshine',
    category: 'nature',
    difficulty: 1,
    emoji: '☀️',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'center',
        name: 'Sun Face',
        suggestedColorHex: '#EAB308',
        x: 60,
        y: 60,
        width: 120,
        height: 120,
        borderRadius: 60,
        shapeType: 'circle',
      },
      {
        id: 'top_ray',
        name: 'Top Ray',
        suggestedColorHex: '#F97316',
        x: 108,
        y: 10,
        width: 24,
        height: 40,
        borderRadius: 12,
        shapeType: 'rect',
      },
      {
        id: 'bottom_ray',
        name: 'Bottom Ray',
        suggestedColorHex: '#F97316',
        x: 108,
        y: 190,
        width: 24,
        height: 40,
        borderRadius: 12,
        shapeType: 'rect',
      },
      {
        id: 'left_ray',
        name: 'Left Ray',
        suggestedColorHex: '#F97316',
        x: 10,
        y: 108,
        width: 40,
        height: 24,
        borderRadius: 12,
        shapeType: 'rect',
      },
      {
        id: 'right_ray',
        name: 'Right Ray',
        suggestedColorHex: '#F97316',
        x: 190,
        y: 108,
        width: 40,
        height: 24,
        borderRadius: 12,
        shapeType: 'rect',
      },
    ],
  },
  {
    id: 'flower',
    title: 'Garden Flower',
    category: 'nature',
    difficulty: 2,
    emoji: '🌸',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'stem',
        name: 'Stem',
        suggestedColorHex: '#10B981',
        x: 114,
        y: 120,
        width: 12,
        height: 100,
        borderRadius: 6,
        shapeType: 'rect',
      },
      {
        id: 'leaf_left',
        name: 'Left Leaf',
        suggestedColorHex: '#10B981',
        x: 70,
        y: 150,
        width: 45,
        height: 25,
        borderRadius: 14,
        shapeType: 'ellipse',
      },
      {
        id: 'petal_top',
        name: 'Top Petal',
        suggestedColorHex: '#EC4899',
        x: 95,
        y: 20,
        width: 50,
        height: 50,
        borderRadius: 25,
        shapeType: 'circle',
      },
      {
        id: 'petal_bottom',
        name: 'Bottom Petal',
        suggestedColorHex: '#EC4899',
        x: 95,
        y: 95,
        width: 50,
        height: 50,
        borderRadius: 25,
        shapeType: 'circle',
      },
      {
        id: 'petal_left',
        name: 'Left Petal',
        suggestedColorHex: '#EC4899',
        x: 58,
        y: 58,
        width: 50,
        height: 50,
        borderRadius: 25,
        shapeType: 'circle',
      },
      {
        id: 'petal_right',
        name: 'Right Petal',
        suggestedColorHex: '#EC4899',
        x: 132,
        y: 58,
        width: 50,
        height: 50,
        borderRadius: 25,
        shapeType: 'circle',
      },
      {
        id: 'center',
        name: 'Flower Center',
        suggestedColorHex: '#EAB308',
        x: 95,
        y: 58,
        width: 50,
        height: 50,
        borderRadius: 25,
        shapeType: 'circle',
      },
    ],
  },
  {
    id: 'tree',
    title: 'Green Forest Tree',
    category: 'nature',
    difficulty: 2,
    emoji: '🌳',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'trunk',
        name: 'Tree Trunk',
        suggestedColorHex: '#78350F',
        x: 100,
        y: 130,
        width: 40,
        height: 90,
        borderRadius: 10,
        shapeType: 'rect',
      },
      {
        id: 'canopy_bottom',
        name: 'Leaves Bottom',
        suggestedColorHex: '#10B981',
        x: 35,
        y: 80,
        width: 170,
        height: 80,
        borderRadius: 40,
        shapeType: 'ellipse',
      },
      {
        id: 'canopy_top',
        name: 'Leaves Top',
        suggestedColorHex: '#34D399',
        x: 55,
        y: 25,
        width: 130,
        height: 85,
        borderRadius: 45,
        shapeType: 'ellipse',
      },
    ],
  },
  {
    id: 'house',
    title: 'Cozy House',
    category: 'objects',
    difficulty: 3,
    emoji: '🏠',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'wall',
        name: 'House Wall',
        suggestedColorHex: '#3B82F6',
        x: 45,
        y: 95,
        width: 150,
        height: 120,
        borderRadius: 16,
        shapeType: 'rect',
      },
      {
        id: 'roof',
        name: 'Roof',
        suggestedColorHex: '#EF4444',
        x: 30,
        y: 35,
        width: 180,
        height: 65,
        borderRadius: 20,
        shapeType: 'triangle',
      },
      {
        id: 'door',
        name: 'Door',
        suggestedColorHex: '#78350F',
        x: 100,
        y: 140,
        width: 40,
        height: 75,
        borderRadius: 8,
        shapeType: 'rect',
      },
      {
        id: 'window_left',
        name: 'Left Window',
        suggestedColorHex: '#EAB308',
        x: 58,
        y: 120,
        width: 32,
        height: 32,
        borderRadius: 8,
        shapeType: 'rect',
      },
      {
        id: 'window_right',
        name: 'Right Window',
        suggestedColorHex: '#EAB308',
        x: 150,
        y: 120,
        width: 32,
        height: 32,
        borderRadius: 8,
        shapeType: 'rect',
      },
    ],
  },
  {
    id: 'car',
    title: 'Speedy Car',
    category: 'vehicles',
    difficulty: 3,
    emoji: '🚗',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'body_bottom',
        name: 'Car Lower Body',
        suggestedColorHex: '#EF4444',
        x: 25,
        y: 110,
        width: 190,
        height: 55,
        borderRadius: 18,
        shapeType: 'rect',
      },
      {
        id: 'body_top',
        name: 'Cabin Roof',
        suggestedColorHex: '#DC2626',
        x: 65,
        y: 65,
        width: 110,
        height: 50,
        borderRadius: 16,
        shapeType: 'rect',
      },
      {
        id: 'window_left',
        name: 'Front Window',
        suggestedColorHex: '#93C5FD',
        x: 75,
        y: 75,
        width: 42,
        height: 30,
        borderRadius: 6,
        shapeType: 'rect',
      },
      {
        id: 'window_right',
        name: 'Rear Window',
        suggestedColorHex: '#93C5FD',
        x: 123,
        y: 75,
        width: 42,
        height: 30,
        borderRadius: 6,
        shapeType: 'rect',
      },
      {
        id: 'wheel_left',
        name: 'Front Wheel',
        suggestedColorHex: '#18181B',
        x: 50,
        y: 150,
        width: 44,
        height: 44,
        borderRadius: 22,
        shapeType: 'circle',
      },
      {
        id: 'wheel_right',
        name: 'Rear Wheel',
        suggestedColorHex: '#18181B',
        x: 146,
        y: 150,
        width: 44,
        height: 44,
        borderRadius: 22,
        shapeType: 'circle',
      },
    ],
  },
  {
    id: 'rocket',
    title: 'Space Rocket',
    category: 'vehicles',
    difficulty: 4,
    emoji: '🚀',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'body',
        name: 'Rocket Body',
        suggestedColorHex: '#F8FAFC',
        x: 85,
        y: 50,
        width: 70,
        height: 120,
        borderRadius: 35,
        shapeType: 'rect',
      },
      {
        id: 'nose',
        name: 'Nose Cone',
        suggestedColorHex: '#EF4444',
        x: 90,
        y: 20,
        width: 60,
        height: 40,
        borderRadius: 20,
        shapeType: 'triangle',
      },
      {
        id: 'fin_left',
        name: 'Left Fin',
        suggestedColorHex: '#3B82F6',
        x: 45,
        y: 130,
        width: 40,
        height: 50,
        borderRadius: 10,
        shapeType: 'triangle',
      },
      {
        id: 'fin_right',
        name: 'Right Fin',
        suggestedColorHex: '#3B82F6',
        x: 155,
        y: 130,
        width: 40,
        height: 50,
        borderRadius: 10,
        shapeType: 'triangle',
      },
      {
        id: 'window',
        name: 'Porthole Window',
        suggestedColorHex: '#0EA5E9',
        x: 102,
        y: 80,
        width: 36,
        height: 36,
        borderRadius: 18,
        shapeType: 'circle',
      },
      {
        id: 'flame',
        name: 'Thruster Flame',
        suggestedColorHex: '#F97316',
        x: 98,
        y: 175,
        width: 44,
        height: 45,
        borderRadius: 22,
        shapeType: 'ellipse',
      },
    ],
  },
  {
    id: 'butterfly',
    title: 'Pretty Butterfly',
    category: 'animals',
    difficulty: 4,
    emoji: '🦋',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'body',
        name: 'Butterfly Body',
        suggestedColorHex: '#18181B',
        x: 112,
        y: 50,
        width: 16,
        height: 120,
        borderRadius: 8,
        shapeType: 'rect',
      },
      {
        id: 'wing_top_left',
        name: 'Top Left Wing',
        suggestedColorHex: '#8B5CF6',
        x: 35,
        y: 45,
        width: 75,
        height: 70,
        borderRadius: 35,
        shapeType: 'ellipse',
      },
      {
        id: 'wing_top_right',
        name: 'Top Right Wing',
        suggestedColorHex: '#8B5CF6',
        x: 130,
        y: 45,
        width: 75,
        height: 70,
        borderRadius: 35,
        shapeType: 'ellipse',
      },
      {
        id: 'wing_bottom_left',
        name: 'Bottom Left Wing',
        suggestedColorHex: '#EC4899',
        x: 45,
        y: 115,
        width: 65,
        height: 60,
        borderRadius: 30,
        shapeType: 'ellipse',
      },
      {
        id: 'wing_bottom_right',
        name: 'Bottom Right Wing',
        suggestedColorHex: '#EC4899',
        x: 130,
        y: 115,
        width: 65,
        height: 60,
        borderRadius: 30,
        shapeType: 'ellipse',
      },
    ],
  },
  {
    id: 'fish',
    title: 'Happy Fish',
    category: 'animals',
    difficulty: 2,
    emoji: '🐟',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'body',
        name: 'Fish Body',
        suggestedColorHex: '#F97316',
        x: 45,
        y: 70,
        width: 130,
        height: 100,
        borderRadius: 50,
        shapeType: 'ellipse',
      },
      {
        id: 'tail',
        name: 'Tail Fin',
        suggestedColorHex: '#EAB308',
        x: 165,
        y: 80,
        width: 50,
        height: 80,
        borderRadius: 16,
        shapeType: 'triangle',
      },
      {
        id: 'eye',
        name: 'Eye',
        suggestedColorHex: '#18181B',
        x: 75,
        y: 100,
        width: 16,
        height: 16,
        borderRadius: 8,
        shapeType: 'circle',
      },
    ],
  },
  {
    id: 'cat',
    title: 'Cute Kitty Cat',
    category: 'animals',
    difficulty: 3,
    emoji: '🐱',
    viewBox: {width: 240, height: 240},
    regions: [
      {
        id: 'head',
        name: 'Cat Head',
        suggestedColorHex: '#F97316',
        x: 60,
        y: 70,
        width: 120,
        height: 110,
        borderRadius: 60,
        shapeType: 'circle',
      },
      {
        id: 'ear_left',
        name: 'Left Ear',
        suggestedColorHex: '#EA580C',
        x: 55,
        y: 40,
        width: 40,
        height: 40,
        borderRadius: 10,
        shapeType: 'triangle',
      },
      {
        id: 'ear_right',
        name: 'Right Ear',
        suggestedColorHex: '#EA580C',
        x: 145,
        y: 40,
        width: 40,
        height: 40,
        borderRadius: 10,
        shapeType: 'triangle',
      },
      {
        id: 'nose',
        name: 'Pink Nose',
        suggestedColorHex: '#EC4899',
        x: 112,
        y: 125,
        width: 16,
        height: 14,
        borderRadius: 7,
        shapeType: 'triangle',
      },
    ],
  },
];

export const TRACING_PATHS: readonly TracingPath[] = [
  {
    id: 'trace_line_horiz',
    title: 'Straight Highway',
    subtitle: 'Trace from left to right',
    type: 'line',
    emoji: '➖',
    points: [
      {x: 30, y: 120},
      {x: 80, y: 120},
      {x: 130, y: 120},
      {x: 180, y: 120},
      {x: 230, y: 120},
    ],
  },
  {
    id: 'trace_line_vert',
    title: 'Raindrop Drop',
    subtitle: 'Trace straight down',
    type: 'line',
    emoji: '🌧️',
    points: [
      {x: 130, y: 30},
      {x: 130, y: 80},
      {x: 130, y: 130},
      {x: 130, y: 180},
      {x: 130, y: 230},
    ],
  },
  {
    id: 'trace_zigzag',
    title: 'Mountain Peaks',
    subtitle: 'Trace up and down zig-zags',
    type: 'zigzag',
    emoji: '⛰️',
    points: [
      {x: 30, y: 160},
      {x: 80, y: 70},
      {x: 130, y: 160},
      {x: 180, y: 70},
      {x: 230, y: 160},
    ],
  },
  {
    id: 'trace_wave',
    title: 'Ocean Wave',
    subtitle: 'Trace smooth curvy waves',
    type: 'wave',
    emoji: '🌊',
    points: [
      {x: 30, y: 120},
      {x: 75, y: 70},
      {x: 130, y: 120},
      {x: 185, y: 170},
      {x: 230, y: 120},
    ],
  },
  {
    id: 'trace_circle',
    title: 'Full Moon Circle',
    subtitle: 'Trace all the way round',
    type: 'shape',
    emoji: '🌕',
    points: [
      {x: 130, y: 40},
      {x: 200, y: 80},
      {x: 210, y: 130},
      {x: 190, y: 190},
      {x: 130, y: 210},
      {x: 70, y: 190},
      {x: 50, y: 130},
      {x: 70, y: 70},
      {x: 130, y: 40},
    ],
  },
];

export const SHAPES_DATA: readonly ShapeItem[] = [
  {
    id: 'circle',
    name: 'Circle',
    emoji: '🔴',
    color: '#EF4444',
    sides: 0,
    funFact: 'A circle has no corners and goes round and round forever!',
    strokeSequence: [
      '1. Start at the top center point',
      '2. Curve around to the left and bottom',
      '3. Curve back up to close the circle',
    ],
    guidePoints: [
      {x: 130, y: 40},
      {x: 210, y: 120},
      {x: 130, y: 200},
      {x: 50, y: 120},
      {x: 130, y: 40},
    ],
  },
  {
    id: 'square',
    name: 'Square',
    emoji: '🟦',
    color: '#3B82F6',
    sides: 4,
    funFact: 'A square has 4 equal sides and 4 square corners!',
    strokeSequence: [
      '1. Draw the top line straight across',
      '2. Draw down the right side',
      '3. Draw across the bottom',
      '4. Draw back up to the start',
    ],
    guidePoints: [
      {x: 50, y: 50},
      {x: 200, y: 50},
      {x: 200, y: 200},
      {x: 50, y: 200},
      {x: 50, y: 50},
    ],
  },
  {
    id: 'triangle',
    name: 'Triangle',
    emoji: '🔺',
    color: '#EAB308',
    sides: 3,
    funFact: 'A triangle has 3 pointy corners like a slice of pizza!',
    strokeSequence: [
      '1. Start at the top point',
      '2. Slant down to the bottom-right',
      '3. Draw flat across the bottom',
      '4. Slant back up to the top peak',
    ],
    guidePoints: [
      {x: 130, y: 40},
      {x: 210, y: 200},
      {x: 50, y: 200},
      {x: 130, y: 40},
    ],
  },
  {
    id: 'rectangle',
    name: 'Rectangle',
    emoji: '🚪',
    color: '#10B981',
    sides: 4,
    funFact: 'A rectangle has 2 long sides and 2 short sides like a door!',
    strokeSequence: [
      '1. Draw a long line across the top',
      '2. Draw a short line down the right',
      '3. Draw a long line across the bottom',
      '4. Draw a short line back up',
    ],
    guidePoints: [
      {x: 40, y: 70},
      {x: 210, y: 70},
      {x: 210, y: 170},
      {x: 40, y: 170},
      {x: 40, y: 70},
    ],
  },
  {
    id: 'star',
    name: 'Star',
    emoji: '⭐',
    color: '#F59E0B',
    sides: 5,
    funFact: 'A star has 5 glowing points that twinkle in the sky!',
    strokeSequence: [
      '1. Draw up to the top star point',
      '2. Criss-cross diagonal lines',
      '3. Connect all five points into a star',
    ],
    guidePoints: [
      {x: 130, y: 35},
      {x: 155, y: 100},
      {x: 220, y: 105},
      {x: 170, y: 145},
      {x: 190, y: 210},
      {x: 130, y: 170},
      {x: 70, y: 210},
      {x: 90, y: 145},
      {x: 40, y: 105},
      {x: 105, y: 100},
      {x: 130, y: 35},
    ],
  },
  {
    id: 'heart',
    name: 'Heart',
    emoji: '❤️',
    color: '#EC4899',
    sides: 2,
    funFact:
      'A heart shape is made of two curved arches meeting at a bottom tip!',
    strokeSequence: [
      '1. Curve up and around the left lobe',
      '2. Angle down to the bottom point',
      '3. Curve up and around the right lobe to complete',
    ],
    guidePoints: [
      {x: 130, y: 80},
      {x: 80, y: 35},
      {x: 40, y: 80},
      {x: 130, y: 210},
      {x: 220, y: 80},
      {x: 180, y: 35},
      {x: 130, y: 80},
    ],
  },
];

export const SIMPLE_OBJECT_DRAWING_DATA: readonly SimpleObjectDrawingItem[] = [
  {
    id: 'obj_sun',
    title: 'How to Draw a Sun',
    emoji: '☀️',
    level: 1,
    baseShape: 'Circle',
    instructions: [
      'Draw a large circle in the middle',
      'Add straight ray lines radiating all around',
      'Give your sun two eyes and a happy smile!',
    ],
    stepPreviews: ['1. Circle ⭕', '2. Sun Rays ☀️', '3. Happy Face 😊'],
  },
  {
    id: 'obj_tree',
    title: 'How to Draw a Tree',
    emoji: '🌳',
    level: 1,
    baseShape: 'Rectangle + Clouds',
    instructions: [
      'Draw two tall vertical lines for the trunk',
      'Draw a fluffy cloud shape on top for the leaves',
      'Add little branch lines inside!',
    ],
    stepPreviews: ['1. Trunk 🪵', '2. Canopy ☁️', '3. Branches 🌿'],
  },
  {
    id: 'obj_house',
    title: 'How to Draw a House',
    emoji: '🏠',
    level: 1,
    baseShape: 'Square + Triangle',
    instructions: [
      'Draw a big square for the walls',
      'Draw a triangle roof on top',
      'Add a rectangle door and square windows!',
    ],
    stepPreviews: ['1. Square ⬛', '2. Roof 🔺', '3. Door & Windows 🪟'],
  },
  {
    id: 'obj_fish',
    title: 'How to Draw a Fish',
    emoji: '🐟',
    level: 2,
    baseShape: 'Oval + Triangle',
    instructions: [
      'Draw an oval egg shape for the body',
      'Add a triangle tail fin on the side',
      'Draw a round eye and little swimming fins!',
    ],
    stepPreviews: ['1. Oval Body 🥚', '2. Tail Fin 📐', '3. Eye & Fins 👁️'],
  },
  {
    id: 'obj_cat',
    title: 'How to Draw a Cat',
    emoji: '🐱',
    level: 2,
    baseShape: 'Circles + Triangles',
    instructions: [
      'Draw a round head',
      'Add two triangle ears on top',
      'Draw eyes, a triangle nose, and long whiskers!',
    ],
    stepPreviews: ['1. Head ⭕', '2. Ears 🔺', '3. Face & Whiskers 😺'],
  },
  {
    id: 'obj_car',
    title: 'How to Draw a Car',
    emoji: '🚗',
    level: 3,
    baseShape: 'Rectangles + Circles',
    instructions: [
      'Draw a long rectangle for the lower car body',
      'Draw a smaller box on top for the windows',
      'Add two round circles for wheels at the bottom!',
    ],
    stepPreviews: ['1. Long Body 🚘', '2. Windows 🪟', '3. Wheels 🛞'],
  },
  {
    id: 'obj_rocket',
    title: 'How to Draw a Rocket',
    emoji: '🚀',
    level: 3,
    baseShape: 'Tall Oval + Triangles',
    instructions: [
      'Draw a tall rocket fuselage',
      'Add a triangle nose cone at the top',
      'Add side fins and fiery thrusters at the bottom!',
    ],
    stepPreviews: ['1. Fuselage 🚀', '2. Fins 📐', '3. Flames 🔥'],
  },
];

export const GUIDED_DRAWING_LESSONS: readonly GuidedDrawingLesson[] = [
  {
    id: 'guided_cat',
    title: 'Draw a Cute Cat',
    emoji: '🐱',
    totalSteps: 5,
    coloringSuggestion: ['Orange', 'Pink', 'White'],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Step 1: Draw a big circle for the cat’s head.',
        hintEmoji: '⭕',
        strokeDescription: 'Circle head in the middle',
        guidePoints: [
          {x: 130, y: 70},
          {x: 190, y: 130},
          {x: 130, y: 190},
          {x: 70, y: 130},
          {x: 130, y: 70},
        ],
      },
      {
        stepNumber: 2,
        instruction: 'Step 2: Add two triangle ears on the top left and right.',
        hintEmoji: '🔺',
        strokeDescription: 'Triangle ears on top',
        guidePoints: [
          {x: 80, y: 75},
          {x: 65, y: 35},
          {x: 105, y: 60},
        ],
      },
      {
        stepNumber: 3,
        instruction: 'Step 3: Draw two shiny round eyes.',
        hintEmoji: '👀',
        strokeDescription: 'Two circle eyes inside',
        guidePoints: [
          {x: 100, y: 110},
          {x: 110, y: 110},
        ],
      },
      {
        stepNumber: 4,
        instruction: 'Step 4: Draw a little triangle nose and smiling mouth.',
        hintEmoji: '😺',
        strokeDescription: 'Nose and smile',
        guidePoints: [
          {x: 130, y: 135},
          {x: 120, y: 155},
          {x: 140, y: 155},
        ],
      },
      {
        stepNumber: 5,
        instruction: 'Step 5: Add long whiskers on each side!',
        hintEmoji: '✨',
        strokeDescription: 'Whiskers on cheeks',
        guidePoints: [
          {x: 50, y: 135},
          {x: 90, y: 140},
          {x: 170, y: 140},
          {x: 210, y: 135},
        ],
      },
    ],
  },
  {
    id: 'guided_fish',
    title: 'Draw a Swimming Fish',
    emoji: '🐟',
    totalSteps: 4,
    coloringSuggestion: ['Blue', 'Yellow', 'Orange'],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Step 1: Draw a smooth oval body.',
        hintEmoji: '🥚',
        strokeDescription: 'Oval body in the center',
        guidePoints: [
          {x: 60, y: 130},
          {x: 130, y: 80},
          {x: 180, y: 130},
          {x: 130, y: 180},
          {x: 60, y: 130},
        ],
      },
      {
        stepNumber: 2,
        instruction: 'Step 2: Add a triangle tail on the right side.',
        hintEmoji: '📐',
        strokeDescription: 'Tail fin on back',
        guidePoints: [
          {x: 175, y: 130},
          {x: 220, y: 85},
          {x: 220, y: 175},
          {x: 175, y: 130},
        ],
      },
      {
        stepNumber: 3,
        instruction: 'Step 3: Draw a happy round eye near the front.',
        hintEmoji: '👁️',
        strokeDescription: 'Eye on front of face',
        guidePoints: [{x: 95, y: 115}],
      },
      {
        stepNumber: 4,
        instruction: 'Step 4: Draw top and bottom swimming fins!',
        hintEmoji: '🌊',
        strokeDescription: 'Fins and scales',
        guidePoints: [
          {x: 125, y: 80},
          {x: 145, y: 55},
          {x: 160, y: 85},
        ],
      },
    ],
  },
  {
    id: 'guided_rocket',
    title: 'Draw a Blast-off Rocket',
    emoji: '🚀',
    totalSteps: 4,
    coloringSuggestion: ['Red', 'White', 'Blue', 'Orange'],
    steps: [
      {
        stepNumber: 1,
        instruction: 'Step 1: Draw a tall capsule shape for the rocket body.',
        hintEmoji: '🚀',
        strokeDescription: 'Vertical capsule body',
        guidePoints: [
          {x: 95, y: 60},
          {x: 165, y: 60},
          {x: 165, y: 180},
          {x: 95, y: 180},
          {x: 95, y: 60},
        ],
      },
      {
        stepNumber: 2,
        instruction: 'Step 2: Add a pointed triangle nose cone on top.',
        hintEmoji: '🔺',
        strokeDescription: 'Triangle nose on top',
        guidePoints: [
          {x: 95, y: 60},
          {x: 130, y: 20},
          {x: 165, y: 60},
        ],
      },
      {
        stepNumber: 3,
        instruction: 'Step 3: Add two angled wings on the bottom sides.',
        hintEmoji: '📐',
        strokeDescription: 'Side rocket fins',
        guidePoints: [
          {x: 95, y: 140},
          {x: 55, y: 185},
          {x: 95, y: 185},
        ],
      },
      {
        stepNumber: 4,
        instruction: 'Step 4: Draw a round window and flame blasts underneath!',
        hintEmoji: '🔥',
        strokeDescription: 'Window and flames',
        guidePoints: [
          {x: 130, y: 110},
          {x: 110, y: 185},
          {x: 130, y: 220},
          {x: 150, y: 185},
        ],
      },
    ],
  },
];

export const CREATIVE_CHALLENGES: readonly CreativeChallengeItem[] = [
  {
    id: 'challenge_dream_house',
    title: 'My Dream House',
    prompt:
      'Draw the house of your dreams! Add colors, windows, trees, and flowers around it.',
    emoji: '🏡',
    inspirationalTips: [
      'You can make a castle, treehouse, or cozy cottage!',
      'Try adding a sun and rainbow!',
    ],
    suggestedPalette: ['#EF4444', '#3B82F6', '#EAB308', '#10B981', '#F97316'],
  },
  {
    id: 'challenge_favorite_animal',
    title: 'My Favorite Animal',
    prompt:
      'Draw your favorite pet or wild animal! Is it a cat, dog, lion, or cute puppy?',
    emoji: '🦁',
    inspirationalTips: [
      'Start with simple circles for the head and body.',
      'Add ears, a tail, and fur spots!',
    ],
    suggestedPalette: ['#78350F', '#F97316', '#EAB308', '#18181B', '#EC4899'],
  },
  {
    id: 'challenge_space_adventure',
    title: 'Space Adventure',
    prompt:
      'Draw a journey through outer space! Include stars, planets, and a soaring spaceship.',
    emoji: '🪐',
    inspirationalTips: [
      'Draw glowing stars with yellow and white.',
      'Add rings around colorful planets!',
    ],
    suggestedPalette: ['#3B82F6', '#8B5CF6', '#EAB308', '#F97316', '#F8FAFC'],
  },
  {
    id: 'challenge_magical_garden',
    title: 'Magical Flower Garden',
    prompt:
      'Draw a vibrant sunny garden with colorful blooming flowers and fluttering butterflies.',
    emoji: '🌸',
    inspirationalTips: [
      'Mix different flower petal shapes.',
      'Draw happy buzzing bees!',
    ],
    suggestedPalette: ['#EC4899', '#10B981', '#EAB308', '#8B5CF6', '#3B82F6'],
  },
  {
    id: 'challenge_happy_family',
    title: 'My Happy Family',
    prompt:
      'Draw you and the people you love having fun together outside on a sunny day.',
    emoji: '👨‍👩‍👧',
    inspirationalTips: [
      'Give everyone happy smiles!',
      'Add colorful clothes and bright grass below.',
    ],
    suggestedPalette: ['#EF4444', '#3B82F6', '#10B981', '#F97316', '#EAB308'],
  },
];

export const SUBMODULE_QUIZZES: Record<string, readonly DrawingQuizQuestion[]> =
  {
    colors: [
      {
        id: 'quiz_c1',
        question: 'Which of these is the color Red?',
        promptAudioText: 'Which of these is the color Red?',
        type: 'color_identify',
        targetHex: '#EF4444',
        targetEmoji: '🔴',
        options: [
          {id: 'blue', text: 'Blue', hex: '#3B82F6', emoji: '🔵'},
          {id: 'red', text: 'Red', hex: '#EF4444', emoji: '🔴'},
          {id: 'yellow', text: 'Yellow', hex: '#EAB308', emoji: '🟡'},
        ],
        answerId: 'red',
        explanation: 'Red is warm and bright like a tasty apple 🍎!',
      },
      {
        id: 'quiz_c2',
        question: 'What color is a juicy yellow lemon?',
        promptAudioText: 'What color is a juicy yellow lemon?',
        type: 'object_match',
        targetEmoji: '🍋',
        options: [
          {id: 'yellow', text: 'Yellow', hex: '#EAB308', emoji: '🟡'},
          {id: 'purple', text: 'Purple', hex: '#8B5CF6', emoji: '🟣'},
          {id: 'green', text: 'Green', hex: '#10B981', emoji: '🟢'},
        ],
        answerId: 'yellow',
        explanation: 'Lemons are sunny and yellow 🍋!',
      },
      {
        id: 'quiz_c3',
        question: 'Which object is naturally Blue?',
        promptAudioText: 'Which object is naturally Blue?',
        type: 'object_match',
        options: [
          {id: 'apple', text: 'Apple', emoji: '🍎'},
          {id: 'ocean', text: 'Ocean Waves', emoji: '🌊'},
          {id: 'banana', text: 'Banana', emoji: '🍌'},
        ],
        answerId: 'ocean',
        explanation: 'Ocean waves are deep cool blue 🌊!',
      },
    ],
    color_mix: [
      {
        id: 'quiz_m1',
        question: 'What color do you get by mixing Red + Yellow?',
        promptAudioText: 'What color do you get by mixing Red and Yellow?',
        type: 'color_mix',
        options: [
          {id: 'green', text: 'Green', hex: '#10B981', emoji: '🟢'},
          {id: 'orange', text: 'Orange', hex: '#F97316', emoji: '🟠'},
          {id: 'purple', text: 'Purple', hex: '#8B5CF6', emoji: '🟣'},
        ],
        answerId: 'orange',
        explanation: 'Red + Yellow = Orange 🟠!',
      },
      {
        id: 'quiz_m2',
        question: 'What color do you get by mixing Blue + Yellow?',
        promptAudioText: 'What color do you get by mixing Blue and Yellow?',
        type: 'color_mix',
        options: [
          {id: 'orange', text: 'Orange', hex: '#F97316', emoji: '🟠'},
          {id: 'green', text: 'Green', hex: '#10B981', emoji: '🟢'},
          {id: 'pink', text: 'Pink', hex: '#EC4899', emoji: '🩷'},
        ],
        answerId: 'green',
        explanation: 'Blue + Yellow = Green 🟢!',
      },
      {
        id: 'quiz_m3',
        question: 'What color do you get by mixing Red + Blue?',
        promptAudioText: 'What color do you get by mixing Red and Blue?',
        type: 'color_mix',
        options: [
          {id: 'purple', text: 'Purple', hex: '#8B5CF6', emoji: '🟣'},
          {id: 'yellow', text: 'Yellow', hex: '#EAB308', emoji: '🟡'},
          {id: 'brown', text: 'Brown', hex: '#78350F', emoji: '🟤'},
        ],
        answerId: 'purple',
        explanation: 'Red + Blue = Purple 🟣!',
      },
    ],
    shapes: [
      {
        id: 'quiz_s1',
        question: 'Which shape has NO corners and is completely round?',
        promptAudioText: 'Which shape has no corners and is completely round?',
        type: 'shape_identify',
        options: [
          {id: 'square', text: 'Square', emoji: '🟦'},
          {id: 'circle', text: 'Circle', emoji: '🔴'},
          {id: 'triangle', text: 'Triangle', emoji: '🔺'},
        ],
        answerId: 'circle',
        explanation: 'A circle has 0 corners and curves all the way around 🔴!',
      },
      {
        id: 'quiz_s2',
        question: 'Which shape has exactly 3 pointy corners?',
        promptAudioText: 'Which shape has exactly 3 pointy corners?',
        type: 'shape_identify',
        options: [
          {id: 'triangle', text: 'Triangle', emoji: '🔺'},
          {id: 'rectangle', text: 'Rectangle', emoji: '🚪'},
          {id: 'circle', text: 'Circle', emoji: '🔴'},
        ],
        answerId: 'triangle',
        explanation: 'Triangles have 3 sides and 3 corners 🔺!',
      },
      {
        id: 'quiz_s3',
        question: 'Which shape has 4 equal straight sides?',
        promptAudioText: 'Which shape has 4 equal straight sides?',
        type: 'shape_identify',
        options: [
          {id: 'circle', text: 'Circle', emoji: '🔴'},
          {id: 'star', text: 'Star', emoji: '⭐'},
          {id: 'square', text: 'Square', emoji: '🟦'},
        ],
        answerId: 'square',
        explanation: 'A square has 4 equal sides 🟦!',
      },
    ],
  };
