import type {GKCategory, GKLessonQuestion} from '../entities/gkEntities';

export const GK_CATEGORIES: readonly GKCategory[] = [
  // ─── 1. Vehicles ──────────────────────────────────────────────────────────
  {
    id: 'vehicles',
    titleKey: 'generalKnowledge.categories.vehicles.title',
    subtitleKey: 'generalKnowledge.categories.vehicles.sub',
    emoji: '🚗',
    accentColor: '#EF4444',
    badgeTag: '10 Vehicles',
    lessons: [
      {
        id: 'veh-car',
        categoryId: 'vehicles',
        orderIndex: 1,
        titleKey: 'generalKnowledge.vehicles.car.title',
        subtitleKey: 'generalKnowledge.vehicles.car.sub',
        emoji: '🚗',
        factKey: 'generalKnowledge.vehicles.car.fact',
        purposeKey: 'generalKnowledge.vehicles.car.purpose',
        accentColor: '#EF4444',
        practice: {
          promptKey: 'generalKnowledge.practice.tapCar',
          targetEmoji: '🚗',
          choices: [
            {
              id: 'c1',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: true,
            },
            {
              id: 'c2',
              labelKey: 'generalKnowledge.vehicles.ship.title',
              emoji: '🚢',
              isCorrect: false,
            },
            {
              id: 'c3',
              labelKey: 'generalKnowledge.vehicles.airplane.title',
              emoji: '✈️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-car-1',
            questionKey: 'generalKnowledge.quiz.carQ1',
            questionType: 'identify-object',
            promptEmoji: '🚗',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.car.title',
                icon: '🚗',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.airplane.title',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.carExp1',
          },
          {
            id: 'q-car-2',
            questionKey: 'generalKnowledge.quiz.carQ2',
            questionType: 'match-purpose',
            promptEmoji: '🛣️ 4️⃣',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.fourWheels',
                icon: '🚗 🛞',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.twoWings',
                icon: '🪽',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.sailsWater',
                icon: '🌊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.carExp2',
          },
          {
            id: 'q-car-3',
            questionKey: 'generalKnowledge.quiz.carQ3',
            questionType: 'fact-check',
            promptEmoji: '🛑 🚦',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.wearSeatbelt',
                icon: '🔒',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.jumpAround',
                icon: '🤾',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.openDoors',
                icon: '🚪',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.carExp3',
          },
        ],
      },
      {
        id: 'veh-bus',
        categoryId: 'vehicles',
        orderIndex: 2,
        titleKey: 'generalKnowledge.vehicles.bus.title',
        subtitleKey: 'generalKnowledge.vehicles.bus.sub',
        emoji: '🚌',
        factKey: 'generalKnowledge.vehicles.bus.fact',
        purposeKey: 'generalKnowledge.vehicles.bus.purpose',
        accentColor: '#F59E0B',
        practice: {
          promptKey: 'generalKnowledge.practice.tapBus',
          targetEmoji: '🚌',
          choices: [
            {
              id: 'b1',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'b2',
              labelKey: 'generalKnowledge.vehicles.bus.title',
              emoji: '🚌',
              isCorrect: true,
            },
            {
              id: 'b3',
              labelKey: 'generalKnowledge.vehicles.train.title',
              emoji: '🚂',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-bus-1',
            questionKey: 'generalKnowledge.quiz.busQ1',
            questionType: 'identify-object',
            promptEmoji: '🚌 🏫',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.bus.title',
                icon: '🚌',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.bicycle.title',
                icon: '🚲',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.busExp1',
          },
          {
            id: 'q-bus-2',
            questionKey: 'generalKnowledge.quiz.busQ2',
            questionType: 'match-purpose',
            promptEmoji: '👥 🚌',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.carriesManyPeople',
                icon: '👥 🚌',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.fliesInClouds',
                icon: '☁️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.divesUnderWater',
                icon: '🌊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.busExp2',
          },
          {
            id: 'q-bus-3',
            questionKey: 'generalKnowledge.quiz.busQ3',
            questionType: 'match-job',
            promptEmoji: '👨‍✈️ 🚌',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.busDriver',
                icon: '👨‍✈️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.pilotJob',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.chefJob',
                icon: '👩‍🍳',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.busExp3',
          },
        ],
      },
      {
        id: 'veh-ambulance',
        categoryId: 'vehicles',
        orderIndex: 3,
        titleKey: 'generalKnowledge.vehicles.ambulance.title',
        subtitleKey: 'generalKnowledge.vehicles.ambulance.sub',
        emoji: '🚑',
        factKey: 'generalKnowledge.vehicles.ambulance.fact',
        purposeKey: 'generalKnowledge.vehicles.ambulance.purpose',
        accentColor: '#EF4444',
        practice: {
          promptKey: 'generalKnowledge.practice.tapAmbulance',
          targetEmoji: '🚑',
          choices: [
            {
              id: 'a1',
              labelKey: 'generalKnowledge.vehicles.ambulance.title',
              emoji: '🚑',
              isCorrect: true,
            },
            {
              id: 'a2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'a3',
              labelKey: 'generalKnowledge.vehicles.bus.title',
              emoji: '🚌',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-amb-1',
            questionKey: 'generalKnowledge.quiz.ambQ1',
            questionType: 'identify-object',
            promptEmoji: '🚑 🚨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.ambulance.title',
                icon: '🚑',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.police.title',
                icon: '🚓',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.train.title',
                icon: '🚂',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ambExp1',
          },
          {
            id: 'q-amb-2',
            questionKey: 'generalKnowledge.quiz.ambQ2',
            questionType: 'match-purpose',
            promptEmoji: '🏥 🚨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.takesSickToHospital',
                icon: '🏥',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.deliversMail',
                icon: '✉️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.carriesIceCream',
                icon: '🍦',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ambExp2',
          },
          {
            id: 'q-amb-3',
            questionKey: 'generalKnowledge.quiz.ambQ3',
            questionType: 'scenario',
            promptEmoji: '🚨 🔊',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.giveWayAmbulance',
                icon: '🚗 ➡️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.blockRoad',
                icon: '🛑',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.raceAmbulance',
                icon: '🏎️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ambExp3',
          },
        ],
      },
      {
        id: 'veh-fire-truck',
        categoryId: 'vehicles',
        orderIndex: 4,
        titleKey: 'generalKnowledge.vehicles.fireTruck.title',
        subtitleKey: 'generalKnowledge.vehicles.fireTruck.sub',
        emoji: '🚒',
        factKey: 'generalKnowledge.vehicles.fireTruck.fact',
        purposeKey: 'generalKnowledge.vehicles.fireTruck.purpose',
        accentColor: '#DC2626',
        practice: {
          promptKey: 'generalKnowledge.practice.tapFireTruck',
          targetEmoji: '🚒',
          choices: [
            {
              id: 'f1',
              labelKey: 'generalKnowledge.vehicles.fireTruck.title',
              emoji: '🚒',
              isCorrect: true,
            },
            {
              id: 'f2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'f3',
              labelKey: 'generalKnowledge.vehicles.ship.title',
              emoji: '🚢',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-ft-1',
            questionKey: 'generalKnowledge.quiz.ftQ1',
            questionType: 'identify-object',
            promptEmoji: '🚒 🧯',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.fireTruck.title',
                icon: '🚒',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.bus.title',
                icon: '🚌',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.airplane.title',
                icon: '✈️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ftExp1',
          },
          {
            id: 'q-ft-2',
            questionKey: 'generalKnowledge.quiz.ftQ2',
            questionType: 'match-job',
            promptEmoji: '👨‍🚒 🚒',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.firefighter.title',
                icon: '👨‍🚒',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.chef.title',
                icon: '👩‍🍳',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.teacher.title',
                icon: '👩‍🏫',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ftExp2',
          },
          {
            id: 'q-ft-3',
            questionKey: 'generalKnowledge.quiz.ftQ3',
            questionType: 'match-purpose',
            promptEmoji: '🔥 💧',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.putsOutFires',
                icon: '💧 🔥',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.deliversPizzas',
                icon: '🍕',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.digsDeepHoles',
                icon: '⛏️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.ftExp3',
          },
        ],
      },
      {
        id: 'veh-police-car',
        categoryId: 'vehicles',
        orderIndex: 5,
        titleKey: 'generalKnowledge.vehicles.police.title',
        subtitleKey: 'generalKnowledge.vehicles.police.sub',
        emoji: '🚓',
        factKey: 'generalKnowledge.vehicles.police.fact',
        purposeKey: 'generalKnowledge.vehicles.police.purpose',
        accentColor: '#2563EB',
        practice: {
          promptKey: 'generalKnowledge.practice.tapPolice',
          targetEmoji: '🚓',
          choices: [
            {
              id: 'p1',
              labelKey: 'generalKnowledge.vehicles.police.title',
              emoji: '🚓',
              isCorrect: true,
            },
            {
              id: 'p2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'p3',
              labelKey: 'generalKnowledge.vehicles.bicycle.title',
              emoji: '🚲',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-pol-1',
            questionKey: 'generalKnowledge.quiz.polQ1',
            questionType: 'identify-object',
            promptEmoji: '🚓 👮',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.police.title',
                icon: '🚓',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.bus.title',
                icon: '🚌',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.polExp1',
          },
          {
            id: 'q-pol-2',
            questionKey: 'generalKnowledge.quiz.polQ2',
            questionType: 'match-purpose',
            promptEmoji: '🛡️ 🚓',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.keepsPeopleSafe',
                icon: '🛡️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.carriesGroceries',
                icon: '🛒',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.paintsHouses',
                icon: '🎨',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.polExp2',
          },
          {
            id: 'q-pol-3',
            questionKey: 'generalKnowledge.quiz.polQ3',
            questionType: 'match-job',
            promptEmoji: '👮 🚓',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.police.title',
                icon: '👮',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.farmer.title',
                icon: '👨‍🌾',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.doctor.title',
                icon: '👨‍⚕️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.polExp3',
          },
        ],
      },
      {
        id: 'veh-airplane',
        categoryId: 'vehicles',
        orderIndex: 6,
        titleKey: 'generalKnowledge.vehicles.airplane.title',
        subtitleKey: 'generalKnowledge.vehicles.airplane.sub',
        emoji: '✈️',
        factKey: 'generalKnowledge.vehicles.airplane.fact',
        purposeKey: 'generalKnowledge.vehicles.airplane.purpose',
        accentColor: '#3B82F6',
        practice: {
          promptKey: 'generalKnowledge.practice.tapAirplane',
          targetEmoji: '✈️',
          choices: [
            {
              id: 'ap1',
              labelKey: 'generalKnowledge.vehicles.airplane.title',
              emoji: '✈️',
              isCorrect: true,
            },
            {
              id: 'ap2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'ap3',
              labelKey: 'generalKnowledge.vehicles.train.title',
              emoji: '🚂',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-air-1',
            questionKey: 'generalKnowledge.quiz.airQ1',
            questionType: 'identify-object',
            promptEmoji: '✈️ ☁️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.airplane.title',
                icon: '✈️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.bus.title',
                icon: '🚌',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.airExp1',
          },
          {
            id: 'q-air-2',
            questionKey: 'generalKnowledge.quiz.airQ2',
            questionType: 'match-purpose',
            promptEmoji: '☁️ 🪽',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.fliesHighInSky',
                icon: '☁️ ✈️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.drivesOnTracks',
                icon: '🛤️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.swimsInPond',
                icon: '🦆',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.airExp2',
          },
          {
            id: 'q-air-3',
            questionKey: 'generalKnowledge.quiz.airQ3',
            questionType: 'match-job',
            promptEmoji: '👨‍✈️ ✈️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.pilot.title',
                icon: '✈️ 👨‍✈️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.builder.title',
                icon: '👷',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.chef.title',
                icon: '👩‍🍳',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.airExp3',
          },
        ],
      },
      {
        id: 'veh-ship',
        categoryId: 'vehicles',
        orderIndex: 7,
        titleKey: 'generalKnowledge.vehicles.ship.title',
        subtitleKey: 'generalKnowledge.vehicles.ship.sub',
        emoji: '🚢',
        factKey: 'generalKnowledge.vehicles.ship.fact',
        purposeKey: 'generalKnowledge.vehicles.ship.purpose',
        accentColor: '#0EA5E9',
        practice: {
          promptKey: 'generalKnowledge.practice.tapShip',
          targetEmoji: '🚢',
          choices: [
            {
              id: 's1',
              labelKey: 'generalKnowledge.vehicles.ship.title',
              emoji: '🚢',
              isCorrect: true,
            },
            {
              id: 's2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 's3',
              labelKey: 'generalKnowledge.vehicles.airplane.title',
              emoji: '✈️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-shp-1',
            questionKey: 'generalKnowledge.quiz.shpQ1',
            questionType: 'identify-object',
            promptEmoji: '🚢 🌊',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.train.title',
                icon: '🚂',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.car.title',
                icon: '🚗',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.shpExp1',
          },
          {
            id: 'q-shp-2',
            questionKey: 'generalKnowledge.quiz.shpQ2',
            questionType: 'match-purpose',
            promptEmoji: '🌊 ⚓',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.sailsAcrossOceans',
                icon: '🌊 🚢',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.fliesInSpace',
                icon: '🚀',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.ridesOnRoads',
                icon: '🛣️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.shpExp2',
          },
          {
            id: 'q-shp-3',
            questionKey: 'generalKnowledge.quiz.shpQ3',
            questionType: 'fact-check',
            promptEmoji: '⚓ 🚢',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.captainDrivesShip',
                icon: '👨‍✈️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.busDriverDrivesShip',
                icon: '🚌',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.fishDrivesShip',
                icon: '🐟',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.shpExp3',
          },
        ],
      },
      {
        id: 'veh-train',
        categoryId: 'vehicles',
        orderIndex: 8,
        titleKey: 'generalKnowledge.vehicles.train.title',
        subtitleKey: 'generalKnowledge.vehicles.train.sub',
        emoji: '🚂',
        factKey: 'generalKnowledge.vehicles.train.fact',
        purposeKey: 'generalKnowledge.vehicles.train.purpose',
        accentColor: '#8B5CF6',
        practice: {
          promptKey: 'generalKnowledge.practice.tapTrain',
          targetEmoji: '🚂',
          choices: [
            {
              id: 't1',
              labelKey: 'generalKnowledge.vehicles.train.title',
              emoji: '🚂',
              isCorrect: true,
            },
            {
              id: 't2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 't3',
              labelKey: 'generalKnowledge.vehicles.ship.title',
              emoji: '🚢',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-trn-1',
            questionKey: 'generalKnowledge.quiz.trnQ1',
            questionType: 'identify-object',
            promptEmoji: '🚂 🛤️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.vehicles.train.title',
                icon: '🚂',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.airplane.title',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.bicycle.title',
                icon: '🚲',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.trnExp1',
          },
          {
            id: 'q-trn-2',
            questionKey: 'generalKnowledge.quiz.trnQ2',
            questionType: 'match-purpose',
            promptEmoji: '🛤️ 🚂',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.runsOnRailwayTracks',
                icon: '🛤️ 🚂',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.floatsOnClouds',
                icon: '☁️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.swimsInRivers',
                icon: '🌊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.trnExp2',
          },
          {
            id: 'q-trn-3',
            questionKey: 'generalKnowledge.quiz.trnQ3',
            questionType: 'fact-check',
            promptEmoji: '🚂 💨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.chooChooSound',
                icon: '🚂 🎶',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.quackQuackSound',
                icon: '🦆',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.silentNoWheels',
                icon: '🔇',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.trnExp3',
          },
        ],
      },
    ],
  },

  // ─── 2. Occupations ───────────────────────────────────────────────────────
  {
    id: 'occupations',
    titleKey: 'generalKnowledge.categories.occupations.title',
    subtitleKey: 'generalKnowledge.categories.occupations.sub',
    emoji: '👩‍⚕️',
    accentColor: '#10B981',
    badgeTag: 'Community Helpers',
    lessons: [
      {
        id: 'occ-doctor',
        categoryId: 'occupations',
        orderIndex: 1,
        titleKey: 'generalKnowledge.occupations.doctor.title',
        subtitleKey: 'generalKnowledge.occupations.doctor.sub',
        emoji: '👨‍⚕️',
        factKey: 'generalKnowledge.occupations.doctor.fact',
        purposeKey: 'generalKnowledge.occupations.doctor.purpose',
        accentColor: '#10B981',
        practice: {
          promptKey: 'generalKnowledge.practice.tapDoctor',
          targetEmoji: '👨‍⚕️',
          choices: [
            {
              id: 'd1',
              labelKey: 'generalKnowledge.occupations.doctor.title',
              emoji: '👨‍⚕️',
              isCorrect: true,
            },
            {
              id: 'd2',
              labelKey: 'generalKnowledge.occupations.chef.title',
              emoji: '👩‍🍳',
              isCorrect: false,
            },
            {
              id: 'd3',
              labelKey: 'generalKnowledge.occupations.builder.title',
              emoji: '👷',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-doc-1',
            questionKey: 'generalKnowledge.quiz.docQ1',
            questionType: 'match-job',
            promptEmoji: '🩺 🏥',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.doctor.title',
                icon: '👨‍⚕️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.teacher.title',
                icon: '👩‍🏫',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.pilot.title',
                icon: '✈️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.docExp1',
          },
          {
            id: 'q-doc-2',
            questionKey: 'generalKnowledge.quiz.docQ2',
            questionType: 'match-purpose',
            promptEmoji: '🤒 💊',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.helpsSickFeelBetter',
                icon: '🩺 💖',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.cooksDinner',
                icon: '🍳',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.buildsRoads',
                icon: '🏗️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.docExp2',
          },
          {
            id: 'q-doc-3',
            questionKey: 'generalKnowledge.quiz.docQ3',
            questionType: 'identify-object',
            promptEmoji: '🩺',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.stethoscopeTool',
                icon: '🩺',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.hammerTool',
                icon: '🔨',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.fryingPan',
                icon: '🍳',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.docExp3',
          },
        ],
      },
      {
        id: 'occ-teacher',
        categoryId: 'occupations',
        orderIndex: 2,
        titleKey: 'generalKnowledge.occupations.teacher.title',
        subtitleKey: 'generalKnowledge.occupations.teacher.sub',
        emoji: '👩‍🏫',
        factKey: 'generalKnowledge.occupations.teacher.fact',
        purposeKey: 'generalKnowledge.occupations.teacher.purpose',
        accentColor: '#3B82F6',
        practice: {
          promptKey: 'generalKnowledge.practice.tapTeacher',
          targetEmoji: '👩‍🏫',
          choices: [
            {
              id: 'tch1',
              labelKey: 'generalKnowledge.occupations.teacher.title',
              emoji: '👩‍🏫',
              isCorrect: true,
            },
            {
              id: 'tch2',
              labelKey: 'generalKnowledge.occupations.farmer.title',
              emoji: '👨‍🌾',
              isCorrect: false,
            },
            {
              id: 'tch3',
              labelKey: 'generalKnowledge.occupations.firefighter.title',
              emoji: '👨‍🚒',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-tch-1',
            questionKey: 'generalKnowledge.quiz.tchQ1',
            questionType: 'match-job',
            promptEmoji: '📚 🏫',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.teacher.title',
                icon: '👩‍🏫',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.chef.title',
                icon: '👩‍🍳',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.police.title',
                icon: '👮',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tchExp1',
          },
          {
            id: 'q-tch-2',
            questionKey: 'generalKnowledge.quiz.tchQ2',
            questionType: 'match-purpose',
            promptEmoji: '📖 ✏️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.helpsKidsLearn',
                icon: '📚 ✨',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.fliesAirplanes',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.growsCrops',
                icon: '🌾',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tchExp2',
          },
          {
            id: 'q-tch-3',
            questionKey: 'generalKnowledge.quiz.tchQ3',
            questionType: 'fact-check',
            promptEmoji: '🏫 🎒',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.worksInSchool',
                icon: '🏫',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.worksInSubmarine',
                icon: '🌊',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.worksInJungle',
                icon: '🦁',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tchExp3',
          },
        ],
      },
      {
        id: 'occ-chef',
        categoryId: 'occupations',
        orderIndex: 3,
        titleKey: 'generalKnowledge.occupations.chef.title',
        subtitleKey: 'generalKnowledge.occupations.chef.sub',
        emoji: '👩‍🍳',
        factKey: 'generalKnowledge.occupations.chef.fact',
        purposeKey: 'generalKnowledge.occupations.chef.purpose',
        accentColor: '#F59E0B',
        practice: {
          promptKey: 'generalKnowledge.practice.tapChef',
          targetEmoji: '👩‍🍳',
          choices: [
            {
              id: 'cf1',
              labelKey: 'generalKnowledge.occupations.chef.title',
              emoji: '👩‍🍳',
              isCorrect: true,
            },
            {
              id: 'cf2',
              labelKey: 'generalKnowledge.occupations.doctor.title',
              emoji: '👨‍⚕️',
              isCorrect: false,
            },
            {
              id: 'cf3',
              labelKey: 'generalKnowledge.occupations.pilot.title',
              emoji: '✈️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-chf-1',
            questionKey: 'generalKnowledge.quiz.chfQ1',
            questionType: 'match-job',
            promptEmoji: '🍳 🥗',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.chef.title',
                icon: '👩‍🍳',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.builder.title',
                icon: '👷',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.police.title',
                icon: '👮',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chfExp1',
          },
          {
            id: 'q-chf-2',
            questionKey: 'generalKnowledge.quiz.chfQ2',
            questionType: 'match-purpose',
            promptEmoji: '🍲 🍽️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.cooksDeliciousFood',
                icon: '🍲 😋',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.repairsCars',
                icon: '🚗',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.fliesRockets',
                icon: '🚀',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chfExp2',
          },
          {
            id: 'q-chf-3',
            questionKey: 'generalKnowledge.quiz.chfQ3',
            questionType: 'identify-object',
            promptEmoji: '👨‍🍳 🎩',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.whiteChefHat',
                icon: '👨‍🍳',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.spaceHelmet',
                icon: '🧑‍🚀',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.swimmingGoggles',
                icon: '🥽',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chfExp3',
          },
        ],
      },
      {
        id: 'occ-farmer',
        categoryId: 'occupations',
        orderIndex: 4,
        titleKey: 'generalKnowledge.occupations.farmer.title',
        subtitleKey: 'generalKnowledge.occupations.farmer.sub',
        emoji: '👨‍🌾',
        factKey: 'generalKnowledge.occupations.farmer.fact',
        purposeKey: 'generalKnowledge.occupations.farmer.purpose',
        accentColor: '#10B981',
        practice: {
          promptKey: 'generalKnowledge.practice.tapFarmer',
          targetEmoji: '👨‍🌾',
          choices: [
            {
              id: 'fm1',
              labelKey: 'generalKnowledge.occupations.farmer.title',
              emoji: '👨‍🌾',
              isCorrect: true,
            },
            {
              id: 'fm2',
              labelKey: 'generalKnowledge.occupations.teacher.title',
              emoji: '👩‍🏫',
              isCorrect: false,
            },
            {
              id: 'fm3',
              labelKey: 'generalKnowledge.occupations.doctor.title',
              emoji: '👨‍⚕️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-fm-1',
            questionKey: 'generalKnowledge.quiz.fmQ1',
            questionType: 'match-job',
            promptEmoji: '🌾 🚜',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.occupations.farmer.title',
                icon: '👨‍🌾',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.occupations.pilot.title',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.occupations.firefighter.title',
                icon: '👨‍🚒',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.fmExp1',
          },
          {
            id: 'q-fm-2',
            questionKey: 'generalKnowledge.quiz.fmQ2',
            questionType: 'match-purpose',
            promptEmoji: '🍎 🥦 🌾',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.growsFruitsAndGrains',
                icon: '🌾 🍎',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.sellsTickets',
                icon: '🎟️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.singsConcerts',
                icon: '🎤',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.fmExp2',
          },
          {
            id: 'q-fm-3',
            questionKey: 'generalKnowledge.quiz.fmQ3',
            questionType: 'identify-object',
            promptEmoji: '🚜',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.tractorOnFarm',
                icon: '🚜',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.submarineInDeep',
                icon: '🌊',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.airplaneOnRunway',
                icon: '✈️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.fmExp3',
          },
        ],
      },
    ],
  },

  // ─── 3. Famous Places ─────────────────────────────────────────────────────
  {
    id: 'places',
    titleKey: 'generalKnowledge.categories.places.title',
    subtitleKey: 'generalKnowledge.categories.places.sub',
    emoji: '🌍',
    accentColor: '#8B5CF6',
    badgeTag: 'Landmarks & Wonders',
    lessons: [
      {
        id: 'plc-eiffel',
        categoryId: 'places',
        orderIndex: 1,
        titleKey: 'generalKnowledge.places.eiffel.title',
        subtitleKey: 'generalKnowledge.places.eiffel.sub',
        emoji: '🗼',
        factKey: 'generalKnowledge.places.eiffel.fact',
        purposeKey: 'generalKnowledge.places.eiffel.purpose',
        accentColor: '#8B5CF6',
        practice: {
          promptKey: 'generalKnowledge.practice.tapEiffel',
          targetEmoji: '🗼',
          choices: [
            {
              id: 'ef1',
              labelKey: 'generalKnowledge.places.eiffel.title',
              emoji: '🗼',
              isCorrect: true,
            },
            {
              id: 'ef2',
              labelKey: 'generalKnowledge.places.taj.title',
              emoji: '🕌',
              isCorrect: false,
            },
            {
              id: 'ef3',
              labelKey: 'generalKnowledge.places.pyramids.title',
              emoji: '🔺',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-eif-1',
            questionKey: 'generalKnowledge.quiz.eifQ1',
            questionType: 'identify-object',
            promptEmoji: '🗼 🇫🇷',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.places.statue.title',
                icon: '🗽',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.pyramids.title',
                icon: '🔺',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.eifExp1',
          },
          {
            id: 'q-eif-2',
            questionKey: 'generalKnowledge.quiz.eifQ2',
            questionType: 'fact-check',
            promptEmoji: '🗼 🗼',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.madeOfIronInParis',
                icon: '🗼 🇫🇷',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.madeOfChocolate',
                icon: '🍫',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.floatsOnWater',
                icon: '🌊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.eifExp2',
          },
          {
            id: 'q-eif-3',
            questionKey: 'generalKnowledge.quiz.eifQ3',
            questionType: 'match-purpose',
            promptEmoji: '✨ 🌃',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.sparklesAtNight',
                icon: '✨ 🌟',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.turnsIntoRocket',
                icon: '🚀',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.sleepsUnderground',
                icon: '🕳️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.eifExp3',
          },
        ],
      },
      {
        id: 'plc-taj',
        categoryId: 'places',
        orderIndex: 2,
        titleKey: 'generalKnowledge.places.taj.title',
        subtitleKey: 'generalKnowledge.places.taj.sub',
        emoji: '🕌',
        factKey: 'generalKnowledge.places.taj.fact',
        purposeKey: 'generalKnowledge.places.taj.purpose',
        accentColor: '#06B6D4',
        practice: {
          promptKey: 'generalKnowledge.practice.tapTaj',
          targetEmoji: '🕌',
          choices: [
            {
              id: 'tj1',
              labelKey: 'generalKnowledge.places.taj.title',
              emoji: '🕌',
              isCorrect: true,
            },
            {
              id: 'tj2',
              labelKey: 'generalKnowledge.places.eiffel.title',
              emoji: '🗼',
              isCorrect: false,
            },
            {
              id: 'tj3',
              labelKey: 'generalKnowledge.places.statue.title',
              emoji: '🗽',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-taj-1',
            questionKey: 'generalKnowledge.quiz.tajQ1',
            questionType: 'identify-object',
            promptEmoji: '🕌 🇮🇳',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.places.taj.title',
                icon: '🕌',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.colosseum.title',
                icon: '🏛️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tajExp1',
          },
          {
            id: 'q-taj-2',
            questionKey: 'generalKnowledge.quiz.tajQ2',
            questionType: 'fact-check',
            promptEmoji: '🤍 🏛️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.whiteMarbleIndia',
                icon: '🤍 🇮🇳',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.redBrickUSA',
                icon: '🧱',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.madeOfGlass',
                icon: '🪟',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tajExp2',
          },
          {
            id: 'q-taj-3',
            questionKey: 'generalKnowledge.quiz.tajQ3',
            questionType: 'match-purpose',
            promptEmoji: '🌟 🇮🇳',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.worldWonderAgra',
                icon: '🏛️ ✨',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.swimmingPool',
                icon: '🏊',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.trainStation',
                icon: '🚂',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tajExp3',
          },
        ],
      },
      {
        id: 'plc-statue',
        categoryId: 'places',
        orderIndex: 3,
        titleKey: 'generalKnowledge.places.statue.title',
        subtitleKey: 'generalKnowledge.places.statue.sub',
        emoji: '🗽',
        factKey: 'generalKnowledge.places.statue.fact',
        purposeKey: 'generalKnowledge.places.statue.purpose',
        accentColor: '#10B981',
        practice: {
          promptKey: 'generalKnowledge.practice.tapStatue',
          targetEmoji: '🗽',
          choices: [
            {
              id: 'st1',
              labelKey: 'generalKnowledge.places.statue.title',
              emoji: '🗽',
              isCorrect: true,
            },
            {
              id: 'st2',
              labelKey: 'generalKnowledge.places.taj.title',
              emoji: '🕌',
              isCorrect: false,
            },
            {
              id: 'st3',
              labelKey: 'generalKnowledge.places.eiffel.title',
              emoji: '🗼',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-stt-1',
            questionKey: 'generalKnowledge.quiz.sttQ1',
            questionType: 'identify-object',
            promptEmoji: '🗽 🇺🇸',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.places.statue.title',
                icon: '🗽',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.places.pyramids.title',
                icon: '🔺',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sttExp1',
          },
          {
            id: 'q-stt-2',
            questionKey: 'generalKnowledge.quiz.sttQ2',
            questionType: 'match-purpose',
            promptEmoji: '🗽 🔦',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.holdsTorchFreedom',
                icon: '🗽 🔥',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.holdsTennisRacket',
                icon: '🎾',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.holdsIceCream',
                icon: '🍦',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sttExp2',
          },
          {
            id: 'q-stt-3',
            questionKey: 'generalKnowledge.quiz.sttQ3',
            questionType: 'fact-check',
            promptEmoji: '🗽 🗽',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.greenishCopperColor',
                icon: '🗽 💚',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.pinkPlastic',
                icon: '🎀',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.brightPurple',
                icon: '🟣',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sttExp3',
          },
        ],
      },
    ],
  },

  // ─── 4. Nature & Environment ──────────────────────────────────────────────
  {
    id: 'nature',
    titleKey: 'generalKnowledge.categories.nature.title',
    subtitleKey: 'generalKnowledge.categories.nature.sub',
    emoji: '🌳',
    accentColor: '#10B981',
    badgeTag: 'Green Earth',
    lessons: [
      {
        id: 'nat-trees',
        categoryId: 'nature',
        orderIndex: 1,
        titleKey: 'generalKnowledge.nature.trees.title',
        subtitleKey: 'generalKnowledge.nature.trees.sub',
        emoji: '🌳',
        factKey: 'generalKnowledge.nature.trees.fact',
        purposeKey: 'generalKnowledge.nature.trees.purpose',
        accentColor: '#10B981',
        practice: {
          promptKey: 'generalKnowledge.practice.tapTree',
          targetEmoji: '🌳',
          choices: [
            {
              id: 'tr1',
              labelKey: 'generalKnowledge.nature.trees.title',
              emoji: '🌳',
              isCorrect: true,
            },
            {
              id: 'tr2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'tr3',
              labelKey: 'generalKnowledge.vehicles.airplane.title',
              emoji: '✈️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-tre-1',
            questionKey: 'generalKnowledge.quiz.treQ1',
            questionType: 'identify-object',
            promptEmoji: '🌳 🍃',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.nature.trees.title',
                icon: '🌳',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.car.title',
                icon: '🚗',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.treExp1',
          },
          {
            id: 'q-tre-2',
            questionKey: 'generalKnowledge.quiz.treQ2',
            questionType: 'match-purpose',
            promptEmoji: '🌬️ 🍃',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.givesFreshAirOxygen',
                icon: '🍃 💨',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.makesPlastic',
                icon: '🥤',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.heatsTheGround',
                icon: '🔥',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.treExp2',
          },
          {
            id: 'q-tre-3',
            questionKey: 'generalKnowledge.quiz.treQ3',
            questionType: 'fact-check',
            promptEmoji: '🐦 🌳',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.birdsBuildNestsInTrees',
                icon: '🐦 🪺',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.fishBuildNestsInTrees',
                icon: '🐟',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.carsGrowOnTrees',
                icon: '🚗',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.treExp3',
          },
        ],
      },
      {
        id: 'nat-rainbow',
        categoryId: 'nature',
        orderIndex: 2,
        titleKey: 'generalKnowledge.nature.rainbow.title',
        subtitleKey: 'generalKnowledge.nature.rainbow.sub',
        emoji: '🌈',
        factKey: 'generalKnowledge.nature.rainbow.fact',
        purposeKey: 'generalKnowledge.nature.rainbow.purpose',
        accentColor: '#EC4899',
        practice: {
          promptKey: 'generalKnowledge.practice.tapRainbow',
          targetEmoji: '🌈',
          choices: [
            {
              id: 'rb1',
              labelKey: 'generalKnowledge.nature.rainbow.title',
              emoji: '🌈',
              isCorrect: true,
            },
            {
              id: 'rb2',
              labelKey: 'generalKnowledge.nature.trees.title',
              emoji: '🌳',
              isCorrect: false,
            },
            {
              id: 'rb3',
              labelKey: 'generalKnowledge.vehicles.ship.title',
              emoji: '🚢',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-rnb-1',
            questionKey: 'generalKnowledge.quiz.rnbQ1',
            questionType: 'identify-object',
            promptEmoji: '🌈 🌧️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.nature.rainbow.title',
                icon: '🌈',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.airplane.title',
                icon: '✈️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.taj.title',
                icon: '🕌',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnbExp1',
          },
          {
            id: 'q-rnb-2',
            questionKey: 'generalKnowledge.quiz.rnbQ2',
            questionType: 'match-purpose',
            promptEmoji: '☀️ 🌧️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.sunlightAndRaindrops',
                icon: '☀️ 💧 🌈',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.paintedByRobots',
                icon: '🤖',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.onlyAtMidnight',
                icon: '🌙',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnbExp2',
          },
          {
            id: 'q-rnb-3',
            questionKey: 'generalKnowledge.quiz.rnbQ3',
            questionType: 'fact-check',
            promptEmoji: '🎨 7️⃣',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.sevenBeautifulColors',
                icon: '🌈 7️⃣',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.onlyOneBlackColor',
                icon: '⬛',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.noColorsAtAll',
                icon: '⚪',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnbExp3',
          },
        ],
      },
      {
        id: 'nat-recycling',
        categoryId: 'nature',
        orderIndex: 3,
        titleKey: 'generalKnowledge.nature.recycling.title',
        subtitleKey: 'generalKnowledge.nature.recycling.sub',
        emoji: '♻️',
        factKey: 'generalKnowledge.nature.recycling.fact',
        purposeKey: 'generalKnowledge.nature.recycling.purpose',
        accentColor: '#10B981',
        practice: {
          promptKey: 'generalKnowledge.practice.tapRecycling',
          targetEmoji: '♻️',
          choices: [
            {
              id: 'rc1',
              labelKey: 'generalKnowledge.nature.recycling.title',
              emoji: '♻️',
              isCorrect: true,
            },
            {
              id: 'rc2',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
            {
              id: 'rc3',
              labelKey: 'generalKnowledge.nature.trees.title',
              emoji: '🌳',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-rec-1',
            questionKey: 'generalKnowledge.quiz.recQ1',
            questionType: 'identify-object',
            promptEmoji: '♻️ 🗑️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.nature.recycling.title',
                icon: '♻️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.vehicles.ship.title',
                icon: '🚢',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.statue.title',
                icon: '🗽',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.recExp1',
          },
          {
            id: 'q-rec-2',
            questionKey: 'generalKnowledge.quiz.recQ2',
            questionType: 'match-purpose',
            promptEmoji: '🌍 ♻️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.turnsOldIntoNewThings',
                icon: '♻️ 🌟',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.throwsTrashInRiver',
                icon: '🌊 👎',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.burnsPlastic',
                icon: '🔥 👎',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.recExp2',
          },
          {
            id: 'q-rec-3',
            questionKey: 'generalKnowledge.quiz.recQ3',
            questionType: 'scenario',
            promptEmoji: '📦 🗞️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.putPaperInRecycleBin',
                icon: '♻️ 📦',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.dropOnStreet',
                icon: '🚯',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.hideUnderBed',
                icon: '🛏️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.recExp3',
          },
        ],
      },
    ],
  },

  // ─── 5. Festivals & Celebrations ──────────────────────────────────────────
  {
    id: 'festivals',
    titleKey: 'generalKnowledge.categories.festivals.title',
    subtitleKey: 'generalKnowledge.categories.festivals.sub',
    emoji: '🎉',
    accentColor: '#F59E0B',
    badgeTag: 'Traditions & Joy',
    lessons: [
      {
        id: 'fst-diwali',
        categoryId: 'festivals',
        orderIndex: 1,
        titleKey: 'generalKnowledge.festivals.diwali.title',
        subtitleKey: 'generalKnowledge.festivals.diwali.sub',
        emoji: '🪔',
        factKey: 'generalKnowledge.festivals.diwali.fact',
        purposeKey: 'generalKnowledge.festivals.diwali.purpose',
        accentColor: '#F59E0B',
        practice: {
          promptKey: 'generalKnowledge.practice.tapDiwali',
          targetEmoji: '🪔',
          choices: [
            {
              id: 'dw1',
              labelKey: 'generalKnowledge.festivals.diwali.title',
              emoji: '🪔',
              isCorrect: true,
            },
            {
              id: 'dw2',
              labelKey: 'generalKnowledge.festivals.christmas.title',
              emoji: '🎄',
              isCorrect: false,
            },
            {
              id: 'dw3',
              labelKey: 'generalKnowledge.festivals.eid.title',
              emoji: '🌙',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-diw-1',
            questionKey: 'generalKnowledge.quiz.diwQ1',
            questionType: 'identify-object',
            promptEmoji: '🪔 ✨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.festivals.diwali.title',
                icon: '🪔',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.festivals.christmas.title',
                icon: '🎄',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.car.title',
                icon: '🚗',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.diwExp1',
          },
          {
            id: 'q-diw-2',
            questionKey: 'generalKnowledge.quiz.diwQ2',
            questionType: 'match-purpose',
            promptEmoji: '🪔 🪔',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.festivalOfLights',
                icon: '🪔 🌟',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.sleepingFestival',
                icon: '😴',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.swimmingRace',
                icon: '🏊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.diwExp2',
          },
          {
            id: 'q-diw-3',
            questionKey: 'generalKnowledge.quiz.diwQ3',
            questionType: 'fact-check',
            promptEmoji: '🪔 🍬',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.lightingDiyasAndSweets',
                icon: '🪔 🍬',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.makingSnowmen',
                icon: '⛄',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.wearingRaincoats',
                icon: '🧥',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.diwExp3',
          },
        ],
      },
      {
        id: 'fst-christmas',
        categoryId: 'festivals',
        orderIndex: 2,
        titleKey: 'generalKnowledge.festivals.christmas.title',
        subtitleKey: 'generalKnowledge.festivals.christmas.sub',
        emoji: '🎄',
        factKey: 'generalKnowledge.festivals.christmas.fact',
        purposeKey: 'generalKnowledge.festivals.christmas.purpose',
        accentColor: '#EF4444',
        practice: {
          promptKey: 'generalKnowledge.practice.tapChristmas',
          targetEmoji: '🎄',
          choices: [
            {
              id: 'ch1',
              labelKey: 'generalKnowledge.festivals.christmas.title',
              emoji: '🎄',
              isCorrect: true,
            },
            {
              id: 'ch2',
              labelKey: 'generalKnowledge.festivals.diwali.title',
              emoji: '🪔',
              isCorrect: false,
            },
            {
              id: 'ch3',
              labelKey: 'generalKnowledge.festivals.eid.title',
              emoji: '🌙',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-chm-1',
            questionKey: 'generalKnowledge.quiz.chmQ1',
            questionType: 'identify-object',
            promptEmoji: '🎄 🎅',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.festivals.christmas.title',
                icon: '🎄',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.festivals.diwali.title',
                icon: '🪔',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chmExp1',
          },
          {
            id: 'q-chm-2',
            questionKey: 'generalKnowledge.quiz.chmQ2',
            questionType: 'match-purpose',
            promptEmoji: '🎄 🎁',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.decoratedTreeAndGifts',
                icon: '🎄 🎁',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.flyingKites',
                icon: '🪁',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.playingWithMud',
                icon: '泥',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chmExp2',
          },
          {
            id: 'q-chm-3',
            questionKey: 'generalKnowledge.quiz.chmQ3',
            questionType: 'fact-check',
            promptEmoji: '🔔 ⭐',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.celebratedInDecember',
                icon: '📅 ❄️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.celebratedInMidSummer',
                icon: '☀️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.celebratedUnderOcean',
                icon: '🌊',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.chmExp3',
          },
        ],
      },
    ],
  },

  // ─── 6. Everyday Objects ──────────────────────────────────────────────────
  {
    id: 'objects',
    titleKey: 'generalKnowledge.categories.objects.title',
    subtitleKey: 'generalKnowledge.categories.objects.sub',
    emoji: '🔍',
    accentColor: '#3B82F6',
    badgeTag: 'Things We Use',
    lessons: [
      {
        id: 'obj-toothbrush',
        categoryId: 'objects',
        orderIndex: 1,
        titleKey: 'generalKnowledge.objects.toothbrush.title',
        subtitleKey: 'generalKnowledge.objects.toothbrush.sub',
        emoji: '🪥',
        factKey: 'generalKnowledge.objects.toothbrush.fact',
        purposeKey: 'generalKnowledge.objects.toothbrush.purpose',
        accentColor: '#0EA5E9',
        practice: {
          promptKey: 'generalKnowledge.practice.tapToothbrush',
          targetEmoji: '🪥',
          choices: [
            {
              id: 'tb1',
              labelKey: 'generalKnowledge.objects.toothbrush.title',
              emoji: '🪥',
              isCorrect: true,
            },
            {
              id: 'tb2',
              labelKey: 'generalKnowledge.objects.pencil.title',
              emoji: '✏️',
              isCorrect: false,
            },
            {
              id: 'tb3',
              labelKey: 'generalKnowledge.objects.umbrella.title',
              emoji: '☂️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-tb-1',
            questionKey: 'generalKnowledge.quiz.tbQ1',
            questionType: 'identify-object',
            promptEmoji: '🪥 ✨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.objects.toothbrush.title',
                icon: '🪥',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.objects.pencil.title',
                icon: '✏️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.car.title',
                icon: '🚗',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tbExp1',
          },
          {
            id: 'q-tb-2',
            questionKey: 'generalKnowledge.quiz.tbQ2',
            questionType: 'match-purpose',
            promptEmoji: '🦷 🪥',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.cleansOurTeeth',
                icon: '🦷 ✨',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.drawsOnPaper',
                icon: '📝',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.cutsApples',
                icon: '🍎',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tbExp2',
          },
          {
            id: 'q-tb-3',
            questionKey: 'generalKnowledge.quiz.tbQ3',
            questionType: 'scenario',
            promptEmoji: '🚿 🪥',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.useToothpasteWithIt',
                icon: '🪥 🧼',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.usePaintWithIt',
                icon: '🎨',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.useSyrupWithIt',
                icon: '🍯',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.tbExp3',
          },
        ],
      },
      {
        id: 'obj-pencil',
        categoryId: 'objects',
        orderIndex: 2,
        titleKey: 'generalKnowledge.objects.pencil.title',
        subtitleKey: 'generalKnowledge.objects.pencil.sub',
        emoji: '✏️',
        factKey: 'generalKnowledge.objects.pencil.fact',
        purposeKey: 'generalKnowledge.objects.pencil.purpose',
        accentColor: '#F59E0B',
        practice: {
          promptKey: 'generalKnowledge.practice.tapPencil',
          targetEmoji: '✏️',
          choices: [
            {
              id: 'pn1',
              labelKey: 'generalKnowledge.objects.pencil.title',
              emoji: '✏️',
              isCorrect: true,
            },
            {
              id: 'pn2',
              labelKey: 'generalKnowledge.objects.toothbrush.title',
              emoji: '🪥',
              isCorrect: false,
            },
            {
              id: 'pn3',
              labelKey: 'generalKnowledge.vehicles.car.title',
              emoji: '🚗',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-pnc-1',
            questionKey: 'generalKnowledge.quiz.pncQ1',
            questionType: 'identify-object',
            promptEmoji: '✏️ 📝',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.objects.pencil.title',
                icon: '✏️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.objects.umbrella.title',
                icon: '☂️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.vehicles.bus.title',
                icon: '🚌',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.pncExp1',
          },
          {
            id: 'q-pnc-2',
            questionKey: 'generalKnowledge.quiz.pncQ2',
            questionType: 'match-purpose',
            promptEmoji: '📝 🎨',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.writingAndDrawing',
                icon: '✏️ 📝',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.eatingSoup',
                icon: '🥣',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.ridingToSchool',
                icon: '🚲',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.pncExp2',
          },
          {
            id: 'q-pnc-3',
            questionKey: 'generalKnowledge.quiz.pncQ3',
            questionType: 'fact-check',
            promptEmoji: '✏️ 🧽',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.erasedWithEraser',
                icon: '🧽 ✏️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.erasedWithWater',
                icon: '💧',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.cannotBeErased',
                icon: '🚫',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.pncExp3',
          },
        ],
      },
    ],
  },

  // ─── 7. Weather & Oceans ──────────────────────────────────────────────────
  {
    id: 'weatherOceans',
    titleKey: 'generalKnowledge.categories.weather.title',
    subtitleKey: 'generalKnowledge.categories.weather.sub',
    emoji: '🌦️',
    accentColor: '#0284C7',
    badgeTag: 'Sky & Seas',
    lessons: [
      {
        id: 'wth-sunny',
        categoryId: 'weatherOceans',
        orderIndex: 1,
        titleKey: 'generalKnowledge.weather.sunny.title',
        subtitleKey: 'generalKnowledge.weather.sunny.sub',
        emoji: '☀️',
        factKey: 'generalKnowledge.weather.sunny.fact',
        purposeKey: 'generalKnowledge.weather.sunny.purpose',
        accentColor: '#F59E0B',
        practice: {
          promptKey: 'generalKnowledge.practice.tapSun',
          targetEmoji: '☀️',
          choices: [
            {
              id: 'sn1',
              labelKey: 'generalKnowledge.weather.sunny.title',
              emoji: '☀️',
              isCorrect: true,
            },
            {
              id: 'sn2',
              labelKey: 'generalKnowledge.weather.rainy.title',
              emoji: '🌧️',
              isCorrect: false,
            },
            {
              id: 'sn3',
              labelKey: 'generalKnowledge.weather.snowy.title',
              emoji: '❄️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-sun-1',
            questionKey: 'generalKnowledge.quiz.sunQ1',
            questionType: 'identify-object',
            promptEmoji: '☀️ 🕶️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.weather.sunny.title',
                icon: '☀️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.weather.rainy.title',
                icon: '🌧️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.weather.snowy.title',
                icon: '❄️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sunExp1',
          },
          {
            id: 'q-sun-2',
            questionKey: 'generalKnowledge.quiz.sunQ2',
            questionType: 'match-purpose',
            promptEmoji: '☀️ 🌳',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.givesLightAndWarmth',
                icon: '☀️ 💛',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.makesThingsFreeze',
                icon: '🧊',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.fillsPuddles',
                icon: '🌧️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sunExp2',
          },
          {
            id: 'q-sun-3',
            questionKey: 'generalKnowledge.quiz.sunQ3',
            questionType: 'scenario',
            promptEmoji: '☀️ 🧢',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.wearHatAndSunglasses',
                icon: '🧢 🕶️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.wearHeavySnowcoat',
                icon: '🧥 ❄️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.carrySnowShovel',
                icon: '⛏️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.sunExp3',
          },
        ],
      },
      {
        id: 'wth-rainy',
        categoryId: 'weatherOceans',
        orderIndex: 2,
        titleKey: 'generalKnowledge.weather.rainy.title',
        subtitleKey: 'generalKnowledge.weather.rainy.sub',
        emoji: '🌧️',
        factKey: 'generalKnowledge.weather.rainy.fact',
        purposeKey: 'generalKnowledge.weather.rainy.purpose',
        accentColor: '#3B82F6',
        practice: {
          promptKey: 'generalKnowledge.practice.tapRain',
          targetEmoji: '🌧️',
          choices: [
            {
              id: 'rn1',
              labelKey: 'generalKnowledge.weather.rainy.title',
              emoji: '🌧️',
              isCorrect: true,
            },
            {
              id: 'rn2',
              labelKey: 'generalKnowledge.weather.sunny.title',
              emoji: '☀️',
              isCorrect: false,
            },
            {
              id: 'rn3',
              labelKey: 'generalKnowledge.weather.snowy.title',
              emoji: '❄️',
              isCorrect: false,
            },
          ],
        },
        quizQuestions: [
          {
            id: 'q-rn-1',
            questionKey: 'generalKnowledge.quiz.rnQ1',
            questionType: 'identify-object',
            promptEmoji: '🌧️ 💧',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.weather.rainy.title',
                icon: '🌧️',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.weather.sunny.title',
                icon: '☀️',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.places.eiffel.title',
                icon: '🗼',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnExp1',
          },
          {
            id: 'q-rn-2',
            questionKey: 'generalKnowledge.quiz.rnQ2',
            questionType: 'scenario',
            promptEmoji: '🌧️ ☂️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.carryUmbrellaRaincoat',
                icon: '☂️ 🧥',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.carryWaterGun',
                icon: '🔫',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.wearPaperHat',
                icon: '📄',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnExp2',
          },
          {
            id: 'q-rn-3',
            questionKey: 'generalKnowledge.quiz.rnQ3',
            questionType: 'match-purpose',
            promptEmoji: '🌱 🌧️',
            options: [
              {
                id: 'o1',
                textKey: 'generalKnowledge.quiz.helpsPlantsGrow',
                icon: '🌱 💧',
                isCorrect: true,
              },
              {
                id: 'o2',
                textKey: 'generalKnowledge.quiz.driesClothes',
                icon: '👕',
                isCorrect: false,
              },
              {
                id: 'o3',
                textKey: 'generalKnowledge.quiz.turnsNightToDay',
                icon: '☀️',
                isCorrect: false,
              },
            ],
            explanationKey: 'generalKnowledge.quiz.rnExp3',
          },
        ],
      },
    ],
  },
];

// ─── Grand GK Challenge Questions ───────────────────────────────────────────
export const GRAND_GK_CHALLENGE_QUESTIONS: readonly GKLessonQuestion[] = [
  {
    id: 'gkc-1',
    questionKey: 'generalKnowledge.challenge.q1',
    questionType: 'identify-object',
    promptEmoji: '🚒 🔥',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.vehicles.fireTruck.title',
        icon: '🚒',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.vehicles.bus.title',
        icon: '🚌',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.vehicles.ship.title',
        icon: '🚢',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp1',
  },
  {
    id: 'gkc-2',
    questionKey: 'generalKnowledge.challenge.q2',
    questionType: 'match-job',
    promptEmoji: '🩺 🏥',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.occupations.doctor.title',
        icon: '👨‍⚕️',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.occupations.chef.title',
        icon: '👩‍🍳',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.occupations.pilot.title',
        icon: '✈️',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp2',
  },
  {
    id: 'gkc-3',
    questionKey: 'generalKnowledge.challenge.q3',
    questionType: 'identify-object',
    promptEmoji: '🗼 🇫🇷',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.places.eiffel.title',
        icon: '🗼',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.places.taj.title',
        icon: '🕌',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.places.statue.title',
        icon: '🗽',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp3',
  },
  {
    id: 'gkc-4',
    questionKey: 'generalKnowledge.challenge.q4',
    questionType: 'fact-check',
    promptEmoji: '🌳 🌬️',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.quiz.givesFreshAirOxygen',
        icon: '🍃 💨',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.quiz.makesPlastic',
        icon: '🥤',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.quiz.heatsTheGround',
        icon: '🔥',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp4',
  },
  {
    id: 'gkc-5',
    questionKey: 'generalKnowledge.challenge.q5',
    questionType: 'identify-object',
    promptEmoji: '🪔 ✨',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.festivals.diwali.title',
        icon: '🪔',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.festivals.christmas.title',
        icon: '🎄',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.vehicles.car.title',
        icon: '🚗',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp5',
  },
  {
    id: 'gkc-6',
    questionKey: 'generalKnowledge.challenge.q6',
    questionType: 'match-purpose',
    promptEmoji: '🦷 🪥',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.objects.toothbrush.title',
        icon: '🪥',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.objects.pencil.title',
        icon: '✏️',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.vehicles.train.title',
        icon: '🚂',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp6',
  },
  {
    id: 'gkc-7',
    questionKey: 'generalKnowledge.challenge.q7',
    questionType: 'match-purpose',
    promptEmoji: '✈️ ☁️',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.occupations.pilot.title',
        icon: '👨‍✈️',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.occupations.teacher.title',
        icon: '👩‍🏫',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.occupations.farmer.title',
        icon: '👨‍🌾',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp7',
  },
  {
    id: 'gkc-8',
    questionKey: 'generalKnowledge.challenge.q8',
    questionType: 'identify-object',
    promptEmoji: '🕌 🇮🇳',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.places.taj.title',
        icon: '🕌',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.places.eiffel.title',
        icon: '🗼',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.places.statue.title',
        icon: '🗽',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp8',
  },
  {
    id: 'gkc-9',
    questionKey: 'generalKnowledge.challenge.q9',
    questionType: 'scenario',
    promptEmoji: '🌧️ 💧',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.quiz.carryUmbrellaRaincoat',
        icon: '☂️ 🧥',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.quiz.wearPaperHat',
        icon: '📄',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.quiz.carryWaterGun',
        icon: '🔫',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp9',
  },
  {
    id: 'gkc-10',
    questionKey: 'generalKnowledge.challenge.q10',
    questionType: 'match-purpose',
    promptEmoji: '♻️ 🌍',
    options: [
      {
        id: 'o1',
        textKey: 'generalKnowledge.quiz.turnsOldIntoNewThings',
        icon: '♻️ 🌟',
        isCorrect: true,
      },
      {
        id: 'o2',
        textKey: 'generalKnowledge.quiz.throwsTrashInRiver',
        icon: '🌊',
        isCorrect: false,
      },
      {
        id: 'o3',
        textKey: 'generalKnowledge.quiz.burnsPlastic',
        icon: '🔥',
        isCorrect: false,
      },
    ],
    explanationKey: 'generalKnowledge.challenge.exp10',
  },
];
