export {
  screenBackground,
  splashLionLoading,
  welcomeMathIcon,
  welcomeEnglishIcon,
  welcomeChessIcon,
  welcomeRewardsIcon,
  avatarLion,
  avatarPanda,
  avatarRabbit,
  avatarTiger,
  avatarMonkey,
  avatarKoala,
  avatarPenguin,
  avatarFox,
  avatarElephant,
  avatarOwl,
  CHILD_AVATARS,
  getChildAvatar,
  type ChildAvatarId,
  type ChildAvatarDef,
} from './images';
