export {
  screenBackground,
  splashLionLoading,
  welcomeMathIcon,
  welcomeEnglishIcon,
  welcomeChessIcon,
  welcomeRewardsIcon,
  homeChessIcon,
  homeMathIcon,
  homeEnglishIcon,
  homeColorsIcon,
  homeShapesIcon,
  homeRhymesIcon,
  homeStoryIcon,
  homePhonicsIcon,
  homeMascotLion,
  backArrowIcon,
  leoWave,
  leoThumbsUp,
  leoCelebrate,
  leoThinking,
  mathTopicAddition,
  mathTopicCounting,
  mathTopicOrdering,
  mathTopicTime,
  mathTopicMoney,
  chessBoard,
  chessKing,
  chessQueen,
  chessKnight,
  chessBishop,
  chessPawn,
  chessRook,
  avatarLion,
  avatarPanda,
  avatarRabbit,
  avatarTiger,
  avatarMonkey,
  avatarKoala,
  avatarPenguin,
  avatarFox,
  avatarElephant,
  avatarOwl,
  CHILD_AVATARS,
  getChildAvatar,
  type ChildAvatarId,
  type ChildAvatarDef,
} from './images';
