import type {
  PhonicsCvcWordItem,
  PhonicsExerciseQuestion,
  PhonicsLetterItem,
  PhonicsSentenceItem,
  PhonicsSubModule,
  PhonicsTransformItem,
  PhonicsWordFamilyItem,
} from '../entities/phonicsEntities';

export const PHONICS_SUBMODULES: readonly PhonicsSubModule[] = [
  {
    id: 'letter_sounds',
    titleKey: 'phonics.submodules.letterSounds',
    subtitleKey: 'phonics.submodules.letterSoundsSub',
    icon: '🔤',
    color: '#3B82F6',
    order: 1,
    questionsCount: 5,
  },
  {
    id: 'sound_recognition',
    titleKey: 'phonics.submodules.soundRecognition',
    subtitleKey: 'phonics.submodules.soundRecognitionSub',
    icon: '👂',
    color: '#10B981',
    order: 2,
    questionsCount: 5,
  },
  {
    id: 'letter_matching',
    titleKey: 'phonics.submodules.letterMatching',
    subtitleKey: 'phonics.submodules.letterMatchingSub',
    icon: '🔠',
    color: '#8B5CF6',
    order: 3,
    questionsCount: 5,
  },
  {
    id: 'beginning_sounds',
    titleKey: 'phonics.submodules.beginningSounds',
    subtitleKey: 'phonics.submodules.beginningSoundsSub',
    icon: '🔊',
    color: '#F59E0B',
    order: 4,
    questionsCount: 5,
  },
  {
    id: 'ending_sounds',
    titleKey: 'phonics.submodules.endingSounds',
    subtitleKey: 'phonics.submodules.endingSoundsSub',
    icon: '🔚',
    color: '#EC4899',
    order: 5,
    questionsCount: 5,
  },
  {
    id: 'slow_blending',
    titleKey: 'phonics.submodules.slowBlending',
    subtitleKey: 'phonics.submodules.slowBlendingSub',
    icon: '🐢',
    color: '#06B6D4',
    order: 6,
    questionsCount: 5,
  },
  {
    id: 'cvc_words',
    titleKey: 'phonics.submodules.cvcWords',
    subtitleKey: 'phonics.submodules.cvcWordsSub',
    icon: '📖',
    color: '#10B981',
    order: 7,
    questionsCount: 5,
  },
  {
    id: 'word_builder',
    titleKey: 'phonics.submodules.wordBuilder',
    subtitleKey: 'phonics.submodules.wordBuilderSub',
    icon: '🧩',
    color: '#F97316',
    order: 8,
    questionsCount: 5,
  },
  {
    id: 'word_families',
    titleKey: 'phonics.submodules.wordFamilies',
    subtitleKey: 'phonics.submodules.wordFamiliesSub',
    icon: '🔄',
    color: '#6366F1',
    order: 9,
    questionsCount: 5,
  },
  {
    id: 'word_transform',
    titleKey: 'phonics.submodules.wordTransform',
    subtitleKey: 'phonics.submodules.wordTransformSub',
    icon: '✏️',
    color: '#EAB308',
    order: 10,
    questionsCount: 5,
  },
  {
    id: 'hear_choose_word',
    titleKey: 'phonics.submodules.hearChooseWord',
    subtitleKey: 'phonics.submodules.hearChooseWordSub',
    icon: '🎧',
    color: '#14B8A6',
    order: 11,
    questionsCount: 5,
  },
  {
    id: 'picture_to_word',
    titleKey: 'phonics.submodules.pictureToWord',
    subtitleKey: 'phonics.submodules.pictureToWordSub',
    icon: '🖼️',
    color: '#84CC16',
    order: 12,
    questionsCount: 5,
  },
  {
    id: 'read_words',
    titleKey: 'phonics.submodules.readWords',
    subtitleKey: 'phonics.submodules.readWordsSub',
    icon: '📚',
    color: '#A855F7',
    order: 13,
    questionsCount: 5,
  },
  {
    id: 'read_sentences',
    titleKey: 'phonics.submodules.readSentences',
    subtitleKey: 'phonics.submodules.readSentencesSub',
    icon: '📝',
    color: '#3B82F6',
    order: 14,
    questionsCount: 5,
  },
  {
    id: 'phonics_games',
    titleKey: 'phonics.submodules.phonicsGames',
    subtitleKey: 'phonics.submodules.phonicsGamesSub',
    icon: '🎮',
    color: '#F43F5E',
    order: 15,
    questionsCount: 6,
  },
  {
    id: 'phonics_challenge',
    titleKey: 'phonics.submodules.phonicsChallenge',
    subtitleKey: 'phonics.submodules.phonicsChallengeSub',
    icon: '🏆',
    color: '#D97706',
    order: 16,
    questionsCount: 8,
  },
];

// 26 Letters with phonics sounds & example objects
export const PHONICS_LETTERS: readonly PhonicsLetterItem[] = [
  {
    id: 'letter_a',
    letter: 'A',
    lowercase: 'a',
    soundSymbol: '/æ/',
    soundPronunciation: 'ah',
    exampleWord: 'Apple',
    exampleEmoji: '🍎',
    color: '#EF4444',
  },
  {
    id: 'letter_b',
    letter: 'B',
    lowercase: 'b',
    soundSymbol: '/b/',
    soundPronunciation: 'buh',
    exampleWord: 'Ball',
    exampleEmoji: '⚽',
    color: '#3B82F6',
  },
  {
    id: 'letter_c',
    letter: 'C',
    lowercase: 'c',
    soundSymbol: '/k/',
    soundPronunciation: 'kuh',
    exampleWord: 'Cat',
    exampleEmoji: '🐱',
    color: '#F59E0B',
  },
  {
    id: 'letter_d',
    letter: 'D',
    lowercase: 'd',
    soundSymbol: '/d/',
    soundPronunciation: 'duh',
    exampleWord: 'Dog',
    exampleEmoji: '🐶',
    color: '#10B981',
  },
  {
    id: 'letter_e',
    letter: 'E',
    lowercase: 'e',
    soundSymbol: '/e/',
    soundPronunciation: 'eh',
    exampleWord: 'Egg',
    exampleEmoji: '🥚',
    color: '#8B5CF6',
  },
  {
    id: 'letter_f',
    letter: 'F',
    lowercase: 'f',
    soundSymbol: '/f/',
    soundPronunciation: 'fff',
    exampleWord: 'Fish',
    exampleEmoji: '🐟',
    color: '#06B6D4',
  },
  {
    id: 'letter_g',
    letter: 'G',
    lowercase: 'g',
    soundSymbol: '/g/',
    soundPronunciation: 'guh',
    exampleWord: 'Goat',
    exampleEmoji: '🐐',
    color: '#84CC16',
  },
  {
    id: 'letter_h',
    letter: 'H',
    lowercase: 'h',
    soundSymbol: '/h/',
    soundPronunciation: 'huh',
    exampleWord: 'Hat',
    exampleEmoji: '🎩',
    color: '#EC4899',
  },
  {
    id: 'letter_i',
    letter: 'I',
    lowercase: 'i',
    soundSymbol: '/ɪ/',
    soundPronunciation: 'ih',
    exampleWord: 'Igloo',
    exampleEmoji: '🧊',
    color: '#6366F1',
  },
  {
    id: 'letter_j',
    letter: 'J',
    lowercase: 'j',
    soundSymbol: '/dʒ/',
    soundPronunciation: 'juh',
    exampleWord: 'Jar',
    exampleEmoji: '🏺',
    color: '#F97316',
  },
  {
    id: 'letter_k',
    letter: 'K',
    lowercase: 'k',
    soundSymbol: '/k/',
    soundPronunciation: 'kuh',
    exampleWord: 'Kite',
    exampleEmoji: '🪁',
    color: '#14B8A6',
  },
  {
    id: 'letter_l',
    letter: 'L',
    lowercase: 'l',
    soundSymbol: '/l/',
    soundPronunciation: 'lll',
    exampleWord: 'Lion',
    exampleEmoji: '🦁',
    color: '#EAB308',
  },
  {
    id: 'letter_m',
    letter: 'M',
    lowercase: 'm',
    soundSymbol: '/m/',
    soundPronunciation: 'mmm',
    exampleWord: 'Monkey',
    exampleEmoji: '🐒',
    color: '#A855F7',
  },
  {
    id: 'letter_n',
    letter: 'N',
    lowercase: 'n',
    soundSymbol: '/n/',
    soundPronunciation: 'nnn',
    exampleWord: 'Nest',
    exampleEmoji: '🪺',
    color: '#3B82F6',
  },
  {
    id: 'letter_o',
    letter: 'O',
    lowercase: 'o',
    soundSymbol: '/ɒ/',
    soundPronunciation: 'aw',
    exampleWord: 'Orange',
    exampleEmoji: '🍊',
    color: '#F97316',
  },
  {
    id: 'letter_p',
    letter: 'P',
    lowercase: 'p',
    soundSymbol: '/p/',
    soundPronunciation: 'puh',
    exampleWord: 'Pig',
    exampleEmoji: '🐷',
    color: '#EC4899',
  },
  {
    id: 'letter_q',
    letter: 'Q',
    lowercase: 'q',
    soundSymbol: '/kw/',
    soundPronunciation: 'kwuh',
    exampleWord: 'Queen',
    exampleEmoji: '👑',
    color: '#8B5CF6',
  },
  {
    id: 'letter_r',
    letter: 'R',
    lowercase: 'r',
    soundSymbol: '/r/',
    soundPronunciation: 'rrr',
    exampleWord: 'Rabbit',
    exampleEmoji: '🐰',
    color: '#EF4444',
  },
  {
    id: 'letter_s',
    letter: 'S',
    lowercase: 's',
    soundSymbol: '/s/',
    soundPronunciation: 'sss',
    exampleWord: 'Sun',
    exampleEmoji: '☀️',
    color: '#F59E0B',
  },
  {
    id: 'letter_t',
    letter: 'T',
    lowercase: 't',
    soundSymbol: '/t/',
    soundPronunciation: 'tuh',
    exampleWord: 'Tiger',
    exampleEmoji: '🐯',
    color: '#10B981',
  },
  {
    id: 'letter_u',
    letter: 'U',
    lowercase: 'u',
    soundSymbol: '/ʌ/',
    soundPronunciation: 'uh',
    exampleWord: 'Umbrella',
    exampleEmoji: '☂️',
    color: '#06B6D4',
  },
  {
    id: 'letter_v',
    letter: 'V',
    lowercase: 'v',
    soundSymbol: '/v/',
    soundPronunciation: 'vvv',
    exampleWord: 'Van',
    exampleEmoji: '🚐',
    color: '#84CC16',
  },
  {
    id: 'letter_w',
    letter: 'W',
    lowercase: 'w',
    soundSymbol: '/w/',
    soundPronunciation: 'wuh',
    exampleWord: 'Watch',
    exampleEmoji: '⌚',
    color: '#6366F1',
  },
  {
    id: 'letter_x',
    letter: 'X',
    lowercase: 'x',
    soundSymbol: '/ks/',
    soundPronunciation: 'ks',
    exampleWord: 'Xylophone',
    exampleEmoji: '🪵',
    color: '#EAB308',
  },
  {
    id: 'letter_y',
    letter: 'Y',
    lowercase: 'y',
    soundSymbol: '/j/',
    soundPronunciation: 'yuh',
    exampleWord: 'Yo-yo',
    exampleEmoji: '🪀',
    color: '#14B8A6',
  },
  {
    id: 'letter_z',
    letter: 'Z',
    lowercase: 'z',
    soundSymbol: '/z/',
    soundPronunciation: 'zzz',
    exampleWord: 'Zebra',
    exampleEmoji: '🦓',
    color: '#1F2937',
  },
];

// CVC Words with phoneme breakdowns
export const CVC_WORDS_CATALOG: readonly PhonicsCvcWordItem[] = [
  // Short 'a'
  {
    id: 'cvc_cat',
    word: 'CAT',
    letters: ['C', 'A', 'T'],
    sounds: ['kuh', 'ah', 'tuh'],
    soundSymbols: ['/k/', '/æ/', '/t/'],
    emoji: '🐱',
    vowelGroup: 'a',
    sentence: 'The cat sat on the mat.',
  },
  {
    id: 'cvc_bat',
    word: 'BAT',
    letters: ['B', 'A', 'T'],
    sounds: ['buh', 'ah', 'tuh'],
    soundSymbols: ['/b/', '/æ/', '/t/'],
    emoji: '🦇',
    vowelGroup: 'a',
    sentence: 'A bat can fly high.',
  },
  {
    id: 'cvc_mat',
    word: 'MAT',
    letters: ['M', 'A', 'T'],
    sounds: ['mmm', 'ah', 'tuh'],
    soundSymbols: ['/m/', '/æ/', '/t/'],
    emoji: '🧘',
    vowelGroup: 'a',
    sentence: 'Sit on the green mat.',
  },
  {
    id: 'cvc_hat',
    word: 'HAT',
    letters: ['H', 'A', 'T'],
    sounds: ['huh', 'ah', 'tuh'],
    soundSymbols: ['/h/', '/æ/', '/t/'],
    emoji: '🎩',
    vowelGroup: 'a',
    sentence: 'He has a red hat.',
  },
  {
    id: 'cvc_can',
    word: 'CAN',
    letters: ['C', 'A', 'N'],
    sounds: ['kuh', 'ah', 'nnn'],
    soundSymbols: ['/k/', '/æ/', '/n/'],
    emoji: '🥫',
    vowelGroup: 'a',
    sentence: 'I can see the sun.',
  },
  {
    id: 'cvc_pan',
    word: 'PAN',
    letters: ['P', 'A', 'N'],
    sounds: ['puh', 'ah', 'nnn'],
    soundSymbols: ['/p/', '/æ/', '/n/'],
    emoji: '🍳',
    vowelGroup: 'a',
    sentence: 'Cook eggs in the pan.',
  },
  {
    id: 'cvc_map',
    word: 'MAP',
    letters: ['M', 'A', 'P'],
    sounds: ['mmm', 'ah', 'puh'],
    soundSymbols: ['/m/', '/æ/', '/p/'],
    emoji: '🗺️',
    vowelGroup: 'a',
    sentence: 'Follow the treasure map.',
  },
  {
    id: 'cvc_cap',
    word: 'CAP',
    letters: ['C', 'A', 'P'],
    sounds: ['kuh', 'ah', 'puh'],
    soundSymbols: ['/k/', '/æ/', '/p/'],
    emoji: '🧢',
    vowelGroup: 'a',
    sentence: 'Put on your blue cap.',
  },

  // Short 'e'
  {
    id: 'cvc_bed',
    word: 'BED',
    letters: ['B', 'E', 'D'],
    sounds: ['buh', 'eh', 'duh'],
    soundSymbols: ['/b/', '/e/', '/d/'],
    emoji: '🛏️',
    vowelGroup: 'e',
    sentence: 'Sleep in the cozy bed.',
  },
  {
    id: 'cvc_red',
    word: 'RED',
    letters: ['R', 'E', 'D'],
    sounds: ['rrr', 'eh', 'duh'],
    soundSymbols: ['/r/', '/e/', '/d/'],
    emoji: '🔴',
    vowelGroup: 'e',
    sentence: 'The apple is bright red.',
  },
  {
    id: 'cvc_pen',
    word: 'PEN',
    letters: ['P', 'E', 'N'],
    sounds: ['puh', 'eh', 'nnn'],
    soundSymbols: ['/p/', '/e/', '/n/'],
    emoji: '🖊️',
    vowelGroup: 'e',
    sentence: 'Write with a shiny pen.',
  },
  {
    id: 'cvc_hen',
    word: 'HEN',
    letters: ['H', 'E', 'N'],
    sounds: ['huh', 'eh', 'nnn'],
    soundSymbols: ['/h/', '/e/', '/n/'],
    emoji: '🐔',
    vowelGroup: 'e',
    sentence: 'The hen laid an egg.',
  },
  {
    id: 'cvc_net',
    word: 'NET',
    letters: ['N', 'E', 'T'],
    sounds: ['nnn', 'eh', 'tuh'],
    soundSymbols: ['/n/', '/e/', '/t/'],
    emoji: '🥅',
    vowelGroup: 'e',
    sentence: 'Catch the ball in the net.',
  },

  // Short 'i'
  {
    id: 'cvc_pig',
    word: 'PIG',
    letters: ['P', 'I', 'G'],
    sounds: ['puh', 'ih', 'guh'],
    soundSymbols: ['/p/', '/ɪ/', '/g/'],
    emoji: '🐷',
    vowelGroup: 'i',
    sentence: 'The pink pig is cute.',
  },
  {
    id: 'cvc_dig',
    word: 'DIG',
    letters: ['D', 'I', 'G'],
    sounds: ['duh', 'ih', 'guh'],
    soundSymbols: ['/d/', '/ɪ/', '/g/'],
    emoji: '⛏️',
    vowelGroup: 'i',
    sentence: 'Dogs like to dig holes.',
  },
  {
    id: 'cvc_pin',
    word: 'PIN',
    letters: ['P', 'I', 'N'],
    sounds: ['puh', 'ih', 'nnn'],
    soundSymbols: ['/p/', '/ɪ/', '/n/'],
    emoji: '📍',
    vowelGroup: 'i',
    sentence: 'Push the red pin in.',
  },
  {
    id: 'cvc_win',
    word: 'WIN',
    letters: ['W', 'I', 'N'],
    sounds: ['wuh', 'ih', 'nnn'],
    soundSymbols: ['/w/', '/ɪ/', '/n/'],
    emoji: '🏆',
    vowelGroup: 'i',
    sentence: 'You can win the gold cup.',
  },
  {
    id: 'cvc_sit',
    word: 'SIT',
    letters: ['S', 'I', 'T'],
    sounds: ['sss', 'ih', 'tuh'],
    soundSymbols: ['/s/', '/ɪ/', '/t/'],
    emoji: '🪑',
    vowelGroup: 'i',
    sentence: 'Please sit on the chair.',
  },

  // Short 'o'
  {
    id: 'cvc_dog',
    word: 'DOG',
    letters: ['D', 'O', 'G'],
    sounds: ['duh', 'aw', 'guh'],
    soundSymbols: ['/d/', '/ɒ/', '/g/'],
    emoji: '🐶',
    vowelGroup: 'o',
    sentence: 'The happy dog ran fast.',
  },
  {
    id: 'cvc_log',
    word: 'LOG',
    letters: ['L', 'O', 'G'],
    sounds: ['lll', 'aw', 'guh'],
    soundSymbols: ['/l/', '/ɒ/', '/g/'],
    emoji: '🪵',
    vowelGroup: 'o',
    sentence: 'A frog sat on a log.',
  },
  {
    id: 'cvc_fox',
    word: 'FOX',
    letters: ['F', 'O', 'X'],
    sounds: ['fff', 'aw', 'ks'],
    soundSymbols: ['/f/', '/ɒ/', '/ks/'],
    emoji: '🦊',
    vowelGroup: 'o',
    sentence: 'The quick red fox jumped.',
  },
  {
    id: 'cvc_box',
    word: 'BOX',
    letters: ['B', 'O', 'X'],
    sounds: ['buh', 'aw', 'ks'],
    soundSymbols: ['/b/', '/ɒ/', '/ks/'],
    emoji: '📦',
    vowelGroup: 'o',
    sentence: 'Open the magic box.',
  },
  {
    id: 'cvc_pot',
    word: 'POT',
    letters: ['P', 'O', 'T'],
    sounds: ['puh', 'aw', 'tuh'],
    soundSymbols: ['/p/', '/ɒ/', '/t/'],
    emoji: '🍲',
    vowelGroup: 'o',
    sentence: 'Soup is hot in the pot.',
  },

  // Short 'u'
  {
    id: 'cvc_sun',
    word: 'SUN',
    letters: ['S', 'U', 'N'],
    sounds: ['sss', 'uh', 'nnn'],
    soundSymbols: ['/s/', '/ʌ/', '/n/'],
    emoji: '☀️',
    vowelGroup: 'u',
    sentence: 'The sun is bright and warm.',
  },
  {
    id: 'cvc_run',
    word: 'RUN',
    letters: ['R', 'U', 'N'],
    sounds: ['rrr', 'uh', 'nnn'],
    soundSymbols: ['/r/', '/ʌ/', '/n/'],
    emoji: '🏃',
    vowelGroup: 'u',
    sentence: 'Run in the green park.',
  },
  {
    id: 'cvc_cup',
    word: 'CUP',
    letters: ['C', 'U', 'P'],
    sounds: ['kuh', 'uh', 'puh'],
    soundSymbols: ['/k/', '/ʌ/', '/p/'],
    emoji: '🥛',
    vowelGroup: 'u',
    sentence: 'Drink milk from a cup.',
  },
  {
    id: 'cvc_bus',
    word: 'BUS',
    letters: ['B', 'U', 'S'],
    sounds: ['buh', 'uh', 'sss'],
    soundSymbols: ['/b/', '/ʌ/', '/s/'],
    emoji: '🚌',
    vowelGroup: 'u',
    sentence: 'The yellow bus stops here.',
  },
  {
    id: 'cvc_bug',
    word: 'BUG',
    letters: ['B', 'U', 'G'],
    sounds: ['buh', 'uh', 'guh'],
    soundSymbols: ['/b/', '/ʌ/', '/g/'],
    emoji: '🐞',
    vowelGroup: 'u',
    sentence: 'A cute bug on a leaf.',
  },
  {
    id: 'cvc_mug',
    word: 'MUG',
    letters: ['M', 'U', 'G'],
    sounds: ['mmm', 'uh', 'guh'],
    soundSymbols: ['/m/', '/ʌ/', '/g/'],
    emoji: '☕',
    vowelGroup: 'u',
    sentence: 'Hot tea in my mug.',
  },
];

// 8 Word Families
export const WORD_FAMILIES_CATALOG: readonly PhonicsWordFamilyItem[] = [
  {
    id: 'fam_at',
    familyEnding: '-at',
    words: ['CAT', 'BAT', 'MAT', 'HAT', 'SAT'],
    emojis: ['🐱', '🦇', '🧘', '🎩', '🪑'],
    color: '#EF4444',
  },
  {
    id: 'fam_an',
    familyEnding: '-an',
    words: ['CAN', 'PAN', 'FAN', 'MAN', 'VAN'],
    emojis: ['🥫', '🍳', '🪭', '👨', '🚐'],
    color: '#3B82F6',
  },
  {
    id: 'fam_ap',
    familyEnding: '-ap',
    words: ['CAP', 'MAP', 'TAP', 'NAP'],
    emojis: ['🧢', '🗺️', '🚰', '😴'],
    color: '#F59E0B',
  },
  {
    id: 'fam_en',
    familyEnding: '-en',
    words: ['PEN', 'HEN', 'TEN', 'MEN'],
    emojis: ['🖊️', '🐔', '🔟', '👥'],
    color: '#10B981',
  },
  {
    id: 'fam_ig',
    familyEnding: '-ig',
    words: ['PIG', 'DIG', 'BIG', 'WIG'],
    emojis: ['🐷', '⛏️', '🐘', '💇'],
    color: '#8B5CF6',
  },
  {
    id: 'fam_ot',
    familyEnding: '-ot',
    words: ['POT', 'HOT', 'DOT', 'NOT'],
    emojis: ['🍲', '🔥', '🔴', '❌'],
    color: '#EC4899',
  },
  {
    id: 'fam_ug',
    familyEnding: '-ug',
    words: ['BUG', 'MUG', 'HUG', 'JUG'],
    emojis: ['🐞', '☕', '🤗', '🫗'],
    color: '#06B6D4',
  },
  {
    id: 'fam_un',
    familyEnding: '-un',
    words: ['SUN', 'RUN', 'FUN', 'BUN'],
    emojis: ['☀️', '🏃', '🎉', '🥖'],
    color: '#EAB308',
  },
];

// Sound Transformation Pairs ("Change One Sound")
export const WORD_TRANSFORMATIONS: readonly PhonicsTransformItem[] = [
  {
    id: 'trans_1',
    startWord: 'CAT',
    targetWord: 'BAT',
    changedPosition: 'first',
    newLetter: 'B',
    startEmoji: '🐱',
    targetEmoji: '🦇',
  },
  {
    id: 'trans_2',
    startWord: 'BAT',
    targetWord: 'HAT',
    changedPosition: 'first',
    newLetter: 'H',
    startEmoji: '🦇',
    targetEmoji: '🎩',
  },
  {
    id: 'trans_3',
    startWord: 'HAT',
    targetWord: 'MAT',
    changedPosition: 'first',
    newLetter: 'M',
    startEmoji: '🎩',
    targetEmoji: '🧘',
  },
  {
    id: 'trans_4',
    startWord: 'PIN',
    targetWord: 'WIN',
    changedPosition: 'first',
    newLetter: 'W',
    startEmoji: '📍',
    targetEmoji: '🏆',
  },
  {
    id: 'trans_5',
    startWord: 'SUN',
    targetWord: 'RUN',
    changedPosition: 'first',
    newLetter: 'R',
    startEmoji: '☀️',
    targetEmoji: '🏃',
  },
  {
    id: 'trans_6',
    startWord: 'BUG',
    targetWord: 'MUG',
    changedPosition: 'first',
    newLetter: 'M',
    startEmoji: '🐞',
    targetEmoji: '☕',
  },
];

// Decodable Sentences
export const PHONICS_SENTENCES: readonly PhonicsSentenceItem[] = [
  {
    id: 'sent_1',
    text: 'The cat sat.',
    words: ['The', 'cat', 'sat.'],
    emoji: '🐱',
    focusWord: 'cat',
  },
  {
    id: 'sent_2',
    text: 'The dog ran.',
    words: ['The', 'dog', 'ran.'],
    emoji: '🐶',
    focusWord: 'dog',
  },
  {
    id: 'sent_3',
    text: 'The sun is hot.',
    words: ['The', 'sun', 'is', 'hot.'],
    emoji: '☀️',
    focusWord: 'sun',
  },
  {
    id: 'sent_4',
    text: 'I see a pink pig.',
    words: ['I', 'see', 'a', 'pink', 'pig.'],
    emoji: '🐷',
    focusWord: 'pig',
  },
  {
    id: 'sent_5',
    text: 'Sam has a red hat.',
    words: ['Sam', 'has', 'a', 'red', 'hat.'],
    emoji: '🎩',
    focusWord: 'hat',
  },
  {
    id: 'sent_6',
    text: 'Drink milk in a cup.',
    words: ['Drink', 'milk', 'in', 'a', 'cup.'],
    emoji: '🥛',
    focusWord: 'cup',
  },
  {
    id: 'sent_7',
    text: 'The hen laid an egg.',
    words: ['The', 'hen', 'laid', 'an', 'egg.'],
    emoji: '🐔',
    focusWord: 'hen',
  },
  {
    id: 'sent_8',
    text: 'The yellow bus stops.',
    words: ['The', 'yellow', 'bus', 'stops.'],
    emoji: '🚌',
    focusWord: 'bus',
  },
];

// Curated Mini Exercises for Submodules
export const PHONICS_EXERCISES_MAP: Record<
  string,
  readonly PhonicsExerciseQuestion[]
> = {
  letter_sounds: [
    {
      id: 'ls_q1',
      prompt: 'Which letter makes the sound /æ/?',
      audioPrompt: 'A says /æ/',
      visualEmoji: '🍎',
      options: ['A', 'B', 'C'],
      correctOption: 'A',
      explanation: 'A says /æ/ as in Apple! 🍎',
    },
    {
      id: 'ls_q2',
      prompt: 'Which letter makes the sound /b/?',
      audioPrompt: 'B says /b/',
      visualEmoji: '⚽',
      options: ['D', 'B', 'P'],
      correctOption: 'B',
      explanation: 'B says /b/ as in Ball! ⚽',
    },
    {
      id: 'ls_q3',
      prompt: 'Which letter makes the sound /k/?',
      audioPrompt: 'C says /k/',
      visualEmoji: '🐱',
      options: ['S', 'M', 'C'],
      correctOption: 'C',
      explanation: 'C says /k/ as in Cat! 🐱',
    },
    {
      id: 'ls_q4',
      prompt: 'Which letter makes the sound /m/?',
      audioPrompt: 'M says /m/',
      visualEmoji: '🐒',
      options: ['M', 'N', 'W'],
      correctOption: 'M',
      explanation: 'M says /m/ as in Monkey! 🐒',
    },
    {
      id: 'ls_q5',
      prompt: 'Which letter makes the sound /s/?',
      audioPrompt: 'S says /s/',
      visualEmoji: '☀️',
      options: ['Z', 'S', 'C'],
      correctOption: 'S',
      explanation: 'S says /s/ as in Sun! ☀️',
    },
  ],

  sound_recognition: [
    {
      id: 'sr_q1',
      prompt: 'Listen to the sound: /d/. Which letter is it?',
      audioPrompt: '/d/',
      visualEmoji: '🐶',
      options: ['D', 'B', 'P'],
      correctOption: 'D',
      explanation: 'D makes the /d/ sound like Dog! 🐶',
    },
    {
      id: 'sr_q2',
      prompt: 'Listen to the sound: /f/. Which letter is it?',
      audioPrompt: '/f/',
      visualEmoji: '🐟',
      options: ['V', 'F', 'T'],
      correctOption: 'F',
      explanation: 'F makes the /f/ sound like Fish! 🐟',
    },
    {
      id: 'sr_q3',
      prompt: 'Listen to the sound: /t/. Which letter is it?',
      audioPrompt: '/t/',
      visualEmoji: '🐯',
      options: ['T', 'D', 'L'],
      correctOption: 'T',
      explanation: 'T makes the /t/ sound like Tiger! 🐯',
    },
    {
      id: 'sr_q4',
      prompt: 'Listen to the sound: /p/. Which letter is it?',
      audioPrompt: '/p/',
      visualEmoji: '🐷',
      options: ['B', 'P', 'D'],
      correctOption: 'P',
      explanation: 'P makes the /p/ sound like Pig! 🐷',
    },
    {
      id: 'sr_q5',
      prompt: 'Listen to the sound: /r/. Which letter is it?',
      audioPrompt: '/r/',
      visualEmoji: '🐰',
      options: ['R', 'N', 'L'],
      correctOption: 'R',
      explanation: 'R makes the /r/ sound like Rabbit! 🐰',
    },
  ],

  beginning_sounds: [
    {
      id: 'bs_q1',
      prompt: 'What sound does Apple start with?',
      audioPrompt: 'Apple starts with what sound?',
      visualEmoji: '🍎',
      options: ['/æ/', '/b/', '/s/'],
      correctOption: '/æ/',
      explanation: 'Apple starts with /æ/ (Letter A)!',
    },
    {
      id: 'bs_q2',
      prompt: 'What sound does Cat start with?',
      audioPrompt: 'Cat starts with what sound?',
      visualEmoji: '🐱',
      options: ['/k/', '/m/', '/t/'],
      correctOption: '/k/',
      explanation: 'Cat starts with /k/ (Letter C)!',
    },
    {
      id: 'bs_q3',
      prompt: 'What sound does Dog start with?',
      audioPrompt: 'Dog starts with what sound?',
      visualEmoji: '🐶',
      options: ['/d/', '/b/', '/p/'],
      correctOption: '/d/',
      explanation: 'Dog starts with /d/ (Letter D)!',
    },
    {
      id: 'bs_q4',
      prompt: 'What sound does Sun start with?',
      audioPrompt: 'Sun starts with what sound?',
      visualEmoji: '☀️',
      options: ['/s/', '/z/', '/t/'],
      correctOption: '/s/',
      explanation: 'Sun starts with /s/ (Letter S)!',
    },
    {
      id: 'bs_q5',
      prompt: 'What sound does Monkey start with?',
      audioPrompt: 'Monkey starts with what sound?',
      visualEmoji: '🐒',
      options: ['/m/', '/n/', '/w/'],
      correctOption: '/m/',
      explanation: 'Monkey starts with /m/ (Letter M)!',
    },
  ],

  ending_sounds: [
    {
      id: 'es_q1',
      prompt: 'What sound do you hear at the END of CAT?',
      audioPrompt: 'What is the ending sound of Cat?',
      visualEmoji: '🐱',
      options: ['/t/', '/k/', '/m/'],
      correctOption: '/t/',
      explanation: 'CAT ends with /t/ (Letter T)!',
    },
    {
      id: 'es_q2',
      prompt: 'What sound do you hear at the END of DOG?',
      audioPrompt: 'What is the ending sound of Dog?',
      visualEmoji: '🐶',
      options: ['/g/', '/d/', '/p/'],
      correctOption: '/g/',
      explanation: 'DOG ends with /g/ (Letter G)!',
    },
    {
      id: 'es_q3',
      prompt: 'What sound do you hear at the END of SUN?',
      audioPrompt: 'What is the ending sound of Sun?',
      visualEmoji: '☀️',
      options: ['/n/', '/s/', '/m/'],
      correctOption: '/n/',
      explanation: 'SUN ends with /n/ (Letter N)!',
    },
    {
      id: 'es_q4',
      prompt: 'What sound do you hear at the END of CUP?',
      audioPrompt: 'What is the ending sound of Cup?',
      visualEmoji: '🥛',
      options: ['/p/', '/k/', '/b/'],
      correctOption: '/p/',
      explanation: 'CUP ends with /p/ (Letter P)!',
    },
    {
      id: 'es_q5',
      prompt: 'What sound do you hear at the END of PIG?',
      audioPrompt: 'What is the ending sound of Pig?',
      visualEmoji: '🐷',
      options: ['/g/', '/p/', '/d/'],
      correctOption: '/g/',
      explanation: 'PIG ends with /g/ (Letter G)!',
    },
  ],

  slow_blending: [
    {
      id: 'sb_q1',
      prompt: 'Blend these sounds: /k/ + /æ/ + /t/ = ?',
      audioPrompt: '/k/ /æ/ /t/ makes what word?',
      visualEmoji: '🐱',
      options: ['CAT', 'BAT', 'DOG'],
      correctOption: 'CAT',
      explanation: '/k/ /æ/ /t/ blends together to say CAT!',
    },
    {
      id: 'sb_q2',
      prompt: 'Blend these sounds: /d/ + /ɒ/ + /g/ = ?',
      audioPrompt: '/d/ /aw/ /g/ makes what word?',
      visualEmoji: '🐶',
      options: ['DOG', 'LOG', 'PIG'],
      correctOption: 'DOG',
      explanation: '/d/ /ɒ/ /g/ blends together to say DOG!',
    },
    {
      id: 'sb_q3',
      prompt: 'Blend these sounds: /s/ + /ʌ/ + /n/ = ?',
      audioPrompt: '/s/ /uh/ /n/ makes what word?',
      visualEmoji: '☀️',
      options: ['SUN', 'RUN', 'SIT'],
      correctOption: 'SUN',
      explanation: '/s/ /ʌ/ /n/ blends together to say SUN!',
    },
    {
      id: 'sb_q4',
      prompt: 'Blend these sounds: /p/ + /e/ + /n/ = ?',
      audioPrompt: '/p/ /eh/ /n/ makes what word?',
      visualEmoji: '🖊️',
      options: ['PEN', 'PAN', 'PIN'],
      correctOption: 'PEN',
      explanation: '/p/ /e/ /n/ blends together to say PEN!',
    },
    {
      id: 'sb_q5',
      prompt: 'Blend these sounds: /b/ + /ʌ/ + /s/ = ?',
      audioPrompt: '/b/ /uh/ /s/ makes what word?',
      visualEmoji: '🚌',
      options: ['BUS', 'BUG', 'BED'],
      correctOption: 'BUS',
      explanation: '/b/ /ʌ/ /s/ blends together to say BUS!',
    },
  ],

  cvc_words: [
    {
      id: 'cvc_q1',
      prompt: 'Which word matches the picture 🐱?',
      visualEmoji: '🐱',
      options: ['CAT', 'DOG', 'SUN'],
      correctOption: 'CAT',
      explanation: 'CAT: C-A-T! 🐱',
    },
    {
      id: 'cvc_q2',
      prompt: 'Which word matches the picture 🛏️?',
      visualEmoji: '🛏️',
      options: ['BED', 'RED', 'BUS'],
      correctOption: 'BED',
      explanation: 'BED: B-E-D! 🛏️',
    },
    {
      id: 'cvc_q3',
      prompt: 'Which word matches the picture 🐷?',
      visualEmoji: '🐷',
      options: ['PIG', 'PUP', 'PEN'],
      correctOption: 'PIG',
      explanation: 'PIG: P-I-G! 🐷',
    },
    {
      id: 'cvc_q4',
      prompt: 'Which word matches the picture ☀️?',
      visualEmoji: '☀️',
      options: ['SUN', 'SON', 'SIT'],
      correctOption: 'SUN',
      explanation: 'SUN: S-U-N! ☀️',
    },
    {
      id: 'cvc_q5',
      prompt: 'Which word matches the picture 🥛?',
      visualEmoji: '🥛',
      options: ['CUP', 'CAP', 'CAN'],
      correctOption: 'CUP',
      explanation: 'CUP: C-U-P! 🥛',
    },
  ],

  word_families: [
    {
      id: 'wf_q1',
      prompt: 'Which word belongs to the -at family?',
      visualEmoji: '🎩',
      options: ['HAT', 'HOT', 'HIT'],
      correctOption: 'HAT',
      explanation: 'HAT ends in -at, just like CAT and BAT!',
    },
    {
      id: 'wf_q2',
      prompt: 'Which word belongs to the -an family?',
      visualEmoji: '🍳',
      options: ['PAN', 'PIN', 'PEN'],
      correctOption: 'PAN',
      explanation: 'PAN ends in -an, just like CAN and FAN!',
    },
    {
      id: 'wf_q3',
      prompt: 'Which word belongs to the -ig family?',
      visualEmoji: '⛏️',
      options: ['DIG', 'DOG', 'DUG'],
      correctOption: 'DIG',
      explanation: 'DIG ends in -ig, just like PIG and BIG!',
    },
    {
      id: 'wf_q4',
      prompt: 'Which word belongs to the -ug family?',
      visualEmoji: '☕',
      options: ['MUG', 'MAP', 'MAN'],
      correctOption: 'MUG',
      explanation: 'MUG ends in -ug, just like BUG and HUG!',
    },
    {
      id: 'wf_q5',
      prompt: 'Which word belongs to the -ot family?',
      visualEmoji: '🍲',
      options: ['POT', 'PET', 'PAT'],
      correctOption: 'POT',
      explanation: 'POT ends in -ot, just like HOT and DOT!',
    },
  ],

  phonics_challenge: [
    {
      id: 'pc_q1',
      prompt: 'What sound does Lion start with? 🦁',
      visualEmoji: '🦁',
      options: ['/l/', '/m/', '/r/'],
      correctOption: '/l/',
      explanation: 'Lion starts with /l/ (Letter L)!',
    },
    {
      id: 'pc_q2',
      prompt: 'What sound do you hear at the END of BUS? 🚌',
      visualEmoji: '🚌',
      options: ['/s/', '/b/', '/t/'],
      correctOption: '/s/',
      explanation: 'BUS ends with /s/ (Letter S)!',
    },
    {
      id: 'pc_q3',
      prompt: 'Blend: /h/ + /e/ + /n/ = ? 🐔',
      visualEmoji: '🐔',
      options: ['HEN', 'HAT', 'HOT'],
      correctOption: 'HEN',
      explanation: '/h/ /e/ /n/ = HEN! 🐔',
    },
    {
      id: 'pc_q4',
      prompt: 'Change C to B in CAT. What is the new word?',
      visualEmoji: '🦇',
      options: ['BAT', 'MAT', 'HAT'],
      correctOption: 'BAT',
      explanation: 'C-A-T becomes B-A-T (BAT)! 🦇',
    },
    {
      id: 'pc_q5',
      prompt: 'Which word rhymes with SUN? 🏃',
      visualEmoji: '🏃',
      options: ['RUN', 'RED', 'RAT'],
      correctOption: 'RUN',
      explanation: 'RUN rhymes with SUN (-un family)!',
    },
    {
      id: 'pc_q6',
      prompt: 'Read the sentence: "The dog ___."',
      visualEmoji: '🐶',
      options: ['ran', 'sun', 'pot'],
      correctOption: 'ran',
      explanation: '"The dog ran." makes sense!',
    },
    {
      id: 'pc_q7',
      prompt: 'Which word matches the image 🗺️?',
      visualEmoji: '🗺️',
      options: ['MAP', 'MUG', 'MAT'],
      correctOption: 'MAP',
      explanation: 'MAP: M-A-P! 🗺️',
    },
    {
      id: 'pc_q8',
      prompt: 'You are a Phonics Champion! How many sounds in C-A-T?',
      visualEmoji: '🏆',
      options: ['3 sounds', '1 sound', '5 sounds'],
      correctOption: '3 sounds',
      explanation: '/k/ /æ/ /t/ = 3 individual phoneme sounds!',
    },
  ],
};
