import type {
  AnimalClassificationItem,
  AnimalCountItem,
  AnimalDietItem,
  AnimalHabitatItem,
  AnimalItem,
  AnimalMatchingPair,
  AnimalPatternItem,
  AnimalPuzzleItem,
  AnimalQuizQuestion,
  AnimalSoundItem,
  AnimalSubModuleConfig,
  BabyAnimalItem,
} from '../entities/animalEntities';

export const ANIMALS_SUB_MODULES: readonly AnimalSubModuleConfig[] = [
  {
    id: 'meet_animals',
    titleKey: 'animals.submodules.meetAnimals',
    subtitleKey: 'animals.submodules.meetAnimalsSub',
    emoji: '🐾',
    accentColor: '#F59E0B',
    bgLightColor: '#FEF3C7',
    lessonCount: 4,
  },
  {
    id: 'land_animals',
    titleKey: 'animals.submodules.landAnimals',
    subtitleKey: 'animals.submodules.landAnimalsSub',
    emoji: '🐶',
    accentColor: '#10B981',
    bgLightColor: '#ECFDF5',
    lessonCount: 15,
  },
  {
    id: 'animal_sounds',
    titleKey: 'animals.submodules.sounds',
    subtitleKey: 'animals.submodules.soundsSub',
    emoji: '🔊',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    lessonCount: 10,
  },
  {
    id: 'habitats',
    titleKey: 'animals.submodules.habitats',
    subtitleKey: 'animals.submodules.habitatsSub',
    emoji: '🏠',
    accentColor: '#8B5CF6',
    bgLightColor: '#F5F3FF',
    lessonCount: 7,
  },
  {
    id: 'animal_diets',
    titleKey: 'animals.submodules.diets',
    subtitleKey: 'animals.submodules.dietsSub',
    emoji: '🥕',
    accentColor: '#EF4444',
    bgLightColor: '#FEF2F2',
    lessonCount: 6,
  },
  {
    id: 'birds',
    titleKey: 'animals.submodules.birds',
    subtitleKey: 'animals.submodules.birdsSub',
    emoji: '🐦',
    accentColor: '#0EA5E9',
    bgLightColor: '#F0F9FF',
    lessonCount: 12,
  },
  {
    id: 'sea_animals',
    titleKey: 'animals.submodules.seaAnimals',
    subtitleKey: 'animals.submodules.seaAnimalsSub',
    emoji: '🐠',
    accentColor: '#06B6D4',
    bgLightColor: '#ECFEFF',
    lessonCount: 12,
  },
  {
    id: 'amphibians_reptiles',
    titleKey: 'animals.submodules.amphibiansReptiles',
    subtitleKey: 'animals.submodules.amphibiansReptilesSub',
    emoji: '🐸',
    accentColor: '#84CC16',
    bgLightColor: '#F7FEE7',
    lessonCount: 6,
  },
  {
    id: 'insects',
    titleKey: 'animals.submodules.insects',
    subtitleKey: 'animals.submodules.insectsSub',
    emoji: '🐛',
    accentColor: '#F97316',
    bgLightColor: '#FFF7ED',
    lessonCount: 7,
  },
  {
    id: 'animal_babies',
    titleKey: 'animals.submodules.babies',
    subtitleKey: 'animals.submodules.babiesSub',
    emoji: '👶',
    accentColor: '#EC4899',
    bgLightColor: '#FDF2F8',
    lessonCount: 8,
  },
  {
    id: 'matching',
    titleKey: 'animals.submodules.matching',
    subtitleKey: 'animals.submodules.matchingSub',
    emoji: '🧩',
    accentColor: '#14B8A6',
    bgLightColor: '#F0FDFA',
    lessonCount: 5,
  },
  {
    id: 'classification',
    titleKey: 'animals.submodules.classification',
    subtitleKey: 'animals.submodules.classificationSub',
    emoji: '🧠',
    accentColor: '#6366F1',
    bgLightColor: '#EEF2FF',
    lessonCount: 4,
  },
  {
    id: 'count',
    titleKey: 'animals.submodules.count',
    subtitleKey: 'animals.submodules.countSub',
    emoji: '🔢',
    accentColor: '#D946EF',
    bgLightColor: '#FDF4FF',
    lessonCount: 4,
  },
  {
    id: 'patterns',
    titleKey: 'animals.submodules.patterns',
    subtitleKey: 'animals.submodules.patternsSub',
    emoji: '🔄',
    accentColor: '#F59E0B',
    bgLightColor: '#FEF3C7',
    lessonCount: 4,
  },
  {
    id: 'puzzles',
    titleKey: 'animals.submodules.puzzles',
    subtitleKey: 'animals.submodules.puzzlesSub',
    emoji: '🎯',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    lessonCount: 5,
  },
  {
    id: 'challenge',
    titleKey: 'animals.submodules.challenge',
    subtitleKey: 'animals.submodules.challengeSub',
    emoji: '🏆',
    accentColor: '#EA580C',
    bgLightColor: '#FFF7ED',
    lessonCount: 1,
  },
];

// ─── 15 LAND ANIMALS ────────────────────────────────────────────────────────
export const LAND_ANIMALS: readonly AnimalItem[] = [
  {
    id: 'dog',
    name: 'Dog',
    emoji: '🐶',
    category: 'land',
    soundName: 'Bark',
    soundOnomatopoeia: 'Woof Woof!',
    soundFrequencyHz: 350,
    habitat: 'farm',
    habitatDisplayName: 'Farm / Home',
    habitatEmoji: '🏠',
    food: 'meat',
    foodDisplayName: 'Meat & Dog food',
    foodEmoji: '🍖',
    babyName: 'Puppy',
    simpleFact: 'Dogs are loyal friends and have a great sense of smell!',
    appearanceDescription: 'Dogs have four legs, soft fur, and a wagging tail.',
    traits: ['Friendly', 'Loves playing', 'Barks'],
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    darkColor: '#B45309',
  },
  {
    id: 'cat',
    name: 'Cat',
    emoji: '🐱',
    category: 'land',
    soundName: 'Meow',
    soundOnomatopoeia: 'Meow Meow!',
    soundFrequencyHz: 480,
    habitat: 'farm',
    habitatDisplayName: 'Home / Farm',
    habitatEmoji: '🏠',
    food: 'fish',
    foodDisplayName: 'Fish & Milk',
    foodEmoji: '🐟',
    babyName: 'Kitten',
    simpleFact: 'Cats can jump very high and purr when happy!',
    appearanceDescription:
      'Cats have soft whiskers, sharp claws, and furry ears.',
    traits: ['Agile', 'Loves napping', 'Purrs'],
    color: '#FB923C',
    lightColor: '#FFEDD5',
    darkColor: '#C2410C',
  },
  {
    id: 'elephant',
    name: 'Elephant',
    emoji: '🐘',
    category: 'land',
    soundName: 'Trumpet',
    soundOnomatopoeia: 'Pawoo!',
    soundFrequencyHz: 180,
    habitat: 'grassland',
    habitatDisplayName: 'Grasslands & Forests',
    habitatEmoji: '🌳',
    food: 'plants',
    foodDisplayName: 'Leaves, Fruits & Grass',
    foodEmoji: '🌿',
    babyName: 'Calf',
    simpleFact: 'An elephant is the largest land animal and has a long trunk!',
    appearanceDescription:
      'Elephants have big floppy ears, grey skin, and long tusks.',
    traits: ['Huge', 'Long trunk', 'Smart'],
    color: '#6B7280',
    lightColor: '#F3F4F6',
    darkColor: '#374151',
  },
  {
    id: 'lion',
    name: 'Lion',
    emoji: '🦁',
    category: 'land',
    soundName: 'Roar',
    soundOnomatopoeia: 'Roaaar!',
    soundFrequencyHz: 220,
    habitat: 'grassland',
    habitatDisplayName: 'Savannah Grasslands',
    habitatEmoji: '🌾',
    food: 'meat',
    foodDisplayName: 'Meat',
    foodEmoji: '🍖',
    babyName: 'Cub',
    simpleFact:
      'The lion is called the King of the Jungle and has a big furry mane!',
    appearanceDescription:
      'Male lions have a large golden mane around their heads.',
    traits: ['Brave', 'Loud roar', 'Golden fur'],
    color: '#D97706',
    lightColor: '#FEF3C7',
    darkColor: '#92400E',
  },
  {
    id: 'tiger',
    name: 'Tiger',
    emoji: '🐯',
    category: 'land',
    soundName: 'Growl',
    soundOnomatopoeia: 'Grrr!',
    soundFrequencyHz: 240,
    habitat: 'forest',
    habitatDisplayName: 'Dense Forests',
    habitatEmoji: '🌲',
    food: 'meat',
    foodDisplayName: 'Meat',
    foodEmoji: '🍖',
    babyName: 'Cub',
    simpleFact:
      'Tigers are excellent swimmers and have beautiful black stripes!',
    appearanceDescription:
      'Tigers have bright orange fur with unique black stripes.',
    traits: ['Strong', 'Striped coat', 'Loves water'],
    color: '#EA580C',
    lightColor: '#FFEDD5',
    darkColor: '#9A3412',
  },
  {
    id: 'bear',
    name: 'Bear',
    emoji: '🐻',
    category: 'land',
    soundName: 'Growl',
    soundOnomatopoeia: 'Grr Rawr!',
    soundFrequencyHz: 200,
    habitat: 'forest',
    habitatDisplayName: 'Forests & Mountains',
    habitatEmoji: '🌲',
    food: 'fish',
    foodDisplayName: 'Berries & Fresh Fish',
    foodEmoji: '🐟',
    babyName: 'Cub',
    simpleFact: 'Bears love sweet honey and sleep through the cold winter!',
    appearanceDescription:
      'Bears have thick fur coats, strong claws, and round ears.',
    traits: ['Strong', 'Thick fur', 'Honey lover'],
    color: '#78350F',
    lightColor: '#FEF3C7',
    darkColor: '#451A03',
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    emoji: '🐰',
    category: 'land',
    soundName: 'Squeak',
    soundOnomatopoeia: 'Thump Thump!',
    soundFrequencyHz: 520,
    habitat: 'grassland',
    habitatDisplayName: 'Meadows & Burrows',
    habitatEmoji: '🌾',
    food: 'plants',
    foodDisplayName: 'Carrots & Fresh Greens',
    foodEmoji: '🥕',
    babyName: 'Bunny / Kit',
    simpleFact:
      'Rabbits have long ears to hear faraway sounds and love hopping!',
    appearanceDescription:
      'Rabbits have long upright ears, soft fur, and a fluffy tail.',
    traits: ['Hops fast', 'Long ears', 'Loves carrots'],
    color: '#EC4899',
    lightColor: '#FDF2F8',
    darkColor: '#BE185D',
  },
  {
    id: 'horse',
    name: 'Horse',
    emoji: '🐴',
    category: 'land',
    soundName: 'Neigh',
    soundOnomatopoeia: 'Neighhh!',
    soundFrequencyHz: 400,
    habitat: 'farm',
    habitatDisplayName: 'Farm Stables & Meadows',
    habitatEmoji: '🏠',
    food: 'grass',
    foodDisplayName: 'Grass, Hay & Apples',
    foodEmoji: '🌿',
    babyName: 'Foal',
    simpleFact:
      'Horses can run very fast and can even sleep while standing up!',
    appearanceDescription:
      'Horses have long legs, flowing manes, and strong hooves.',
    traits: ['Fast runner', 'Flowing mane', 'Neighs'],
    color: '#92400E',
    lightColor: '#FEF3C7',
    darkColor: '#78350F',
  },
  {
    id: 'cow',
    name: 'Cow',
    emoji: '🐮',
    category: 'land',
    soundName: 'Moo',
    soundOnomatopoeia: 'Moo Moo!',
    soundFrequencyHz: 210,
    habitat: 'farm',
    habitatDisplayName: 'Green Farm Pastures',
    habitatEmoji: '🏠',
    food: 'grass',
    foodDisplayName: 'Green Grass & Hay',
    foodEmoji: '🌿',
    babyName: 'Calf',
    simpleFact: 'Cows give us healthy fresh milk and love chewing green grass!',
    appearanceDescription:
      'Cows have spots on their coat, two horns, and gentle eyes.',
    traits: ['Gentle', 'Gives milk', 'Moos'],
    color: '#10B981',
    lightColor: '#ECFDF5',
    darkColor: '#047857',
  },
  {
    id: 'pig',
    name: 'Pig',
    emoji: '🐷',
    category: 'land',
    soundName: 'Oink',
    soundOnomatopoeia: 'Oink Oink!',
    soundFrequencyHz: 330,
    habitat: 'farm',
    habitatDisplayName: 'Farm Pen',
    habitatEmoji: '🏠',
    food: 'fruits',
    foodDisplayName: 'Fruits & Vegetables',
    foodEmoji: '🍎',
    babyName: 'Piglet',
    simpleFact: 'Pigs are very smart and roll in mud to keep their skin cool!',
    appearanceDescription:
      'Pigs have pink skin, a flat curly snout, and a curly tail.',
    traits: ['Pink skin', 'Curly tail', 'Oinks'],
    color: '#F472B6',
    lightColor: '#FDF2F8',
    darkColor: '#DB2777',
  },
  {
    id: 'sheep',
    name: 'Sheep',
    emoji: '🐑',
    category: 'land',
    soundName: 'Baa',
    soundOnomatopoeia: 'Baa Baa!',
    soundFrequencyHz: 380,
    habitat: 'farm',
    habitatDisplayName: 'Grassy Hills & Farms',
    habitatEmoji: '🏠',
    food: 'grass',
    foodDisplayName: 'Short Grass',
    foodEmoji: '🌿',
    babyName: 'Lamb',
    simpleFact:
      'Sheep have warm fluffy wool that makes soft sweaters and blankets!',
    appearanceDescription: 'Sheep have a thick fluffy white wool coat.',
    traits: ['Fluffy wool', 'Gentle', 'Baas'],
    color: '#64748B',
    lightColor: '#F1F5F9',
    darkColor: '#334155',
  },
  {
    id: 'goat',
    name: 'Goat',
    emoji: '🐐',
    category: 'land',
    soundName: 'Bleat',
    soundOnomatopoeia: 'Maa Maa!',
    soundFrequencyHz: 420,
    habitat: 'farm',
    habitatDisplayName: 'Rocky Hills & Farms',
    habitatEmoji: '🏠',
    food: 'plants',
    foodDisplayName: 'Leaves & Shrubs',
    foodEmoji: '🌿',
    babyName: 'Kid',
    simpleFact: 'Goats are great climbers and love balancing on steep rocks!',
    appearanceDescription:
      'Goats have curved horns, a chin beard, and curious eyes.',
    traits: ['Climber', 'Curious beard', 'Agile'],
    color: '#84CC16',
    lightColor: '#F7FEE7',
    darkColor: '#4D7C0F',
  },
  {
    id: 'monkey',
    name: 'Monkey',
    emoji: '🐒',
    category: 'land',
    soundName: 'Chatter',
    soundOnomatopoeia: 'Ooh Ooh Aah Aah!',
    soundFrequencyHz: 490,
    habitat: 'forest',
    habitatDisplayName: 'Treetops in the Jungle',
    habitatEmoji: '🌳',
    food: 'fruits',
    foodDisplayName: 'Sweet Bananas & Berries',
    foodEmoji: '🍌',
    babyName: 'Infant',
    simpleFact:
      'Monkeys use their strong tails to swing between tree branches!',
    appearanceDescription:
      'Monkeys have long arms, flexible tails, and lively faces.',
    traits: ['Playful', 'Swings in trees', 'Loves bananas'],
    color: '#B45309',
    lightColor: '#FEF3C7',
    darkColor: '#78350F',
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    emoji: '🦒',
    category: 'land',
    soundName: 'Hum',
    soundOnomatopoeia: 'Mmm Hum!',
    soundFrequencyHz: 150,
    habitat: 'grassland',
    habitatDisplayName: 'African Savannah',
    habitatEmoji: '🌾',
    food: 'plants',
    foodDisplayName: 'High Acacia Tree Leaves',
    foodEmoji: '🌿',
    babyName: 'Calf',
    simpleFact:
      'The giraffe is the tallest animal in the world with a very long neck!',
    appearanceDescription:
      'Giraffes have tall necks, long legs, and spotted brown patterns.',
    traits: ['Tallest animal', 'Long blue tongue', 'Spotted coat'],
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    darkColor: '#B45309',
  },
  {
    id: 'zebra',
    name: 'Zebra',
    emoji: '🦓',
    category: 'land',
    soundName: 'Bray',
    soundOnomatopoeia: 'Bark Neigh!',
    soundFrequencyHz: 360,
    habitat: 'grassland',
    habitatDisplayName: 'Open Grasslands',
    habitatEmoji: '🌾',
    food: 'grass',
    foodDisplayName: 'Wild Grass',
    foodEmoji: '🌿',
    babyName: 'Foal',
    simpleFact:
      'Every single zebra has a unique pattern of black and white stripes!',
    appearanceDescription: 'Zebras have bold black-and-white vertical stripes.',
    traits: ['Striped', 'Fast runner', 'Herd animal'],
    color: '#1E293B',
    lightColor: '#F8FAFC',
    darkColor: '#0F172A',
  },
];

// ─── 12 BIRDS ───────────────────────────────────────────────────────────────
export const BIRDS_DATA: readonly AnimalItem[] = [
  {
    id: 'sparrow',
    name: 'Sparrow',
    emoji: '🐦',
    category: 'bird',
    soundName: 'Chirp',
    soundOnomatopoeia: 'Chirp Chirp!',
    soundFrequencyHz: 600,
    habitat: 'forest',
    habitatDisplayName: 'Gardens & Trees',
    habitatEmoji: '🌳',
    food: 'seeds',
    foodDisplayName: 'Small Seeds & Grains',
    foodEmoji: '🌾',
    babyName: 'Chick',
    simpleFact:
      'Sparrows are cheerful little birds that hop around garden lawns!',
    appearanceDescription: 'Small brown and grey feathers with a tiny beak.',
    traits: ['Chirpy', 'Small', 'Hops on ground'],
    color: '#854D0E',
    lightColor: '#FEF9C3',
    darkColor: '#713F12',
  },
  {
    id: 'parrot',
    name: 'Parrot',
    emoji: '🦜',
    category: 'bird',
    soundName: 'Squawk',
    soundOnomatopoeia: 'Squawk Hello!',
    soundFrequencyHz: 550,
    habitat: 'forest',
    habitatDisplayName: 'Tropical Rainforests',
    habitatEmoji: '🌴',
    food: 'fruits',
    foodDisplayName: 'Seeds, Nuts & Sweet Fruits',
    foodEmoji: '🥭',
    babyName: 'Chick',
    simpleFact:
      'Parrots have bright green feathers and can learn to repeat words!',
    appearanceDescription: 'Vibrant green feathers with a curved red beak.',
    traits: ['Colorful', 'Smart talker', 'Curved beak'],
    color: '#10B981',
    lightColor: '#ECFDF5',
    darkColor: '#047857',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    emoji: '🦚',
    category: 'bird',
    soundName: 'Scream',
    soundOnomatopoeia: 'May-Awe!',
    soundFrequencyHz: 450,
    habitat: 'forest',
    habitatDisplayName: 'Forests & Gardens',
    habitatEmoji: '🌳',
    food: 'plants',
    foodDisplayName: 'Seeds, Berries & Insects',
    foodEmoji: '🌿',
    babyName: 'Peachick',
    simpleFact:
      'The peacock opens its gorgeous tail feathers like a giant colorful fan!',
    appearanceDescription:
      'Bright blue neck with iridescent green eye-spotted tail.',
    traits: ['Fan tail', 'National bird', 'Dances in rain'],
    color: '#0284C7',
    lightColor: '#E0F2FE',
    darkColor: '#0369A1',
  },
  {
    id: 'owl',
    name: 'Owl',
    emoji: '🦉',
    category: 'bird',
    soundName: 'Hoot',
    soundOnomatopoeia: 'Hoot Hoot!',
    soundFrequencyHz: 320,
    habitat: 'forest',
    habitatDisplayName: 'Tree Hollows at Night',
    habitatEmoji: '🌲',
    food: 'meat',
    foodDisplayName: 'Small Mice & Insects',
    foodEmoji: '🐭',
    babyName: 'Owlet',
    simpleFact:
      'Owls can turn their heads almost all the way around and see in the dark!',
    appearanceDescription:
      'Large round golden eyes with mottled brown feathers.',
    traits: ['Night hunter', 'Silent wings', 'Big round eyes'],
    color: '#78350F',
    lightColor: '#FEF3C7',
    darkColor: '#451A03',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    emoji: '🦅',
    category: 'bird',
    soundName: 'Screech',
    soundOnomatopoeia: 'Kreee!',
    soundFrequencyHz: 500,
    habitat: 'forest',
    habitatDisplayName: 'High Mountains & Cliffs',
    habitatEmoji: '🏔️',
    food: 'fish',
    foodDisplayName: 'Fish & Small Animals',
    foodEmoji: '🐟',
    babyName: 'Eaglet',
    simpleFact:
      'Eagles fly very high in the sky and have super sharp eyesight!',
    appearanceDescription:
      'Huge wingspan, hooked yellow beak, and sharp talons.',
    traits: ['King of skies', 'Sharp eyes', 'Soars high'],
    color: '#9A3412',
    lightColor: '#FFEDD5',
    darkColor: '#7C2D12',
  },
  {
    id: 'duck',
    name: 'Duck',
    emoji: '🦆',
    category: 'bird',
    soundName: 'Quack',
    soundOnomatopoeia: 'Quack Quack!',
    soundFrequencyHz: 410,
    habitat: 'river',
    habitatDisplayName: 'Ponds & Lakes',
    habitatEmoji: '🏞️',
    food: 'plants',
    foodDisplayName: 'Water Plants & Small Fish',
    foodEmoji: '🌿',
    babyName: 'Duckling',
    simpleFact:
      'Ducks have webbed feet that work just like little swim flippers!',
    appearanceDescription:
      'Waterproof feathers, flat bill, and webbed paddle feet.',
    traits: ['Swims on ponds', 'Webbed feet', 'Quacks'],
    color: '#0D9488',
    lightColor: '#CCFBF1',
    darkColor: '#115E59',
  },
  {
    id: 'hen',
    name: 'Hen',
    emoji: '🐔',
    category: 'bird',
    soundName: 'Cluck',
    soundOnomatopoeia: 'Cluck Cluck!',
    soundFrequencyHz: 460,
    habitat: 'farm',
    habitatDisplayName: 'Farm Coop',
    habitatEmoji: '🏠',
    food: 'seeds',
    foodDisplayName: 'Corn & Grain Seeds',
    foodEmoji: '🌽',
    babyName: 'Chick',
    simpleFact:
      'Hens lay eggs every morning and look after cute little baby chicks!',
    appearanceDescription:
      'Red comb on head, rounded body with brown/white feathers.',
    traits: ['Lays eggs', 'Clucks', 'Farm bird'],
    color: '#EA580C',
    lightColor: '#FFEDD5',
    darkColor: '#9A3412',
  },
  {
    id: 'rooster',
    name: 'Rooster',
    emoji: '🐓',
    category: 'bird',
    soundName: 'Crow',
    soundOnomatopoeia: 'Cock-a-doodle-doo!',
    soundFrequencyHz: 520,
    habitat: 'farm',
    habitatDisplayName: 'Farm Barnyard',
    habitatEmoji: '🏠',
    food: 'seeds',
    foodDisplayName: 'Grains & Seeds',
    foodEmoji: '🌾',
    babyName: 'Chick',
    simpleFact:
      'The rooster crows loudly at sunrise to wake up the whole farm!',
    appearanceDescription:
      'Bright red crown, tall tail feathers, and proud stance.',
    traits: ['Wakes the farm', 'Proud crow', 'Bright crown'],
    color: '#DC2626',
    lightColor: '#FEE2E2',
    darkColor: '#991B1B',
  },
  {
    id: 'swan',
    name: 'Swan',
    emoji: '🦢',
    category: 'bird',
    soundName: 'Honk',
    soundOnomatopoeia: 'Whoop Honk!',
    soundFrequencyHz: 340,
    habitat: 'river',
    habitatDisplayName: 'Calm Lakes & Rivers',
    habitatEmoji: '🏞️',
    food: 'plants',
    foodDisplayName: 'Water Lily Leaves & Algae',
    foodEmoji: '🌿',
    babyName: 'Cygnet',
    simpleFact:
      'Swans are elegant birds with long curved necks that glide smoothly on water!',
    appearanceDescription:
      'Snow-white feathers with a long graceful S-curved neck.',
    traits: ['Graceful', 'Long neck', 'Glides on lakes'],
    color: '#0284C7',
    lightColor: '#E0F2FE',
    darkColor: '#0369A1',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    emoji: '🦩',
    category: 'bird',
    soundName: 'Honk',
    soundOnomatopoeia: 'Honk Kraaa!',
    soundFrequencyHz: 400,
    habitat: 'river',
    habitatDisplayName: 'Shallow Lagoons & Lakes',
    habitatEmoji: '🏞️',
    food: 'fish',
    foodDisplayName: 'Tiny Pink Shrimp & Algae',
    foodEmoji: '🦐',
    babyName: 'Chick',
    simpleFact:
      'Flamingos are pink because of the shrimp they eat, and often stand on one leg!',
    appearanceDescription:
      'Bright pink feathers, very long legs, and curved beak.',
    traits: ['Pink feathers', 'One-leg balance', 'Shallow waters'],
    color: '#EC4899',
    lightColor: '#FDF2F8',
    darkColor: '#BE185D',
  },
  {
    id: 'penguin',
    name: 'Penguin',
    emoji: '🐧',
    category: 'bird',
    soundName: 'Squawk',
    soundOnomatopoeia: 'Honk Bray!',
    soundFrequencyHz: 380,
    habitat: 'polar',
    habitatDisplayName: 'Icy Polar Seas & Glaciers',
    habitatEmoji: '❄️',
    food: 'fish',
    foodDisplayName: 'Silver Fish & Krill',
    foodEmoji: '🐟',
    babyName: 'Chick',
    simpleFact:
      'Penguins are flightless birds that swim like torpedoes in icy water!',
    appearanceDescription:
      'Black-and-white tuxedo feathers with short flipper wings.',
    traits: ['Swims in ice', 'Waddles cute', 'Tuxedo look'],
    color: '#0F172A',
    lightColor: '#F1F5F9',
    darkColor: '#020617',
  },
  {
    id: 'turkey',
    name: 'Turkey',
    emoji: '🦃',
    category: 'bird',
    soundName: 'Gobble',
    soundOnomatopoeia: 'Gobble Gobble!',
    soundFrequencyHz: 360,
    habitat: 'farm',
    habitatDisplayName: 'Farms & Woodlands',
    habitatEmoji: '🏠',
    food: 'seeds',
    foodDisplayName: 'Acorns, Berries & Seeds',
    foodEmoji: '🌾',
    babyName: 'Poult',
    simpleFact:
      'Turkeys make a funny gobble sound and spread their wide tail feathers!',
    appearanceDescription:
      'Large round body, fan tail, and a red wattle on neck.',
    traits: ['Gobble sound', 'Fan tail', 'Farm bird'],
    color: '#B45309',
    lightColor: '#FEF3C7',
    darkColor: '#78350F',
  },
];

// ─── 12 SEA ANIMALS ─────────────────────────────────────────────────────────
export const SEA_ANIMALS_DATA: readonly AnimalItem[] = [
  {
    id: 'fish',
    name: 'Fish',
    emoji: '🐟',
    category: 'sea',
    soundName: 'Bubble',
    soundOnomatopoeia: 'Bloop Bloop!',
    soundFrequencyHz: 480,
    habitat: 'ocean',
    habitatDisplayName: 'Coral Reefs & Oceans',
    habitatEmoji: '🌊',
    food: 'plants',
    foodDisplayName: 'Seaweed & Tiny Plankton',
    foodEmoji: '🌿',
    babyName: 'Fry',
    simpleFact: 'Fish breathe underwater using gills and swim with shiny fins!',
    appearanceDescription: 'Glittering scales, gills, and a waving tail fin.',
    traits: ['Gills', 'Swims with fins', 'Scales'],
    color: '#0284C7',
    lightColor: '#E0F2FE',
    darkColor: '#0369A1',
  },
  {
    id: 'dolphin',
    name: 'Dolphin',
    emoji: '🐬',
    category: 'sea',
    soundName: 'Click',
    soundOnomatopoeia: 'Click Whistle!',
    soundFrequencyHz: 650,
    habitat: 'ocean',
    habitatDisplayName: 'Warm Ocean Waters',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Small Ocean Fish',
    foodEmoji: '🐟',
    babyName: 'Calf',
    simpleFact:
      'Dolphins are super friendly, love jumping out of waves, and talk with clicks!',
    appearanceDescription:
      'Sleek grey body, curved dorsal fin, and a friendly snout.',
    traits: ['Super playful', 'Jumps waves', 'Echolocation'],
    color: '#06B6D4',
    lightColor: '#ECFEFF',
    darkColor: '#0891B2',
  },
  {
    id: 'whale',
    name: 'Blue Whale',
    emoji: '🐋',
    category: 'sea',
    soundName: 'Song',
    soundOnomatopoeia: 'Oooooo Mmm!',
    soundFrequencyHz: 120,
    habitat: 'ocean',
    habitatDisplayName: 'Deep Blue Oceans',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Tiny Krill & Shrimp',
    foodEmoji: '🦐',
    babyName: 'Calf',
    simpleFact:
      'The blue whale is the biggest animal that ever lived on Earth!',
    appearanceDescription:
      'Gigantic blue-grey body with a water spout blowhole on top.',
    traits: ['Biggest animal', 'Blowhole spout', 'Deep diver'],
    color: '#1E40AF',
    lightColor: '#DBEAFE',
    darkColor: '#1E3A8A',
  },
  {
    id: 'shark',
    name: 'Shark',
    emoji: '🦈',
    category: 'sea',
    soundName: 'Splash',
    soundOnomatopoeia: 'Swish Splash!',
    soundFrequencyHz: 200,
    habitat: 'ocean',
    habitatDisplayName: 'Open Ocean Waters',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Ocean Fish',
    foodEmoji: '🐟',
    babyName: 'Pup',
    simpleFact:
      'Sharks are fast swimmers and have multiple rows of sharp teeth!',
    appearanceDescription:
      'Triangle dorsal fin above water, grey body, and gills.',
    traits: ['Fast swimmer', 'Dorsal fin', 'Sharp teeth'],
    color: '#475569',
    lightColor: '#F1F5F9',
    darkColor: '#1E293B',
  },
  {
    id: 'octopus',
    name: 'Octopus',
    emoji: '🐙',
    category: 'sea',
    soundName: 'Squirt',
    soundOnomatopoeia: 'Squirt Bloop!',
    soundFrequencyHz: 310,
    habitat: 'ocean',
    habitatDisplayName: 'Sea Floor & Coral Caves',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Crabs & Clams',
    foodEmoji: '🦀',
    babyName: 'Larva',
    simpleFact:
      'An octopus has 8 flexible arms with suction cups and 3 hearts!',
    appearanceDescription:
      'Round head with eight waving arms covered in suckers.',
    traits: ['8 arms', '3 hearts', 'Can change colors'],
    color: '#E11D48',
    lightColor: '#FFE4E6',
    darkColor: '#9F1239',
  },
  {
    id: 'crab',
    name: 'Crab',
    emoji: '🦀',
    category: 'sea',
    soundName: 'Snap',
    soundOnomatopoeia: 'Snap Click!',
    soundFrequencyHz: 420,
    habitat: 'ocean',
    habitatDisplayName: 'Sandy Seashore & Rocks',
    habitatEmoji: '🌊',
    food: 'plants',
    foodDisplayName: 'Seaweed & Tiny Shellfish',
    foodEmoji: '🌿',
    babyName: 'Zoea',
    simpleFact:
      'Crabs walk sideways on their 10 legs and have strong pinching claws!',
    appearanceDescription: 'Hard red shell with two big pincer claws.',
    traits: ['Walks sideways', 'Pinch claws', 'Hard shell'],
    color: '#EA580C',
    lightColor: '#FFEDD5',
    darkColor: '#9A3412',
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    emoji: '🦐',
    category: 'sea',
    soundName: 'Snap',
    soundOnomatopoeia: 'Click Snap!',
    soundFrequencyHz: 560,
    habitat: 'ocean',
    habitatDisplayName: 'Shallow Coastal Waters',
    habitatEmoji: '🌊',
    food: 'plants',
    foodDisplayName: 'Tiny Algae & Plankton',
    foodEmoji: '🌿',
    babyName: 'Nauplius',
    simpleFact: 'Shrimp swim backwards by quickly bending their curved tails!',
    appearanceDescription: 'Curved pink body with long delicate antennae.',
    traits: ['Long antennae', 'Swims backward', 'Pink shell'],
    color: '#FB7185',
    lightColor: '#FFE4E6',
    darkColor: '#E11D48',
  },
  {
    id: 'jellyfish',
    name: 'Jellyfish',
    emoji: '🪼',
    category: 'sea',
    soundName: 'Glow',
    soundOnomatopoeia: 'Glow Drift!',
    soundFrequencyHz: 350,
    habitat: 'ocean',
    habitatDisplayName: 'Warm Drifting Oceans',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Tiny Plankton & Baby Fish',
    foodEmoji: '🐟',
    babyName: 'Planula',
    simpleFact:
      'Jellyfish have no bones or brain, and gently drift like glowing bells!',
    appearanceDescription: 'Translucent bell dome with soft flowing tentacles.',
    traits: ['No bones', 'Glows in dark', 'Flowing tentacles'],
    color: '#C084FC',
    lightColor: '#FAF5FF',
    darkColor: '#7E22CE',
  },
  {
    id: 'sea_turtle',
    name: 'Sea Turtle',
    emoji: '🐢',
    category: 'sea',
    soundName: 'Hiss',
    soundOnomatopoeia: 'Hiss Paddle!',
    soundFrequencyHz: 280,
    habitat: 'ocean',
    habitatDisplayName: 'Tropical Coral Seas',
    habitatEmoji: '🌊',
    food: 'plants',
    foodDisplayName: 'Green Seaweed & Jellyfish',
    foodEmoji: '🌿',
    babyName: 'Hatchling',
    simpleFact:
      'Sea turtles have paddle flippers and can live for more than 100 years!',
    appearanceDescription:
      'Hard patterned shell with large smooth swim flippers.',
    traits: ['Lives 100+ years', 'Flipper arms', 'Hard shell'],
    color: '#15803D',
    lightColor: '#DCFCE7',
    darkColor: '#166534',
  },
  {
    id: 'starfish',
    name: 'Starfish',
    emoji: '⭐',
    category: 'sea',
    soundName: 'Rustle',
    soundOnomatopoeia: 'Crawl Rustle!',
    soundFrequencyHz: 400,
    habitat: 'ocean',
    habitatDisplayName: 'Tide Pools & Coral Reefs',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Clams & Oysters',
    foodEmoji: '🐚',
    babyName: 'Bipinnaria',
    simpleFact:
      'A starfish is shaped like a star and can grow a new arm if it loses one!',
    appearanceDescription:
      'Bright five-pointed star body with tiny tube feet underneath.',
    traits: ['5 pointed arms', 'Regrows arms', 'Tide pools'],
    color: '#F59E0B',
    lightColor: '#FEF3C7',
    darkColor: '#B45309',
  },
  {
    id: 'squid',
    name: 'Squid',
    emoji: '🦑',
    category: 'sea',
    soundName: 'Jet',
    soundOnomatopoeia: 'Whoosh Jet!',
    soundFrequencyHz: 320,
    habitat: 'ocean',
    habitatDisplayName: 'Deep Ocean Waters',
    habitatEmoji: '🌊',
    food: 'fish',
    foodDisplayName: 'Small Fish & Crabs',
    foodEmoji: '🐟',
    babyName: 'Paralarva',
    simpleFact:
      'Squids shoot jets of water to zoom super fast through the ocean!',
    appearanceDescription:
      'Torpedo-shaped body with 10 arms and big glowing eyes.',
    traits: ['Jet propulsion', '10 arms', 'Fast swimmer'],
    color: '#D946EF',
    lightColor: '#FDF4FF',
    darkColor: '#A21CAF',
  },
  {
    id: 'seal',
    name: 'Seal',
    emoji: '🦭',
    category: 'sea',
    soundName: 'Bark',
    soundOnomatopoeia: 'Arf Arf!',
    soundFrequencyHz: 360,
    habitat: 'polar',
    habitatDisplayName: 'Cold Ocean Coasts & Ice',
    habitatEmoji: '❄️',
    food: 'fish',
    foodDisplayName: 'Fresh Fish & Squid',
    foodEmoji: '🐟',
    babyName: 'Pup',
    simpleFact:
      'Seals have thick blubber to keep warm and clap their flippers happily!',
    appearanceDescription:
      'Smooth whiskered face with round body and flipper feet.',
    traits: ['Whiskers', 'Claps flippers', 'Cold oceans'],
    color: '#475569',
    lightColor: '#F1F5F9',
    darkColor: '#1E293B',
  },
];

// ─── AMPHIBIANS & REPTILES ──────────────────────────────────────────────────
export const AMPHIBIANS_REPTILES_DATA: readonly AnimalItem[] = [
  {
    id: 'frog',
    name: 'Frog',
    emoji: '🐸',
    category: 'amphibian',
    soundName: 'Croak',
    soundOnomatopoeia: 'Ribbit Croak!',
    soundFrequencyHz: 300,
    habitat: 'river',
    habitatDisplayName: 'Ponds, Lakes & Streams',
    habitatEmoji: '🏞️',
    food: 'insects',
    foodDisplayName: 'Flies & Mosquitoes',
    foodEmoji: '🪰',
    babyName: 'Tadpole',
    simpleFact:
      'Frogs can live both on land and in water, and catch flies with long sticky tongues!',
    appearanceDescription:
      'Smooth green skin, long jumping legs, and big bulging eyes.',
    traits: ['Jumps far', 'Sticky tongue', 'Lives in & out of water'],
    color: '#16A34A',
    lightColor: '#DCFCE7',
    darkColor: '#15803D',
  },
  {
    id: 'salamander',
    name: 'Salamander',
    emoji: '🦎',
    category: 'amphibian',
    soundName: 'Squeak',
    soundOnomatopoeia: 'Squeak Rustle!',
    soundFrequencyHz: 450,
    habitat: 'forest',
    habitatDisplayName: 'Damp Forest Floors & Rocks',
    habitatEmoji: '🌲',
    food: 'insects',
    foodDisplayName: 'Worms & Small Bugs',
    foodEmoji: '🪱',
    babyName: 'Larva',
    simpleFact:
      'Salamanders have cool moist skin and like hiding under damp logs!',
    appearanceDescription:
      'Lizard-like body with smooth moist skin and a long tail.',
    traits: ['Moist skin', 'Hides under logs', 'Four small legs'],
    color: '#CA8A04',
    lightColor: '#FEF08A',
    darkColor: '#854D0E',
  },
  {
    id: 'snake',
    name: 'Snake',
    emoji: '🐍',
    category: 'reptile',
    soundName: 'Hiss',
    soundOnomatopoeia: 'Hisssss!',
    soundFrequencyHz: 500,
    habitat: 'forest',
    habitatDisplayName: 'Forests & Deserts',
    habitatEmoji: '🌲',
    food: 'meat',
    foodDisplayName: 'Frogs, Mice & Eggs',
    foodEmoji: '🐭',
    babyName: 'Snakelet',
    simpleFact:
      'Snakes have no legs and slither smoothly across the ground using scales!',
    appearanceDescription:
      'Long flexible body with patterned scales and forked tongue.',
    traits: ['No legs', 'Slithers fast', 'Forked tongue'],
    color: '#059669',
    lightColor: '#D1FAE5',
    darkColor: '#065F46',
  },
  {
    id: 'turtle',
    name: 'Land Turtle',
    emoji: '🐢',
    category: 'reptile',
    soundName: 'Hiss',
    soundOnomatopoeia: 'Hiss Crunch!',
    soundFrequencyHz: 260,
    habitat: 'forest',
    habitatDisplayName: 'Forest Floors & Gardens',
    habitatEmoji: '🌳',
    food: 'plants',
    foodDisplayName: 'Leaves, Grass & Mushrooms',
    foodEmoji: '🌿',
    babyName: 'Hatchling',
    simpleFact:
      'Turtles carry a hard protective shell on their backs and walk very slowly!',
    appearanceDescription:
      'Dome-shaped shell with clawed feet and a gentle face.',
    traits: ['Slow walker', 'Protective shell', 'Very patient'],
    color: '#15803D',
    lightColor: '#DCFCE7',
    darkColor: '#166534',
  },
  {
    id: 'lizard',
    name: 'Lizard',
    emoji: '🦎',
    category: 'reptile',
    soundName: 'Hiss',
    soundOnomatopoeia: 'Click Skitter!',
    soundFrequencyHz: 480,
    habitat: 'desert',
    habitatDisplayName: 'Sunny Walls & Desert Rocks',
    habitatEmoji: '🏜️',
    food: 'insects',
    foodDisplayName: 'Insects, Spiders & Ants',
    foodEmoji: '🐜',
    babyName: 'Hatchling',
    simpleFact: 'Lizards love basking in the warm sunshine on rocks!',
    appearanceDescription:
      'Scalloped scales, four clawed feet, and a long slender tail.',
    traits: ['Basks in sun', 'Quick climber', 'Sticky toes'],
    color: '#65A30D',
    lightColor: '#ECFCCB',
    darkColor: '#3F6212',
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    emoji: '🐊',
    category: 'reptile',
    soundName: 'Growl',
    soundOnomatopoeia: 'Snap Roar!',
    soundFrequencyHz: 210,
    habitat: 'river',
    habitatDisplayName: 'Tropical Rivers & Swamps',
    habitatEmoji: '🏞️',
    food: 'fish',
    foodDisplayName: 'Fish & Water Animals',
    foodEmoji: '🐟',
    babyName: 'Hatchling',
    simpleFact:
      'Crocodiles are ancient reptiles that float quietly in water like logs!',
    appearanceDescription:
      'Armor-plated green skin, powerful jaws, and a heavy tail.',
    traits: ['Powerful jaws', 'Floats like log', 'Armored scales'],
    color: '#166534',
    lightColor: '#DCFCE7',
    darkColor: '#14532D',
  },
];

// ─── INSECTS & SMALL ANIMALS ────────────────────────────────────────────────
export const INSECTS_DATA: readonly AnimalItem[] = [
  {
    id: 'butterfly',
    name: 'Butterfly',
    emoji: '🦋',
    category: 'insect',
    soundName: 'Flutter',
    soundOnomatopoeia: 'Flutter Flutter!',
    soundFrequencyHz: 600,
    habitat: 'forest',
    habitatDisplayName: 'Flower Gardens & Meadows',
    habitatEmoji: '🌸',
    food: 'plants',
    foodDisplayName: 'Sweet Flower Nectar',
    foodEmoji: '🌺',
    babyName: 'Caterpillar',
    simpleFact:
      'A butterfly starts as a caterpillar and grows beautiful wings inside a chrysalis!',
    appearanceDescription:
      'Large colorful wings with bright symmetrical patterns.',
    traits: ['Flutters gracefully', 'Drinks nectar', 'Colorful wings'],
    color: '#0284C7',
    lightColor: '#E0F2FE',
    darkColor: '#0369A1',
  },
  {
    id: 'bee',
    name: 'Honey Bee',
    emoji: '🐝',
    category: 'insect',
    soundName: 'Buzz',
    soundOnomatopoeia: 'Buzzz Buzzz!',
    soundFrequencyHz: 440,
    habitat: 'forest',
    habitatDisplayName: 'Beehives & Flower Meadows',
    habitatEmoji: '🌻',
    food: 'plants',
    foodDisplayName: 'Flower Pollen & Nectar',
    foodEmoji: '🍯',
    babyName: 'Larva',
    simpleFact:
      'Bees make sweet delicious honey and help colorful flowers grow!',
    appearanceDescription:
      'Yellow and black striped body with clear fast-buzzing wings.',
    traits: ['Makes honey', 'Pollinates flowers', 'Buzzes around'],
    color: '#EAB308',
    lightColor: '#FEF9C3',
    darkColor: '#A16207',
  },
  {
    id: 'ladybug',
    name: 'Ladybug',
    emoji: '🐞',
    category: 'insect',
    soundName: 'Crawl',
    soundOnomatopoeia: 'Crawl Tickle!',
    soundFrequencyHz: 520,
    habitat: 'forest',
    habitatDisplayName: 'Garden Leaves & Bushes',
    habitatEmoji: '🍃',
    food: 'insects',
    foodDisplayName: 'Tiny Plant Aphids',
    foodEmoji: '🌱',
    babyName: 'Larva',
    simpleFact:
      'Ladybugs have bright red shells with black polka dots to protect plants!',
    appearanceDescription: 'Bright red dome shell with black round spots.',
    traits: ['Red with black dots', 'Helps gardens', 'Cute crawler'],
    color: '#DC2626',
    lightColor: '#FEE2E2',
    darkColor: '#991B1B',
  },
  {
    id: 'ant',
    name: 'Ant',
    emoji: '🐜',
    category: 'insect',
    soundName: 'March',
    soundOnomatopoeia: 'March March!',
    soundFrequencyHz: 480,
    habitat: 'forest',
    habitatDisplayName: 'Underground Anthills',
    habitatEmoji: '🏜️',
    food: 'plants',
    foodDisplayName: 'Sweet Crumbs & Seeds',
    foodEmoji: '🍞',
    babyName: 'Larva',
    simpleFact:
      'Ants are super strong and can carry food 20 times heavier than themselves!',
    appearanceDescription:
      'Small black body with six busy legs and two feelers.',
    traits: ['Super strong', 'Team worker', 'Builds tunnels'],
    color: '#334155',
    lightColor: '#F1F5F9',
    darkColor: '#0F172A',
  },
  {
    id: 'caterpillar',
    name: 'Caterpillar',
    emoji: '🐛',
    category: 'insect',
    soundName: 'Munch',
    soundOnomatopoeia: 'Munch Munch!',
    soundFrequencyHz: 390,
    habitat: 'forest',
    habitatDisplayName: 'Green Plant Stems',
    habitatEmoji: '🌿',
    food: 'plants',
    foodDisplayName: 'Fresh Green Leaves',
    foodEmoji: '🍃',
    babyName: 'Egg',
    simpleFact:
      'Caterpillars love munching on green leaves before turning into butterflies!',
    appearanceDescription:
      'Long segmented green body with many tiny walking feet.',
    traits: ['Munches leaves', 'Becomes butterfly', 'Many feet'],
    color: '#65A30D',
    lightColor: '#ECFCCB',
    darkColor: '#3F6212',
  },
  {
    id: 'spider',
    name: 'Spider',
    emoji: '🕷️',
    category: 'insect',
    soundName: 'Spin',
    soundOnomatopoeia: 'Spin Weave!',
    soundFrequencyHz: 410,
    habitat: 'forest',
    habitatDisplayName: 'Corners & Tree Webs',
    habitatEmoji: '🕸️',
    food: 'insects',
    foodDisplayName: 'Flies caught in webs',
    foodEmoji: '🪰',
    babyName: 'Spiderling',
    simpleFact:
      'Spiders spin beautiful silky webs to catch pesky flying mosquitoes!',
    appearanceDescription: 'Round body with eight long jointed walking legs.',
    traits: ['8 legs', 'Spins silk webs', 'Catches flies'],
    color: '#1E293B',
    lightColor: '#F8FAFC',
    darkColor: '#0F172A',
  },
  {
    id: 'beetle',
    name: 'Beetle',
    emoji: '🪲',
    category: 'insect',
    soundName: 'Click',
    soundOnomatopoeia: 'Click Clack!',
    soundFrequencyHz: 370,
    habitat: 'forest',
    habitatDisplayName: 'Tree Bark & Soil',
    habitatEmoji: '🌲',
    food: 'plants',
    foodDisplayName: 'Wood Bark & Fallen Leaves',
    foodEmoji: '🍂',
    babyName: 'Grub',
    simpleFact:
      'Beetles have tough shiny armor shells that protect their wings underneath!',
    appearanceDescription:
      'Shiny metallic green or brown shell with strong front horns.',
    traits: ['Hard armor shell', 'Strong legs', 'Forest crawler'],
    color: '#0D9488',
    lightColor: '#CCFBF1',
    darkColor: '#115E59',
  },
];

// All animals combined catalog
export const ALL_ANIMALS: readonly AnimalItem[] = [
  ...LAND_ANIMALS,
  ...BIRDS_DATA,
  ...SEA_ANIMALS_DATA,
  ...AMPHIBIANS_REPTILES_DATA,
  ...INSECTS_DATA,
];

// ─── ANIMAL SOUNDS ITEMS ────────────────────────────────────────────────────
export const ANIMAL_SOUND_ITEMS: readonly AnimalSoundItem[] = [
  {
    id: 'sound_dog',
    animalId: 'dog',
    animalName: 'Dog',
    emoji: '🐶',
    soundText: 'Woof Woof!',
    promptAudio: 'What animal makes this sound: Woof Woof?',
    options: [
      {id: 'dog', name: 'Dog', emoji: '🐶'},
      {id: 'cat', name: 'Cat', emoji: '🐱'},
      {id: 'cow', name: 'Cow', emoji: '🐮'},
    ],
    correctAnimalId: 'dog',
  },
  {
    id: 'sound_cow',
    animalId: 'cow',
    animalName: 'Cow',
    emoji: '🐮',
    soundText: 'Moo Moo!',
    promptAudio: 'What animal says: Moo Moo?',
    options: [
      {id: 'horse', name: 'Horse', emoji: '🐴'},
      {id: 'cow', name: 'Cow', emoji: '🐮'},
      {id: 'lion', name: 'Lion', emoji: '🦁'},
    ],
    correctAnimalId: 'cow',
  },
  {
    id: 'sound_duck',
    animalId: 'duck',
    animalName: 'Duck',
    emoji: '🦆',
    soundText: 'Quack Quack!',
    promptAudio: 'Which bird says: Quack Quack?',
    options: [
      {id: 'owl', name: 'Owl', emoji: '🦉'},
      {id: 'duck', name: 'Duck', emoji: '🦆'},
      {id: 'eagle', name: 'Eagle', emoji: '🦅'},
    ],
    correctAnimalId: 'duck',
  },
  {
    id: 'sound_lion',
    animalId: 'lion',
    animalName: 'Lion',
    emoji: '🦁',
    soundText: 'Roaaar!',
    promptAudio: 'Who makes a loud Roaaar sound?',
    options: [
      {id: 'rabbit', name: 'Rabbit', emoji: '🐰'},
      {id: 'sheep', name: 'Sheep', emoji: '🐑'},
      {id: 'lion', name: 'Lion', emoji: '🦁'},
    ],
    correctAnimalId: 'lion',
  },
  {
    id: 'sound_cat',
    animalId: 'cat',
    animalName: 'Cat',
    emoji: '🐱',
    soundText: 'Meow Meow!',
    promptAudio: 'Which furry friend says: Meow Meow?',
    options: [
      {id: 'cat', name: 'Cat', emoji: '🐱'},
      {id: 'pig', name: 'Pig', emoji: '🐷'},
      {id: 'dog', name: 'Dog', emoji: '🐶'},
    ],
    correctAnimalId: 'cat',
  },
  {
    id: 'sound_rooster',
    animalId: 'rooster',
    animalName: 'Rooster',
    emoji: '🐓',
    soundText: 'Cock-a-doodle-doo!',
    promptAudio: 'Who crows Cock-a-doodle-doo in the morning?',
    options: [
      {id: 'rooster', name: 'Rooster', emoji: '🐓'},
      {id: 'peacock', name: 'Peacock', emoji: '🦚'},
      {id: 'frog', name: 'Frog', emoji: '🐸'},
    ],
    correctAnimalId: 'rooster',
  },
  {
    id: 'sound_frog',
    animalId: 'frog',
    animalName: 'Frog',
    emoji: '🐸',
    soundText: 'Ribbit Croak!',
    promptAudio: 'Who croaks: Ribbit Ribbit?',
    options: [
      {id: 'monkey', name: 'Monkey', emoji: '🐒'},
      {id: 'frog', name: 'Frog', emoji: '🐸'},
      {id: 'fish', name: 'Fish', emoji: '🐟'},
    ],
    correctAnimalId: 'frog',
  },
  {
    id: 'sound_bee',
    animalId: 'bee',
    animalName: 'Honey Bee',
    emoji: '🐝',
    soundText: 'Buzzz Buzzz!',
    promptAudio: 'Which busy insect goes: Buzzz Buzzz?',
    options: [
      {id: 'bee', name: 'Honey Bee', emoji: '🐝'},
      {id: 'butterfly', name: 'Butterfly', emoji: '🦋'},
      {id: 'ant', name: 'Ant', emoji: '🐜'},
    ],
    correctAnimalId: 'bee',
  },
];

// ─── HABITATS ITEMS ─────────────────────────────────────────────────────────
export const ANIMAL_HABITAT_ITEMS: readonly AnimalHabitatItem[] = [
  {
    id: 'hab_lion',
    animalId: 'lion',
    animalName: 'Lion',
    animalEmoji: '🦁',
    prompt: 'Where does the Lion live?',
    correctHabitat: 'grassland',
    correctHabitatName: 'Grassland / Savannah',
    correctHabitatEmoji: '🌾',
    options: [
      {id: 'grassland', name: 'Grassland', emoji: '🌾'},
      {id: 'ocean', name: 'Ocean', emoji: '🌊'},
      {id: 'polar', name: 'Polar Ice', emoji: '❄️'},
    ],
    explanation:
      'Lions live in sunny grassland savannahs where they can roam with their pride.',
  },
  {
    id: 'hab_dolphin',
    animalId: 'dolphin',
    animalName: 'Dolphin',
    animalEmoji: '🐬',
    prompt: 'Where does a Dolphin live?',
    correctHabitat: 'ocean',
    correctHabitatName: 'Ocean',
    correctHabitatEmoji: '🌊',
    options: [
      {id: 'desert', name: 'Desert', emoji: '🏜️'},
      {id: 'ocean', name: 'Ocean', emoji: '🌊'},
      {id: 'forest', name: 'Forest', emoji: '🌲'},
    ],
    explanation:
      'Dolphins live in the deep blue ocean where they swim and play in pods.',
  },
  {
    id: 'hab_penguin',
    animalId: 'penguin',
    animalName: 'Penguin',
    animalEmoji: '🐧',
    prompt: 'Where does a Penguin live?',
    correctHabitat: 'polar',
    correctHabitatName: 'Polar Region',
    correctHabitatEmoji: '❄️',
    options: [
      {id: 'desert', name: 'Desert', emoji: '🏜️'},
      {id: 'polar', name: 'Polar Ice', emoji: '❄️'},
      {id: 'forest', name: 'Jungle', emoji: '🌴'},
    ],
    explanation:
      'Penguins thrive in snowy, icy polar regions where they slide on glaciers.',
  },
  {
    id: 'hab_cow',
    animalId: 'cow',
    animalName: 'Cow',
    animalEmoji: '🐮',
    prompt: 'Where does a Cow live?',
    correctHabitat: 'farm',
    correctHabitatName: 'Farm',
    correctHabitatEmoji: '🏠',
    options: [
      {id: 'ocean', name: 'Ocean', emoji: '🌊'},
      {id: 'farm', name: 'Farm', emoji: '🏠'},
      {id: 'desert', name: 'Desert', emoji: '🏜️'},
    ],
    explanation:
      'Cows live happily on farms with grassy pastures and cozy barns.',
  },
  {
    id: 'hab_frog',
    animalId: 'frog',
    animalName: 'Frog',
    animalEmoji: '🐸',
    prompt: 'Where does a Frog live?',
    correctHabitat: 'river',
    correctHabitatName: 'Ponds & Streams',
    correctHabitatEmoji: '🏞️',
    options: [
      {id: 'polar', name: 'Polar Ice', emoji: '❄️'},
      {id: 'desert', name: 'Desert', emoji: '🏜️'},
      {id: 'river', name: 'Ponds & Streams', emoji: '🏞️'},
    ],
    explanation: 'Frogs live around freshwater ponds, rivers, and streams.',
  },
  {
    id: 'hab_monkey',
    animalId: 'monkey',
    animalName: 'Monkey',
    animalEmoji: '🐒',
    prompt: 'Where does a Monkey live?',
    correctHabitat: 'forest',
    correctHabitatName: 'Jungle Forest',
    correctHabitatEmoji: '🌳',
    options: [
      {id: 'forest', name: 'Jungle Forest', emoji: '🌳'},
      {id: 'polar', name: 'Polar Ice', emoji: '❄️'},
      {id: 'ocean', name: 'Ocean', emoji: '🌊'},
    ],
    explanation:
      'Monkeys live high in jungle tree canopies where they swing on branches.',
  },
];

// ─── ANIMAL DIETS ITEMS ─────────────────────────────────────────────────────
export const ANIMAL_DIET_ITEMS: readonly AnimalDietItem[] = [
  {
    id: 'diet_rabbit',
    animalId: 'rabbit',
    animalName: 'Rabbit',
    animalEmoji: '🐰',
    question: 'What does a Rabbit love to eat?',
    correctFood: 'plants',
    correctFoodName: 'Carrots & Greens',
    correctFoodEmoji: '🥕',
    options: [
      {id: 'plants', name: 'Carrots & Greens', emoji: '🥕'},
      {id: 'meat', name: 'Meat', emoji: '🍖'},
      {id: 'fish', name: 'Fish', emoji: '🐟'},
    ],
    explanation:
      'Rabbits are herbivores that love crunchy carrots and fresh green leaves!',
  },
  {
    id: 'diet_cow',
    animalId: 'cow',
    animalName: 'Cow',
    animalEmoji: '🐮',
    question: 'What does a Cow eat?',
    correctFood: 'grass',
    correctFoodName: 'Green Grass & Hay',
    correctFoodEmoji: '🌿',
    options: [
      {id: 'grass', name: 'Green Grass', emoji: '🌿'},
      {id: 'meat', name: 'Meat', emoji: '🍖'},
      {id: 'insects', name: 'Insects', emoji: '🪲'},
    ],
    explanation: 'Cows eat sweet green pasture grass and hay all day long!',
  },
  {
    id: 'diet_lion',
    animalId: 'lion',
    animalName: 'Lion',
    animalEmoji: '🦁',
    question: 'What does a Lion eat?',
    correctFood: 'meat',
    correctFoodName: 'Meat',
    correctFoodEmoji: '🍖',
    options: [
      {id: 'fruits', name: 'Bananas', emoji: '🍌'},
      {id: 'meat', name: 'Meat', emoji: '🍖'},
      {id: 'seeds', name: 'Seeds', emoji: '🌾'},
    ],
    explanation: 'Lions are strong carnivores that hunt and eat meat.',
  },
  {
    id: 'diet_monkey',
    animalId: 'monkey',
    animalName: 'Monkey',
    animalEmoji: '🐒',
    question: 'What does a Monkey love to snack on?',
    correctFood: 'fruits',
    correctFoodName: 'Bananas & Fruits',
    correctFoodEmoji: '🍌',
    options: [
      {id: 'fruits', name: 'Bananas & Fruits', emoji: '🍌'},
      {id: 'fish', name: 'Fish', emoji: '🐟'},
      {id: 'meat', name: 'Meat', emoji: '🍖'},
    ],
    explanation: 'Monkeys love sweet ripe bananas and juicy jungle fruits!',
  },
  {
    id: 'diet_cat',
    animalId: 'cat',
    animalName: 'Cat',
    animalEmoji: '🐱',
    question: 'What does a Cat love to eat?',
    correctFood: 'fish',
    correctFoodName: 'Fish & Milk',
    correctFoodEmoji: '🐟',
    options: [
      {id: 'grass', name: 'Grass', emoji: '🌿'},
      {id: 'fish', name: 'Fresh Fish', emoji: '🐟'},
      {id: 'bamboo', name: 'Bamboo', emoji: '🎋'},
    ],
    explanation: 'Cats love delicious fresh fish and protein-rich foods!',
  },
  {
    id: 'diet_bee',
    animalId: 'bee',
    animalName: 'Honey Bee',
    animalEmoji: '🐝',
    question: 'What do Honey Bees sip from flowers?',
    correctFood: 'plants',
    correctFoodName: 'Flower Nectar',
    correctFoodEmoji: '🌺',
    options: [
      {id: 'plants', name: 'Flower Nectar', emoji: '🌺'},
      {id: 'meat', name: 'Meat', emoji: '🍖'},
      {id: 'fish', name: 'Fish', emoji: '🐟'},
    ],
    explanation:
      'Bees drink sweet flower nectar and use it to make golden honey!',
  },
];

// ─── BABY ANIMALS ───────────────────────────────────────────────────────────
export const BABY_ANIMALS_DATA: readonly BabyAnimalItem[] = [
  {
    id: 'baby_dog',
    parentAnimalId: 'dog',
    parentName: 'Dog',
    parentEmoji: '🐶',
    babyName: 'Puppy',
    babyEmoji: '🐕',
    options: ['Puppy', 'Kitten', 'Calf'],
    correctBabyName: 'Puppy',
    fact: 'A baby dog is called a Puppy. Puppies love playing with bouncy balls!',
  },
  {
    id: 'baby_cat',
    parentAnimalId: 'cat',
    parentName: 'Cat',
    parentEmoji: '🐱',
    babyName: 'Kitten',
    babyEmoji: '🐈',
    options: ['Cub', 'Kitten', 'Chick'],
    correctBabyName: 'Kitten',
    fact: 'A baby cat is called a Kitten. Kittens love chasing fluffy yarn!',
  },
  {
    id: 'baby_cow',
    parentAnimalId: 'cow',
    parentName: 'Cow',
    parentEmoji: '🐮',
    babyName: 'Calf',
    babyEmoji: '🐄',
    options: ['Foal', 'Calf', 'Lamb'],
    correctBabyName: 'Calf',
    fact: 'A baby cow is called a Calf. Calves can stand up right after birth!',
  },
  {
    id: 'baby_horse',
    parentAnimalId: 'horse',
    parentName: 'Horse',
    parentEmoji: '🐴',
    babyName: 'Foal',
    babyEmoji: '🐎',
    options: ['Foal', 'Puppy', 'Cub'],
    correctBabyName: 'Foal',
    fact: 'A baby horse is called a Foal. Foals can gallop with their mothers within hours!',
  },
  {
    id: 'baby_sheep',
    parentAnimalId: 'sheep',
    parentName: 'Sheep',
    parentEmoji: '🐑',
    babyName: 'Lamb',
    babyEmoji: '🐏',
    options: ['Piglet', 'Lamb', 'Kitten'],
    correctBabyName: 'Lamb',
    fact: 'A baby sheep is called a Lamb. Lambs are super gentle with soft fluffy wool!',
  },
  {
    id: 'baby_hen',
    parentAnimalId: 'hen',
    parentName: 'Hen',
    parentEmoji: '🐔',
    babyName: 'Chick',
    babyEmoji: '🐣',
    options: ['Chick', 'Calf', 'Bunny'],
    correctBabyName: 'Chick',
    fact: 'A baby hen is called a Chick. Chicks hatch from warm eggs and chirp softly!',
  },
  {
    id: 'baby_lion',
    parentAnimalId: 'lion',
    parentName: 'Lion',
    parentEmoji: '🦁',
    babyName: 'Cub',
    babyEmoji: '🐯',
    options: ['Cub', 'Lamb', 'Foal'],
    correctBabyName: 'Cub',
    fact: 'A baby lion is called a Cub. Cubs practice roaring with gentle squeaks!',
  },
  {
    id: 'baby_pig',
    parentAnimalId: 'pig',
    parentName: 'Pig',
    parentEmoji: '🐷',
    babyName: 'Piglet',
    babyEmoji: '🐖',
    options: ['Piglet', 'Puppy', 'Chick'],
    correctBabyName: 'Piglet',
    fact: 'A baby pig is called a Piglet. Piglets are playful and stay close to mama pig!',
  },
];

// ─── ANIMAL MATCHING PAIRS ──────────────────────────────────────────────────
export const ANIMAL_MATCHING_PAIRS: readonly AnimalMatchingPair[] = [
  {
    id: 'match_1',
    leftLabel: 'Dog',
    leftEmoji: '🐶',
    rightLabel: 'Puppy',
    rightEmoji: '🐕',
    matchKey: 'dog_puppy',
    pairType: 'baby',
  },
  {
    id: 'match_2',
    leftLabel: 'Cow',
    leftEmoji: '🐮',
    rightLabel: 'Moo Moo',
    rightEmoji: '🔊',
    matchKey: 'cow_moo',
    pairType: 'sound',
  },
  {
    id: 'match_3',
    leftLabel: 'Dolphin',
    leftEmoji: '🐬',
    rightLabel: 'Ocean',
    rightEmoji: '🌊',
    matchKey: 'dolphin_ocean',
    pairType: 'habitat',
  },
  {
    id: 'match_4',
    leftLabel: 'Rabbit',
    leftEmoji: '🐰',
    rightLabel: 'Carrot',
    rightEmoji: '🥕',
    matchKey: 'rabbit_carrot',
    pairType: 'food',
  },
  {
    id: 'match_5',
    leftLabel: 'Peacock',
    leftEmoji: '🦚',
    rightLabel: 'Bird',
    rightEmoji: '🪶',
    matchKey: 'peacock_bird',
    pairType: 'category',
  },
];

// ─── CLASSIFICATION ITEMS ───────────────────────────────────────────────────
export const ANIMAL_CLASSIFICATION_ITEMS: readonly AnimalClassificationItem[] =
  [
    {
      id: 'class_fly',
      traitCategory: 'can_fly',
      question: 'Which animals can FLY in the sky?',
      promptAudio: 'Tap the animals that can fly in the sky!',
      targetAnimalIds: ['parrot', 'eagle', 'butterfly'],
      options: [
        {id: 'parrot', name: 'Parrot', emoji: '🦜', matches: true},
        {id: 'elephant', name: 'Elephant', emoji: '🐘', matches: false},
        {id: 'eagle', name: 'Eagle', emoji: '🦅', matches: true},
        {id: 'dog', name: 'Dog', emoji: '🐶', matches: false},
        {id: 'butterfly', name: 'Butterfly', emoji: '🦋', matches: true},
        {id: 'cow', name: 'Cow', emoji: '🐮', matches: false},
      ],
    },
    {
      id: 'class_water',
      traitCategory: 'lives_in_water',
      question: 'Which animals LIVE in the WATER?',
      promptAudio: 'Tap the animals that live in water!',
      targetAnimalIds: ['dolphin', 'whale', 'fish', 'octopus'],
      options: [
        {id: 'dolphin', name: 'Dolphin', emoji: '🐬', matches: true},
        {id: 'lion', name: 'Lion', emoji: '🦁', matches: false},
        {id: 'fish', name: 'Fish', emoji: '🐟', matches: true},
        {id: 'horse', name: 'Horse', emoji: '🐴', matches: false},
        {id: 'octopus', name: 'Octopus', emoji: '🐙', matches: true},
        {id: 'rabbit', name: 'Rabbit', emoji: '🐰', matches: false},
      ],
    },
    {
      id: 'class_farm',
      traitCategory: 'farm_animals',
      question: 'Which animals live on a FARM?',
      promptAudio: 'Tap the friendly farm animals!',
      targetAnimalIds: ['cow', 'pig', 'sheep', 'hen'],
      options: [
        {id: 'cow', name: 'Cow', emoji: '🐮', matches: true},
        {id: 'shark', name: 'Shark', emoji: '🦈', matches: false},
        {id: 'sheep', name: 'Sheep', emoji: '🐑', matches: true},
        {id: 'tiger', name: 'Tiger', emoji: '🐯', matches: false},
        {id: 'hen', name: 'Hen', emoji: '🐔', matches: true},
        {id: 'penguin', name: 'Penguin', emoji: '🐧', matches: false},
      ],
    },
  ];

// ─── VISUAL COUNTING ITEMS ──────────────────────────────────────────────────
export const ANIMAL_COUNT_ITEMS: readonly AnimalCountItem[] = [
  {
    id: 'cnt_fish',
    targetAnimalId: 'fish',
    targetAnimalName: 'Fish',
    targetEmoji: '🐟',
    correctCount: 4,
    displayedItems: [
      {id: 'f1', animalId: 'fish', emoji: '🐟'},
      {id: 'f2', animalId: 'fish', emoji: '🐟'},
      {id: 'c1', animalId: 'crab', emoji: '🦀'},
      {id: 'f3', animalId: 'fish', emoji: '🐟'},
      {id: 'f4', animalId: 'fish', emoji: '🐟'},
      {id: 's1', animalId: 'starfish', emoji: '⭐'},
    ],
    options: [3, 4, 5],
  },
  {
    id: 'cnt_duck',
    targetAnimalId: 'duck',
    targetAnimalName: 'Ducks',
    targetEmoji: '🦆',
    correctCount: 5,
    displayedItems: [
      {id: 'd1', animalId: 'duck', emoji: '🦆'},
      {id: 'd2', animalId: 'duck', emoji: '🦆'},
      {id: 'f1', animalId: 'frog', emoji: '🐸'},
      {id: 'd3', animalId: 'duck', emoji: '🦆'},
      {id: 'd4', animalId: 'duck', emoji: '🦆'},
      {id: 'd5', animalId: 'duck', emoji: '🦆'},
    ],
    options: [4, 5, 6],
  },
  {
    id: 'cnt_rabbit',
    targetAnimalId: 'rabbit',
    targetAnimalName: 'Rabbits',
    targetEmoji: '🐰',
    correctCount: 3,
    displayedItems: [
      {id: 'r1', animalId: 'rabbit', emoji: '🐰'},
      {id: 'd1', animalId: 'dog', emoji: '🐶'},
      {id: 'r2', animalId: 'rabbit', emoji: '🐰'},
      {id: 'c1', animalId: 'cat', emoji: '🐱'},
      {id: 'r3', animalId: 'rabbit', emoji: '🐰'},
    ],
    options: [2, 3, 4],
  },
  {
    id: 'cnt_butterfly',
    targetAnimalId: 'butterfly',
    targetAnimalName: 'Butterflies',
    targetEmoji: '🦋',
    correctCount: 6,
    displayedItems: [
      {id: 'b1', animalId: 'butterfly', emoji: '🦋'},
      {id: 'b2', animalId: 'butterfly', emoji: '🦋'},
      {id: 'be1', animalId: 'bee', emoji: '🐝'},
      {id: 'b3', animalId: 'butterfly', emoji: '🦋'},
      {id: 'b4', animalId: 'butterfly', emoji: '🦋'},
      {id: 'b5', animalId: 'butterfly', emoji: '🦋'},
      {id: 'b6', animalId: 'butterfly', emoji: '🦋'},
    ],
    options: [5, 6, 7],
  },
];

// ─── ANIMAL PATTERNS ────────────────────────────────────────────────────────
export const ANIMAL_PATTERNS: readonly AnimalPatternItem[] = [
  {
    id: 'pat_1',
    patternType: 'AB',
    sequence: [
      {animalId: 'dog', emoji: '🐶'},
      {animalId: 'cat', emoji: '🐱'},
      {animalId: 'dog', emoji: '🐶'},
      {animalId: 'cat', emoji: '🐱'},
    ],
    correctAnimalId: 'dog',
    correctEmoji: '🐶',
    options: [
      {animalId: 'dog', emoji: '🐶'},
      {animalId: 'cat', emoji: '🐱'},
      {animalId: 'lion', emoji: '🦁'},
    ],
  },
  {
    id: 'pat_2',
    patternType: 'AAB',
    sequence: [
      {animalId: 'fish', emoji: '🐟'},
      {animalId: 'fish', emoji: '🐟'},
      {animalId: 'dolphin', emoji: '🐬'},
      {animalId: 'fish', emoji: '🐟'},
      {animalId: 'fish', emoji: '🐟'},
    ],
    correctAnimalId: 'dolphin',
    correctEmoji: '🐬',
    options: [
      {animalId: 'fish', emoji: '🐟'},
      {animalId: 'dolphin', emoji: '🐬'},
      {animalId: 'crab', emoji: '🦀'},
    ],
  },
  {
    id: 'pat_3',
    patternType: 'ABC',
    sequence: [
      {animalId: 'lion', emoji: '🦁'},
      {animalId: 'elephant', emoji: '🐘'},
      {animalId: 'monkey', emoji: '🐒'},
      {animalId: 'lion', emoji: '🦁'},
      {animalId: 'elephant', emoji: '🐘'},
    ],
    correctAnimalId: 'monkey',
    correctEmoji: '🐒',
    options: [
      {animalId: 'lion', emoji: '🦁'},
      {animalId: 'elephant', emoji: '🐘'},
      {animalId: 'monkey', emoji: '🐒'},
    ],
  },
  {
    id: 'pat_4',
    patternType: 'AABB',
    sequence: [
      {animalId: 'bird', emoji: '🐦'},
      {animalId: 'bird', emoji: '🐦'},
      {animalId: 'duck', emoji: '🦆'},
      {animalId: 'duck', emoji: '🦆'},
      {animalId: 'bird', emoji: '🐦'},
    ],
    correctAnimalId: 'bird',
    correctEmoji: '🐦',
    options: [
      {animalId: 'bird', emoji: '🐦'},
      {animalId: 'duck', emoji: '🦆'},
      {animalId: 'owl', emoji: '🦉'},
    ],
  },
];

// ─── VISUAL PUZZLES (ODD-ONE-OUT) ───────────────────────────────────────────
export const ANIMAL_PUZZLES: readonly AnimalPuzzleItem[] = [
  {
    id: 'puz_1',
    prompt: 'Which animal is DIFFERENT from the land animals?',
    items: [
      {id: 'i1', animalId: 'dog', name: 'Dog', emoji: '🐶', category: 'land'},
      {id: 'i2', animalId: 'cat', name: 'Cat', emoji: '🐱', category: 'land'},
      {
        id: 'i3',
        animalId: 'rabbit',
        name: 'Rabbit',
        emoji: '🐰',
        category: 'land',
      },
      {id: 'i4', animalId: 'fish', name: 'Fish', emoji: '🐟', category: 'sea'},
    ],
    answerId: 'i4',
    explanation:
      'The fish lives in the water and swims, while the other three are land animals!',
  },
  {
    id: 'puz_2',
    prompt: 'Which animal belongs in the OCEAN?',
    items: [
      {id: 'p1', animalId: 'cow', name: 'Cow', emoji: '🐮', category: 'farm'},
      {
        id: 'p2',
        animalId: 'dolphin',
        name: 'Dolphin',
        emoji: '🐬',
        category: 'ocean',
      },
      {
        id: 'p3',
        animalId: 'horse',
        name: 'Horse',
        emoji: '🐴',
        category: 'farm',
      },
      {
        id: 'p4',
        animalId: 'sheep',
        name: 'Sheep',
        emoji: '🐑',
        category: 'farm',
      },
    ],
    answerId: 'p2',
    explanation:
      'The dolphin is an ocean animal, while the others live on a farm!',
  },
  {
    id: 'puz_3',
    prompt: 'Which creature can FLY in the air?',
    items: [
      {
        id: 'f1',
        animalId: 'elephant',
        name: 'Elephant',
        emoji: '🐘',
        category: 'land',
      },
      {id: 'f2', animalId: 'lion', name: 'Lion', emoji: '🦁', category: 'land'},
      {
        id: 'f3',
        animalId: 'eagle',
        name: 'Eagle',
        emoji: '🦅',
        category: 'bird',
      },
      {id: 'f4', animalId: 'bear', name: 'Bear', emoji: '🐻', category: 'land'},
    ],
    answerId: 'f3',
    explanation: 'The eagle has large wings and can fly high in the air!',
  },
  {
    id: 'puz_4',
    prompt: 'Which animal has EIGHT arms?',
    items: [
      {
        id: 'o1',
        animalId: 'octopus',
        name: 'Octopus',
        emoji: '🐙',
        category: 'sea',
      },
      {
        id: 'o2',
        animalId: 'turtle',
        name: 'Turtle',
        emoji: '🐢',
        category: 'sea',
      },
      {
        id: 'o3',
        animalId: 'whale',
        name: 'Whale',
        emoji: '🐋',
        category: 'sea',
      },
      {id: 'o4', animalId: 'fish', name: 'Fish', emoji: '🐟', category: 'sea'},
    ],
    answerId: 'o1',
    explanation: 'An octopus has 8 flexible waving arms with suckers!',
  },
];

// ─── SUBMODULE MINI QUIZZES & GRAND CHALLENGE ───────────────────────────────
export const ANIMAL_QUIZZES: Record<string, readonly AnimalQuizQuestion[]> = {
  meet_animals: [
    {
      id: 'q_meet_1',
      type: 'identification',
      question: 'What animal is this?',
      targetEmoji: '🐘',
      promptAudio: 'What animal is this with a long trunk?',
      options: [
        {id: 'elephant', text: 'Elephant', emoji: '🐘'},
        {id: 'lion', text: 'Lion', emoji: '🦁'},
        {id: 'horse', text: 'Horse', emoji: '🐴'},
      ],
      answerId: 'elephant',
      explanation: 'That is an Elephant! It has a long trunk and large ears.',
    },
    {
      id: 'q_meet_2',
      type: 'sound',
      question: 'What sound does a dog make?',
      targetEmoji: '🐶',
      promptAudio: 'What sound does a dog make?',
      options: [
        {id: 'bark', text: 'Woof Woof!', emoji: '🐶'},
        {id: 'meow', text: 'Meow Meow!', emoji: '🐱'},
        {id: 'moo', text: 'Moo Moo!', emoji: '🐮'},
      ],
      answerId: 'bark',
      explanation: 'Dogs bark with a happy Woof Woof!',
    },
    {
      id: 'q_meet_3',
      type: 'habitat',
      question: 'Where does a lion live?',
      targetEmoji: '🦁',
      promptAudio: 'Where does a lion live?',
      options: [
        {id: 'grassland', text: 'Savannah Grassland', emoji: '🌾'},
        {id: 'ocean', text: 'Deep Ocean', emoji: '🌊'},
        {id: 'polar', text: 'Polar Ice', emoji: '❄️'},
      ],
      answerId: 'grassland',
      explanation: 'Lions live in wide savannah grasslands!',
    },
  ],
  land_animals: [
    {
      id: 'q_land_1',
      type: 'identification',
      question: 'Which animal is the King of the Jungle?',
      targetEmoji: '👑',
      promptAudio: 'Which animal is the King of the Jungle with a furry mane?',
      options: [
        {id: 'lion', text: 'Lion', emoji: '🦁'},
        {id: 'rabbit', text: 'Rabbit', emoji: '🐰'},
        {id: 'pig', text: 'Pig', emoji: '🐷'},
      ],
      answerId: 'lion',
      explanation: 'The brave lion is known as the King of the Jungle!',
    },
    {
      id: 'q_land_2',
      type: 'fact',
      question: 'Which is the tallest animal with a long neck?',
      targetEmoji: '🦒',
      promptAudio: 'Which is the tallest animal in the world?',
      options: [
        {id: 'giraffe', text: 'Giraffe', emoji: '🦒'},
        {id: 'dog', text: 'Dog', emoji: '🐶'},
        {id: 'sheep', text: 'Sheep', emoji: '🐑'},
      ],
      answerId: 'giraffe',
      explanation:
        'Giraffes are the tallest animals with long necks to reach high tree leaves!',
    },
    {
      id: 'q_land_3',
      type: 'food',
      question: 'What does a monkey love to eat?',
      targetEmoji: '🐒',
      promptAudio: 'What does a monkey love to eat?',
      options: [
        {id: 'banana', text: 'Sweet Bananas', emoji: '🍌'},
        {id: 'meat', text: 'Meat', emoji: '🍖'},
        {id: 'fish', text: 'Fish', emoji: '🐟'},
      ],
      answerId: 'banana',
      explanation: 'Monkeys love sweet yellow bananas and fresh jungle fruits!',
    },
  ],
  birds: [
    {
      id: 'q_bird_1',
      type: 'identification',
      question: 'Which bird has colorful fan tail feathers?',
      targetEmoji: '🦚',
      promptAudio: 'Which bird opens colorful fan tail feathers?',
      options: [
        {id: 'peacock', text: 'Peacock', emoji: '🦚'},
        {id: 'sparrow', text: 'Sparrow', emoji: '🐦'},
        {id: 'hen', text: 'Hen', emoji: '🐔'},
      ],
      answerId: 'peacock',
      explanation:
        'The peacock opens its gorgeous tail feathers like a giant fan!',
    },
    {
      id: 'q_bird_2',
      type: 'fact',
      question: 'Which bird swims in icy cold polar waters?',
      targetEmoji: '❄️',
      promptAudio: 'Which bird swims in icy cold waters and waddles?',
      options: [
        {id: 'penguin', text: 'Penguin', emoji: '🐧'},
        {id: 'parrot', text: 'Parrot', emoji: '🦜'},
        {id: 'owl', text: 'Owl', emoji: '🦉'},
      ],
      answerId: 'penguin',
      explanation:
        'Penguins are great swimmers that live in cold snowy polar regions!',
    },
    {
      id: 'q_bird_3',
      type: 'sound',
      question: 'Which bird says "Quack Quack"?',
      targetEmoji: '🦆',
      promptAudio: 'Which bird says Quack Quack?',
      options: [
        {id: 'duck', text: 'Duck', emoji: '🦆'},
        {id: 'eagle', text: 'Eagle', emoji: '🦅'},
        {id: 'turkey', text: 'Turkey', emoji: '🦃'},
      ],
      answerId: 'duck',
      explanation: 'Ducks swim in ponds and make a cheerful Quack Quack sound!',
    },
  ],
  sea_animals: [
    {
      id: 'q_sea_1',
      type: 'identification',
      question: 'Which is the biggest animal in the world?',
      targetEmoji: '🐋',
      promptAudio: 'Which is the biggest animal in the world?',
      options: [
        {id: 'whale', text: 'Blue Whale', emoji: '🐋'},
        {id: 'crab', text: 'Crab', emoji: '🦀'},
        {id: 'fish', text: 'Fish', emoji: '🐟'},
      ],
      answerId: 'whale',
      explanation:
        'The Blue Whale is the largest animal to ever live on Earth!',
    },
    {
      id: 'q_sea_2',
      type: 'fact',
      question: 'How many arms does an octopus have?',
      targetEmoji: '🐙',
      promptAudio: 'How many arms does an octopus have?',
      options: [
        {id: '8', text: '8 Arms', emoji: '🐙'},
        {id: '4', text: '4 Arms', emoji: '🐾'},
        {id: '2', text: '2 Arms', emoji: '🪶'},
      ],
      answerId: '8',
      explanation:
        'An octopus has 8 flexible waving arms covered in suction cups!',
    },
    {
      id: 'q_sea_3',
      type: 'identification',
      question: 'Which sea animal is playful and jumps out of waves?',
      targetEmoji: '🐬',
      promptAudio: 'Which sea animal is playful and jumps out of waves?',
      options: [
        {id: 'dolphin', text: 'Dolphin', emoji: '🐬'},
        {id: 'starfish', text: 'Starfish', emoji: '⭐'},
        {id: 'shrimp', text: 'Shrimp', emoji: '🦐'},
      ],
      answerId: 'dolphin',
      explanation:
        'Dolphins are intelligent, friendly, and love leaping out of the water!',
    },
  ],
  challenge: [
    {
      id: 'ch_1',
      type: 'identification',
      question: 'Which of these is a BIRD?',
      targetEmoji: '🪶',
      promptAudio: 'Which of these is a bird that can fly?',
      options: [
        {id: 'parrot', text: 'Parrot', emoji: '🦜'},
        {id: 'elephant', text: 'Elephant', emoji: '🐘'},
        {id: 'shark', text: 'Shark', emoji: '🦈'},
      ],
      answerId: 'parrot',
      explanation: 'A parrot is a colorful bird with feathers and wings!',
    },
    {
      id: 'ch_2',
      type: 'habitat',
      question: 'Where does a Dolphin live?',
      targetEmoji: '🐬',
      promptAudio: 'Where does a Dolphin live?',
      options: [
        {id: 'ocean', text: 'In the Ocean', emoji: '🌊'},
        {id: 'desert', text: 'In the Desert', emoji: '🏜️'},
        {id: 'trees', text: 'In the Trees', emoji: '🌲'},
      ],
      answerId: 'ocean',
      explanation: 'Dolphins live and swim in the ocean!',
    },
    {
      id: 'ch_3',
      type: 'sound',
      question: 'Which animal says "Moo Moo"?',
      targetEmoji: '🐮',
      promptAudio: 'Which friendly farm animal says Moo Moo?',
      options: [
        {id: 'cow', text: 'Cow', emoji: '🐮'},
        {id: 'horse', text: 'Horse', emoji: '🐴'},
        {id: 'lion', text: 'Lion', emoji: '🦁'},
      ],
      answerId: 'cow',
      explanation: 'Cows moo and give us fresh milk!',
    },
    {
      id: 'ch_4',
      type: 'baby',
      question: 'What is a baby dog called?',
      targetEmoji: '🐶',
      promptAudio: 'What is a baby dog called?',
      options: [
        {id: 'puppy', text: 'Puppy', emoji: '🐕'},
        {id: 'kitten', text: 'Kitten', emoji: '🐈'},
        {id: 'calf', text: 'Calf', emoji: '🐄'},
      ],
      answerId: 'puppy',
      explanation: 'A baby dog is a cute and playful Puppy!',
    },
    {
      id: 'ch_5',
      type: 'food',
      question: 'What does a rabbit love to eat?',
      targetEmoji: '🐰',
      promptAudio: 'What does a rabbit love to eat?',
      options: [
        {id: 'carrot', text: 'Carrots & Grass', emoji: '🥕'},
        {id: 'fish', text: 'Fish', emoji: '🐟'},
        {id: 'meat', text: 'Meat', emoji: '🍖'},
      ],
      answerId: 'carrot',
      explanation: 'Rabbits love munching on carrots and fresh greens!',
    },
  ],
};
