import type {
  AlphabetLetter,
  BeginningSoundItem,
  BlendingWordItem,
  CVCWordItem,
  EnglishQuizQuestion,
  LetterMatchPair,
  LetterObjectItem,
  LetterSoundItem,
  PhonicsItem,
  SentenceReadingItem,
  ShortStoryItem,
  SightWordItem,
  SubModuleConfig,
  TongueTwisterItem,
  WordBuildingTask,
} from '../entities/englishEntities';

// ─── 1. Sub-module Configurations ─────────────────────────────────────────────
export const ENGLISH_SUB_MODULES: readonly SubModuleConfig[] = [
  {
    id: 'alphabet',
    titleKey: 'english.submodules.alphabet',
    subtitleKey: 'english.submodules.alphabetSub',
    emoji: '🔤',
    accentColor: '#3B82F6',
    bgLightColor: '#EFF6FF',
    orderIndex: 1,
    routeName: 'Alphabet',
  },
  {
    id: 'capital_small',
    titleKey: 'english.submodules.capitalSmall',
    subtitleKey: 'english.submodules.capitalSmallSub',
    emoji: '🔠',
    accentColor: '#8B5CF6',
    bgLightColor: '#F5F3FF',
    orderIndex: 2,
    routeName: 'CapitalSmall',
  },
  {
    id: 'letter_sounds',
    titleKey: 'english.submodules.letterSounds',
    subtitleKey: 'english.submodules.letterSoundsSub',
    emoji: '🔊',
    accentColor: '#EC4899',
    bgLightColor: '#FDF2F8',
    orderIndex: 3,
    routeName: 'LetterSounds',
  },
  {
    id: 'letter_objects',
    titleKey: 'english.submodules.letterObjects',
    subtitleKey: 'english.submodules.letterObjectsSub',
    emoji: '🖼️',
    accentColor: '#10B981',
    bgLightColor: '#ECFDF5',
    orderIndex: 4,
    routeName: 'LetterObjects',
  },
  {
    id: 'beginning_sounds',
    titleKey: 'english.submodules.beginningSounds',
    subtitleKey: 'english.submodules.beginningSoundsSub',
    emoji: '👂',
    accentColor: '#F59E0B',
    bgLightColor: '#FFFBEB',
    orderIndex: 5,
    routeName: 'BeginningSounds',
  },
  {
    id: 'phonics',
    titleKey: 'english.submodules.phonics',
    subtitleKey: 'english.submodules.phonicsSub',
    emoji: '🧩',
    accentColor: '#06B6D4',
    bgLightColor: '#ECFEFF',
    orderIndex: 6,
    routeName: 'Phonics',
  },
  {
    id: 'sound_blending',
    titleKey: 'english.submodules.soundBlending',
    subtitleKey: 'english.submodules.soundBlendingSub',
    emoji: '🔗',
    accentColor: '#6366F1',
    bgLightColor: '#EEF2FF',
    orderIndex: 7,
    routeName: 'SoundBlending',
  },
  {
    id: 'word_building',
    titleKey: 'english.submodules.wordBuilding',
    subtitleKey: 'english.submodules.wordBuildingSub',
    emoji: '📝',
    accentColor: '#F97316',
    bgLightColor: '#FFF7ED',
    orderIndex: 8,
    routeName: 'WordBuilding',
  },
  {
    id: 'cvc_words',
    titleKey: 'english.submodules.cvcWords',
    subtitleKey: 'english.submodules.cvcWordsSub',
    emoji: '📖',
    accentColor: '#E11D48',
    bgLightColor: '#FFF1F2',
    orderIndex: 9,
    routeName: 'CVCWords',
  },
  {
    id: 'sight_words',
    titleKey: 'english.submodules.sightWords',
    subtitleKey: 'english.submodules.sightWordsSub',
    emoji: '⭐',
    accentColor: '#D97706',
    bgLightColor: '#FEF3C7',
    orderIndex: 10,
    routeName: 'SightWords',
  },
  {
    id: 'tongue_twisters',
    titleKey: 'english.submodules.tongueTwisters',
    subtitleKey: 'english.submodules.tongueTwistersSub',
    emoji: '👅',
    accentColor: '#84CC16',
    bgLightColor: '#F7FEE7',
    orderIndex: 11,
    routeName: 'TongueTwisters',
  },
  {
    id: 'sentence_reading',
    titleKey: 'english.submodules.sentenceReading',
    subtitleKey: 'english.submodules.sentenceReadingSub',
    emoji: '📚',
    accentColor: '#2563EB',
    bgLightColor: '#EFF6FF',
    orderIndex: 12,
    routeName: 'SentenceReading',
  },
  {
    id: 'short_stories',
    titleKey: 'english.submodules.shortStories',
    subtitleKey: 'english.submodules.shortStoriesSub',
    emoji: '📖',
    accentColor: '#9333EA',
    bgLightColor: '#FAF5FF',
    orderIndex: 13,
    routeName: 'ShortStories',
  },
  {
    id: 'reading_challenge',
    titleKey: 'english.submodules.readingChallenge',
    subtitleKey: 'english.submodules.readingChallengeSub',
    emoji: '🏆',
    accentColor: '#EA580C',
    bgLightColor: '#FFF7ED',
    orderIndex: 14,
    routeName: 'ReadingChallenge',
  },
];

// ─── 2. Alphabet A–Z Catalog ──────────────────────────────────────────────────
export const ALPHABET_LETTERS: readonly AlphabetLetter[] = [
  {
    id: 'letter_a',
    upper: 'A',
    lower: 'a',
    soundIpa: '/æ/',
    soundHint: 'a as in Apple',
    word: 'Apple',
    emoji: '🍎',
    sentence: 'A is for Apple. Red and sweet!',
    audioSpeech: 'Letter A. A says ah. Apple.',
    color: '#EF4444',
  },
  {
    id: 'letter_b',
    upper: 'B',
    lower: 'b',
    soundIpa: '/b/',
    soundHint: 'b as in Ball',
    word: 'Ball',
    emoji: '⚽',
    sentence: 'B is for Ball. Bounce the ball!',
    audioSpeech: 'Letter B. B says buh. Ball.',
    color: '#3B82F6',
  },
  {
    id: 'letter_c',
    upper: 'C',
    lower: 'c',
    soundIpa: '/k/',
    soundHint: 'c as in Cat',
    word: 'Cat',
    emoji: '🐱',
    sentence: 'C is for Cat. The cat says meow!',
    audioSpeech: 'Letter C. C says kuh. Cat.',
    color: '#F59E0B',
  },
  {
    id: 'letter_d',
    upper: 'D',
    lower: 'd',
    soundIpa: '/d/',
    soundHint: 'd as in Dog',
    word: 'Dog',
    emoji: '🐶',
    sentence: 'D is for Dog. The dog wags its tail!',
    audioSpeech: 'Letter D. D says duh. Dog.',
    color: '#10B981',
  },
  {
    id: 'letter_e',
    upper: 'E',
    lower: 'e',
    soundIpa: '/e/',
    soundHint: 'e as in Egg',
    word: 'Egg',
    emoji: '🥚',
    sentence: 'E is for Egg. An egg in a nest!',
    audioSpeech: 'Letter E. E says eh. Egg.',
    color: '#8B5CF6',
  },
  {
    id: 'letter_f',
    upper: 'F',
    lower: 'f',
    soundIpa: '/f/',
    soundHint: 'f as in Fish',
    word: 'Fish',
    emoji: '🐟',
    sentence: 'F is for Fish. Fish can swim fast!',
    audioSpeech: 'Letter F. F says fff. Fish.',
    color: '#06B6D4',
  },
  {
    id: 'letter_g',
    upper: 'G',
    lower: 'g',
    soundIpa: '/g/',
    soundHint: 'g as in Guitar',
    word: 'Guitar',
    emoji: '🎸',
    sentence: 'G is for Guitar. Play sweet music!',
    audioSpeech: 'Letter G. G says guh. Guitar.',
    color: '#EC4899',
  },
  {
    id: 'letter_h',
    upper: 'H',
    lower: 'h',
    soundIpa: '/h/',
    soundHint: 'h as in Hat',
    word: 'Hat',
    emoji: '🎩',
    sentence: 'H is for Hat. Wear a cool hat!',
    audioSpeech: 'Letter H. H says huh. Hat.',
    color: '#6366F1',
  },
  {
    id: 'letter_i',
    upper: 'I',
    lower: 'i',
    soundIpa: '/ɪ/',
    soundHint: 'i as in Igloo',
    word: 'Igloo',
    emoji: '🏠',
    sentence: 'I is for Igloo. A home of ice!',
    audioSpeech: 'Letter I. I says ih. Igloo.',
    color: '#14B8A6',
  },
  {
    id: 'letter_j',
    upper: 'J',
    lower: 'j',
    soundIpa: '/dʒ/',
    soundHint: 'j as in Jam',
    word: 'Jam',
    emoji: '🍓',
    sentence: 'J is for Jam. Sweet strawberry jam!',
    audioSpeech: 'Letter J. J says juh. Jam.',
    color: '#F97316',
  },
  {
    id: 'letter_k',
    upper: 'K',
    lower: 'k',
    soundIpa: '/k/',
    soundHint: 'k as in Kite',
    word: 'Kite',
    emoji: '🪁',
    sentence: 'K is for Kite. Fly the kite high!',
    audioSpeech: 'Letter K. K says kuh. Kite.',
    color: '#84CC16',
  },
  {
    id: 'letter_l',
    upper: 'L',
    lower: 'l',
    soundIpa: '/l/',
    soundHint: 'l as in Lion',
    word: 'Lion',
    emoji: '🦁',
    sentence: 'L is for Lion. King of the jungle!',
    audioSpeech: 'Letter L. L says lll. Lion.',
    color: '#EAB308',
  },
  {
    id: 'letter_m',
    upper: 'M',
    lower: 'm',
    soundIpa: '/m/',
    soundHint: 'm as in Moon',
    word: 'Moon',
    emoji: '🌙',
    sentence: 'M is for Moon. Shines at night!',
    audioSpeech: 'Letter M. M says mmm. Moon.',
    color: '#6366F1',
  },
  {
    id: 'letter_n',
    upper: 'N',
    lower: 'n',
    soundIpa: '/n/',
    soundHint: 'n as in Nest',
    word: 'Nest',
    emoji: '🪺',
    sentence: 'N is for Nest. Bird in a nest!',
    audioSpeech: 'Letter N. N says nnn. Nest.',
    color: '#0EA5E9',
  },
  {
    id: 'letter_o',
    upper: 'O',
    lower: 'o',
    soundIpa: '/ɒ/',
    soundHint: 'o as in Orange',
    word: 'Orange',
    emoji: '🍊',
    sentence: 'O is for Orange. Juicy and round!',
    audioSpeech: 'Letter O. O says ah. Orange.',
    color: '#F97316',
  },
  {
    id: 'letter_p',
    upper: 'P',
    lower: 'p',
    soundIpa: '/p/',
    soundHint: 'p as in Pig',
    word: 'Pig',
    emoji: '🐷',
    sentence: 'P is for Pig. Happy little pig!',
    audioSpeech: 'Letter P. P says puh. Pig.',
    color: '#F43F5E',
  },
  {
    id: 'letter_q',
    upper: 'Q',
    lower: 'q',
    soundIpa: '/kw/',
    soundHint: 'q as in Queen',
    word: 'Queen',
    emoji: '👑',
    sentence: 'Q is for Queen. With a shiny crown!',
    audioSpeech: 'Letter Q. Q says kwuh. Queen.',
    color: '#A855F7',
  },
  {
    id: 'letter_r',
    upper: 'R',
    lower: 'r',
    soundIpa: '/r/',
    soundHint: 'r as in Sun Rainbow',
    word: 'Rainbow',
    emoji: '🌈',
    sentence: 'R is for Rainbow. Bright seven colors!',
    audioSpeech: 'Letter R. R says rrr. Rainbow.',
    color: '#EC4899',
  },
  {
    id: 'letter_s',
    upper: 'S',
    lower: 's',
    soundIpa: '/s/',
    soundHint: 's as in Sun',
    word: 'Sun',
    emoji: '☀️',
    sentence: 'S is for Sun. Warm and bright!',
    audioSpeech: 'Letter S. S says sss. Sun.',
    color: '#EAB308',
  },
  {
    id: 'letter_t',
    upper: 'T',
    lower: 't',
    soundIpa: '/t/',
    soundHint: 't as in Tree',
    word: 'Tree',
    emoji: '🌳',
    sentence: 'T is for Tree. Tall green tree!',
    audioSpeech: 'Letter T. T says tuh. Tree.',
    color: '#10B981',
  },
  {
    id: 'letter_u',
    upper: 'U',
    lower: 'u',
    soundIpa: '/ʌ/',
    soundHint: 'u as in Umbrella',
    word: 'Umbrella',
    emoji: '☂️',
    sentence: 'U is for Umbrella. Keeps us dry!',
    audioSpeech: 'Letter U. U says uh. Umbrella.',
    color: '#3B82F6',
  },
  {
    id: 'letter_v',
    upper: 'V',
    lower: 'v',
    soundIpa: '/v/',
    soundHint: 'v as in Van',
    word: 'Van',
    emoji: '🚐',
    sentence: 'V is for Van. Drive down the road!',
    audioSpeech: 'Letter V. V says vvv. Van.',
    color: '#8B5CF6',
  },
  {
    id: 'letter_w',
    upper: 'W',
    lower: 'w',
    soundIpa: '/w/',
    soundHint: 'w as in Watch',
    word: 'Watch',
    emoji: '⌚',
    sentence: 'W is for Watch. Tells the time!',
    audioSpeech: 'Letter W. W says wuh. Watch.',
    color: '#06B6D4',
  },
  {
    id: 'letter_x',
    upper: 'X',
    lower: 'x',
    soundIpa: '/ks/',
    soundHint: 'x as in Xylophone',
    word: 'Xylophone',
    emoji: '🎵',
    sentence: 'X is for Xylophone. Make happy tunes!',
    audioSpeech: 'Letter X. X says ks. Xylophone.',
    color: '#F43F5E',
  },
  {
    id: 'letter_y',
    upper: 'Y',
    lower: 'y',
    soundIpa: '/j/',
    soundHint: 'y as in Yo-yo',
    word: 'Yo-yo',
    emoji: '🪀',
    sentence: 'Y is for Yo-yo. Spin it up and down!',
    audioSpeech: 'Letter Y. Y says yuh. Yo-yo.',
    color: '#F59E0B',
  },
  {
    id: 'letter_z',
    upper: 'Z',
    lower: 'z',
    soundIpa: '/z/',
    soundHint: 'z as in Zebra',
    word: 'Zebra',
    emoji: '🦓',
    sentence: 'Z is for Zebra. Black and white stripes!',
    audioSpeech: 'Letter Z. Z says zzz. Zebra.',
    color: '#64748B',
  },
];

// ─── 3. Capital & Small Pairs ─────────────────────────────────────────────────
export const LETTER_MATCH_PAIRS: readonly LetterMatchPair[] = [
  {id: 'match_a', upper: 'A', lower: 'a', distractors: ['d', 'o', 'q']},
  {id: 'match_b', upper: 'B', lower: 'b', distractors: ['d', 'p', 'q']},
  {id: 'match_c', upper: 'C', lower: 'c', distractors: ['e', 'o', 'u']},
  {id: 'match_d', upper: 'D', lower: 'd', distractors: ['b', 'p', 'q']},
  {id: 'match_e', upper: 'E', lower: 'e', distractors: ['c', 'o', 'a']},
  {id: 'match_f', upper: 'F', lower: 'f', distractors: ['t', 'l', 'j']},
  {id: 'match_g', upper: 'G', lower: 'g', distractors: ['q', 'p', 'y']},
  {id: 'match_h', upper: 'H', lower: 'h', distractors: ['n', 'm', 'k']},
  {id: 'match_i', upper: 'I', lower: 'i', distractors: ['l', 'j', 't']},
  {id: 'match_j', upper: 'J', lower: 'j', distractors: ['i', 'l', 'y']},
  {id: 'match_k', upper: 'K', lower: 'k', distractors: ['h', 'x', 'y']},
  {id: 'match_m', upper: 'M', lower: 'm', distractors: ['n', 'w', 'v']},
  {id: 'match_p', upper: 'P', lower: 'p', distractors: ['q', 'b', 'd']},
  {id: 'match_s', upper: 'S', lower: 's', distractors: ['z', 'c', 'e']},
  {id: 'match_t', upper: 'T', lower: 't', distractors: ['f', 'l', 'i']},
];

// ─── 4. Letter Sounds ─────────────────────────────────────────────────────────
export const LETTER_SOUNDS_DATA: readonly LetterSoundItem[] = [
  {
    letter: 'A',
    soundHint: '/æ/ (ah)',
    exampleWord: 'Apple',
    emoji: '🍎',
    audioText: 'A says ah. Like in Apple.',
    options: [
      {id: 'opt_a1', text: 'A', isCorrect: true},
      {id: 'opt_a2', text: 'B', isCorrect: false},
      {id: 'opt_a3', text: 'T', isCorrect: false},
    ],
  },
  {
    letter: 'B',
    soundHint: '/b/ (buh)',
    exampleWord: 'Ball',
    emoji: '⚽',
    audioText: 'B says buh. Like in Ball.',
    options: [
      {id: 'opt_b1', text: 'B', isCorrect: true},
      {id: 'opt_b2', text: 'D', isCorrect: false},
      {id: 'opt_b3', text: 'P', isCorrect: false},
    ],
  },
  {
    letter: 'C',
    soundHint: '/k/ (kuh)',
    exampleWord: 'Cat',
    emoji: '🐱',
    audioText: 'C says kuh. Like in Cat.',
    options: [
      {id: 'opt_c1', text: 'C', isCorrect: true},
      {id: 'opt_c2', text: 'S', isCorrect: false},
      {id: 'opt_c3', text: 'G', isCorrect: false},
    ],
  },
  {
    letter: 'M',
    soundHint: '/m/ (mmm)',
    exampleWord: 'Moon',
    emoji: '🌙',
    audioText: 'M says mmm. Like in Moon.',
    options: [
      {id: 'opt_m1', text: 'M', isCorrect: true},
      {id: 'opt_m2', text: 'N', isCorrect: false},
      {id: 'opt_m3', text: 'W', isCorrect: false},
    ],
  },
  {
    letter: 'S',
    soundHint: '/s/ (sss)',
    exampleWord: 'Sun',
    emoji: '☀️',
    audioText: 'S says sss. Like in Sun.',
    options: [
      {id: 'opt_s1', text: 'S', isCorrect: true},
      {id: 'opt_s2', text: 'C', isCorrect: false},
      {id: 'opt_s3', text: 'Z', isCorrect: false},
    ],
  },
  {
    letter: 'T',
    soundHint: '/t/ (tuh)',
    exampleWord: 'Tree',
    emoji: '🌳',
    audioText: 'T says tuh. Like in Tree.',
    options: [
      {id: 'opt_t1', text: 'T', isCorrect: true},
      {id: 'opt_t2', text: 'D', isCorrect: false},
      {id: 'opt_t3', text: 'F', isCorrect: false},
    ],
  },
];

// ─── 5. Letter & Object Association ──────────────────────────────────────────
export const LETTER_OBJECTS_DATA: readonly LetterObjectItem[] = [
  {
    letter: 'A',
    objectName: 'Apple',
    emoji: '🍎',
    sentence: 'A is for Apple.',
    distractors: [
      {objectName: 'Ball', emoji: '⚽'},
      {objectName: 'Cat', emoji: '🐱'},
    ],
  },
  {
    letter: 'B',
    objectName: 'Ball',
    emoji: '⚽',
    sentence: 'B is for Ball.',
    distractors: [
      {objectName: 'Apple', emoji: '🍎'},
      {objectName: 'Dog', emoji: '🐶'},
    ],
  },
  {
    letter: 'C',
    objectName: 'Cat',
    emoji: '🐱',
    sentence: 'C is for Cat.',
    distractors: [
      {objectName: 'Fish', emoji: '🐟'},
      {objectName: 'Sun', emoji: '☀️'},
    ],
  },
  {
    letter: 'D',
    objectName: 'Dog',
    emoji: '🐶',
    sentence: 'D is for Dog.',
    distractors: [
      {objectName: 'Egg', emoji: '🥚'},
      {objectName: 'Kite', emoji: '🪁'},
    ],
  },
  {
    letter: 'F',
    objectName: 'Fish',
    emoji: '🐟',
    sentence: 'F is for Fish.',
    distractors: [
      {objectName: 'Hat', emoji: '🎩'},
      {objectName: 'Moon', emoji: '🌙'},
    ],
  },
  {
    letter: 'S',
    objectName: 'Sun',
    emoji: '☀️',
    sentence: 'S is for Sun.',
    distractors: [
      {objectName: 'Pig', emoji: '🐷'},
      {objectName: 'Tree', emoji: '🌳'},
    ],
  },
];

// ─── 6. Beginning Sounds ─────────────────────────────────────────────────────
export const BEGINNING_SOUNDS_DATA: readonly BeginningSoundItem[] = [
  {
    word: 'Cat',
    firstLetter: 'C',
    soundHint: '/k/',
    emoji: '🐱',
    distractorSounds: ['/m/', '/s/', '/p/'],
  },
  {
    word: 'Dog',
    firstLetter: 'D',
    soundHint: '/d/',
    emoji: '🐶',
    distractorSounds: ['/b/', '/t/', '/f/'],
  },
  {
    word: 'Sun',
    firstLetter: 'S',
    soundHint: '/s/',
    emoji: '☀️',
    distractorSounds: ['/m/', '/k/', '/l/'],
  },
  {
    word: 'Moon',
    firstLetter: 'M',
    soundHint: '/m/',
    emoji: '🌙',
    distractorSounds: ['/n/', '/w/', '/s/'],
  },
  {
    word: 'Pig',
    firstLetter: 'P',
    soundHint: '/p/',
    emoji: '🐷',
    distractorSounds: ['/b/', '/d/', '/t/'],
  },
  {
    word: 'Apple',
    firstLetter: 'A',
    soundHint: '/æ/',
    emoji: '🍎',
    distractorSounds: ['/b/', '/e/', '/o/'],
  },
];

// ─── 7. Phonics & Blending Items ─────────────────────────────────────────────
export const PHONICS_ITEMS: readonly PhonicsItem[] = [
  {
    id: 'phonics_mat',
    letters: ['M', 'A', 'T'],
    sounds: ['/m/', '/æ/', '/t/'],
    blendedWord: 'MAT',
    emoji: '🧘',
    explanation: 'mmm + aaa + tuh blends into MAT!',
  },
  {
    id: 'phonics_cat',
    letters: ['C', 'A', 'T'],
    sounds: ['/k/', '/æ/', '/t/'],
    blendedWord: 'CAT',
    emoji: '🐱',
    explanation: 'kuh + aaa + tuh blends into CAT!',
  },
  {
    id: 'phonics_sun',
    letters: ['S', 'U', 'N'],
    sounds: ['/s/', '/ʌ/', '/n/'],
    blendedWord: 'SUN',
    emoji: '☀️',
    explanation: 'sss + uh + nnn blends into SUN!',
  },
  {
    id: 'phonics_pig',
    letters: ['P', 'I', 'G'],
    sounds: ['/p/', '/ɪ/', '/g/'],
    blendedWord: 'PIG',
    emoji: '🐷',
    explanation: 'puh + ih + guh blends into PIG!',
  },
  {
    id: 'phonics_dog',
    letters: ['D', 'O', 'G'],
    sounds: ['/d/', '/ɒ/', '/g/'],
    blendedWord: 'DOG',
    emoji: '🐶',
    explanation: 'duh + o + guh blends into DOG!',
  },
];

export const BLENDING_WORDS_DATA: readonly BlendingWordItem[] = [
  {
    id: 'blend_mat',
    letters: ['M', 'A', 'T'],
    phonemes: ['m', 'a', 't'],
    blendedWord: 'mat',
    emoji: '🧘',
    sentence: 'Sit on the mat.',
  },
  {
    id: 'blend_cat',
    letters: ['C', 'A', 'T'],
    phonemes: ['c', 'a', 't'],
    blendedWord: 'cat',
    emoji: '🐱',
    sentence: 'I see a cat.',
  },
  {
    id: 'blend_bat',
    letters: ['B', 'A', 'T'],
    phonemes: ['b', 'a', 't'],
    blendedWord: 'bat',
    emoji: '🏏',
    sentence: 'Hit with a bat.',
  },
  {
    id: 'blend_pin',
    letters: ['P', 'I', 'N'],
    phonemes: ['p', 'i', 'n'],
    blendedWord: 'pin',
    emoji: '📌',
    sentence: 'A sharp pin.',
  },
  {
    id: 'blend_sun',
    letters: ['S', 'U', 'N'],
    phonemes: ['s', 'u', 'n'],
    blendedWord: 'sun',
    emoji: '☀️',
    sentence: 'The sun is hot.',
  },
  {
    id: 'blend_cup',
    letters: ['C', 'U', 'P'],
    phonemes: ['c', 'u', 'p'],
    blendedWord: 'cup',
    emoji: '☕',
    sentence: 'A red cup.',
  },
];

// ─── 8. Word Building Tasks ──────────────────────────────────────────────────
export const WORD_BUILDING_TASKS: readonly WordBuildingTask[] = [
  {
    id: 'wb_cat',
    targetWord: 'CAT',
    emoji: '🐱',
    scrambledLetters: ['C', 'A', 'T', 'M', 'P', 'S'],
    category: 'Animals',
  },
  {
    id: 'wb_dog',
    targetWord: 'DOG',
    emoji: '🐶',
    scrambledLetters: ['D', 'O', 'G', 'B', 'T', 'N'],
    category: 'Animals',
  },
  {
    id: 'wb_sun',
    targetWord: 'SUN',
    emoji: '☀️',
    scrambledLetters: ['S', 'U', 'N', 'R', 'P', 'M'],
    category: 'Nature',
  },
  {
    id: 'wb_bat',
    targetWord: 'BAT',
    emoji: '🏏',
    scrambledLetters: ['B', 'A', 'T', 'F', 'H', 'K'],
    category: 'Play',
  },
  {
    id: 'wb_pig',
    targetWord: 'PIG',
    emoji: '🐷',
    scrambledLetters: ['P', 'I', 'G', 'D', 'S', 'L'],
    category: 'Animals',
  },
  {
    id: 'wb_bed',
    targetWord: 'BED',
    emoji: '🛏️',
    scrambledLetters: ['B', 'E', 'D', 'R', 'T', 'M'],
    category: 'Home',
  },
  {
    id: 'wb_cup',
    targetWord: 'CUP',
    emoji: '☕',
    scrambledLetters: ['C', 'U', 'P', 'N', 'T', 'S'],
    category: 'Home',
  },
  {
    id: 'wb_van',
    targetWord: 'VAN',
    emoji: '🚐',
    scrambledLetters: ['V', 'A', 'N', 'M', 'P', 'T'],
    category: 'Vehicles',
  },
];

// ─── 9. CVC Words ─────────────────────────────────────────────────────────────
export const CVC_WORDS_DATA: readonly CVCWordItem[] = [
  // Short A
  {
    id: 'cvc_cat',
    word: 'cat',
    onset: 'c',
    rime: 'at',
    vowel: 'a',
    family: '-at',
    emoji: '🐱',
    sentence: 'The cat can run.',
  },
  {
    id: 'cvc_bat',
    word: 'bat',
    onset: 'b',
    rime: 'at',
    vowel: 'a',
    family: '-at',
    emoji: '🏏',
    sentence: 'A big bat.',
  },
  {
    id: 'cvc_mat',
    word: 'mat',
    onset: 'm',
    rime: 'at',
    vowel: 'a',
    family: '-at',
    emoji: '🧘',
    sentence: 'Sit on the mat.',
  },
  {
    id: 'cvc_hat',
    word: 'hat',
    onset: 'h',
    rime: 'at',
    vowel: 'a',
    family: '-at',
    emoji: '🎩',
    sentence: 'I see a hat.',
  },
  {
    id: 'cvc_pan',
    word: 'pan',
    onset: 'p',
    rime: 'an',
    vowel: 'a',
    family: '-an',
    emoji: '🍳',
    sentence: 'A hot pan.',
  },

  // Short E
  {
    id: 'cvc_bed',
    word: 'bed',
    onset: 'b',
    rime: 'ed',
    vowel: 'e',
    family: '-ed',
    emoji: '🛏️',
    sentence: 'Sleep in bed.',
  },
  {
    id: 'cvc_red',
    word: 'red',
    onset: 'r',
    rime: 'ed',
    vowel: 'e',
    family: '-ed',
    emoji: '🔴',
    sentence: 'A red ball.',
  },
  {
    id: 'cvc_hen',
    word: 'hen',
    onset: 'h',
    rime: 'en',
    vowel: 'e',
    family: '-en',
    emoji: '🐔',
    sentence: 'The hen has eggs.',
  },
  {
    id: 'cvc_pen',
    word: 'pen',
    onset: 'p',
    rime: 'en',
    vowel: 'e',
    family: '-en',
    emoji: '🖊️',
    sentence: 'I have a pen.',
  },

  // Short I
  {
    id: 'cvc_pin',
    word: 'pin',
    onset: 'p',
    rime: 'in',
    vowel: 'i',
    family: '-in',
    emoji: '📌',
    sentence: 'A little pin.',
  },
  {
    id: 'cvc_pig',
    word: 'pig',
    onset: 'p',
    rime: 'ig',
    vowel: 'i',
    family: '-ig',
    emoji: '🐷',
    sentence: 'The pig is pink.',
  },
  {
    id: 'cvc_sit',
    word: 'sit',
    onset: 's',
    rime: 'it',
    vowel: 'i',
    family: '-it',
    emoji: '🪑',
    sentence: 'Sit down, please.',
  },

  // Short O
  {
    id: 'cvc_dog',
    word: 'dog',
    onset: 'd',
    rime: 'og',
    vowel: 'o',
    family: '-og',
    emoji: '🐶',
    sentence: 'The dog can bark.',
  },
  {
    id: 'cvc_log',
    word: 'log',
    onset: 'l',
    rime: 'og',
    vowel: 'o',
    family: '-og',
    emoji: '🪵',
    sentence: 'A frog on a log.',
  },
  {
    id: 'cvc_pot',
    word: 'pot',
    onset: 'p',
    rime: 'ot',
    vowel: 'o',
    family: '-ot',
    emoji: '🍲',
    sentence: 'Soup in the pot.',
  },

  // Short U
  {
    id: 'cvc_sun',
    word: 'sun',
    onset: 's',
    rime: 'un',
    vowel: 'u',
    family: '-un',
    emoji: '☀️',
    sentence: 'The sun is up.',
  },
  {
    id: 'cvc_run',
    word: 'run',
    onset: 'r',
    rime: 'un',
    vowel: 'u',
    family: '-un',
    emoji: '🏃',
    sentence: 'I can run fast.',
  },
  {
    id: 'cvc_cup',
    word: 'cup',
    onset: 'c',
    rime: 'up',
    vowel: 'u',
    family: '-up',
    emoji: '☕',
    sentence: 'Milk in a cup.',
  },
];

// ─── 10. Sight Words ──────────────────────────────────────────────────────────
export const SIGHT_WORDS_DATA: readonly SightWordItem[] = [
  {
    id: 'sw_i',
    word: 'I',
    exampleSentence: 'I see a dog.',
    emoji: '🙋',
    color: '#EF4444',
  },
  {
    id: 'sw_see',
    word: 'see',
    exampleSentence: 'I see the sun.',
    emoji: '👀',
    color: '#3B82F6',
  },
  {
    id: 'sw_a',
    word: 'a',
    exampleSentence: 'I have a cat.',
    emoji: '🍎',
    color: '#F59E0B',
  },
  {
    id: 'sw_the',
    word: 'the',
    exampleSentence: 'The dog can run.',
    emoji: '🐶',
    color: '#10B981',
  },
  {
    id: 'sw_can',
    word: 'can',
    exampleSentence: 'I can hop.',
    emoji: '🦘',
    color: '#8B5CF6',
  },
  {
    id: 'sw_is',
    word: 'is',
    exampleSentence: 'The sun is hot.',
    emoji: '☀️',
    color: '#EC4899',
  },
  {
    id: 'sw_am',
    word: 'am',
    exampleSentence: 'I am happy.',
    emoji: '😊',
    color: '#06B6D4',
  },
  {
    id: 'sw_my',
    word: 'my',
    exampleSentence: 'This is my ball.',
    emoji: '⚽',
    color: '#F97316',
  },
  {
    id: 'sw_in',
    word: 'in',
    exampleSentence: 'The cat is in the box.',
    emoji: '📦',
    color: '#6366F1',
  },
  {
    id: 'sw_on',
    word: 'on',
    exampleSentence: 'The bug is on the rug.',
    emoji: '🐛',
    color: '#14B8A6',
  },
  {
    id: 'sw_it',
    word: 'it',
    exampleSentence: 'Look at it go!',
    emoji: '🚀',
    color: '#EAB308',
  },
  {
    id: 'sw_to',
    word: 'to',
    exampleSentence: 'Run to the tree.',
    emoji: '🌳',
    color: '#64748B',
  },
];

// ─── 11. Tongue Twisters ─────────────────────────────────────────────────────
export const TONGUE_TWISTERS_DATA: readonly TongueTwisterItem[] = [
  {
    id: 'tt_b',
    title: 'Bouncy Blue Ball',
    text: 'Big blue ball bounces bright.',
    targetSound: '/b/',
    highlightedLetter: 'B',
    emoji: '⚽',
    speedText: 'Say it 3 times fast!',
  },
  {
    id: 'tt_s',
    title: 'Sunny Snakes',
    text: 'Six silly snakes see sunny skies.',
    targetSound: '/s/',
    highlightedLetter: 'S',
    emoji: '🐍',
    speedText: 'Hiss like a snake!',
  },
  {
    id: 'tt_r',
    title: 'Red Rabbit',
    text: 'Red rabbit runs round rocks.',
    targetSound: '/r/',
    highlightedLetter: 'R',
    emoji: '🐰',
    speedText: 'Hop and say it quick!',
  },
  {
    id: 'tt_c',
    title: 'Cute Cats',
    text: 'Cute cats catch crunchy cookies.',
    targetSound: '/k/',
    highlightedLetter: 'C',
    emoji: '🐱',
    speedText: 'Meow and repeat!',
  },
  {
    id: 'tt_f',
    title: 'Funny Frogs',
    text: 'Four friendly frogs float fast.',
    targetSound: '/f/',
    highlightedLetter: 'F',
    emoji: '🐸',
    speedText: 'Ribbit ribbit fast!',
  },
];

// ─── 12. Sentence Reading Lessons ────────────────────────────────────────────
export const SENTENCE_READING_DATA: readonly SentenceReadingItem[] = [
  {
    id: 'sen_1',
    text: 'I see a cat.',
    words: ['I', 'see', 'a', 'cat.'],
    emoji: '🐱',
    level: 1,
    comprehensionQuestion: {
      question: 'What do I see?',
      options: ['A cat', 'A dog', 'A car'],
      answer: 'A cat',
    },
  },
  {
    id: 'sen_2',
    text: 'The dog can run.',
    words: ['The', 'dog', 'can', 'run.'],
    emoji: '🐶',
    level: 1,
    comprehensionQuestion: {
      question: 'Who can run?',
      options: ['The dog', 'The tree', 'The house'],
      answer: 'The dog',
    },
  },
  {
    id: 'sen_3',
    text: 'The sun is big and hot.',
    words: ['The', 'sun', 'is', 'big', 'and', 'hot.'],
    emoji: '☀️',
    level: 2,
    comprehensionQuestion: {
      question: 'How is the sun?',
      options: ['Big and hot', 'Cold and wet', 'Dark and cold'],
      answer: 'Big and hot',
    },
  },
  {
    id: 'sen_4',
    text: 'Sam has a red hat.',
    words: ['Sam', 'has', 'a', 'red', 'hat.'],
    emoji: '🎩',
    level: 2,
    comprehensionQuestion: {
      question: 'What color is the hat?',
      options: ['Red', 'Blue', 'Green'],
      answer: 'Red',
    },
  },
  {
    id: 'sen_5',
    text: 'A little pig in the mud.',
    words: ['A', 'little', 'pig', 'in', 'the', 'mud.'],
    emoji: '🐷',
    level: 3,
    comprehensionQuestion: {
      question: 'Where is the pig?',
      options: ['In the mud', 'In the sky', 'On the roof'],
      answer: 'In the mud',
    },
  },
];

// ─── 13. Short Stories ────────────────────────────────────────────────────────
export const SHORT_STORIES_DATA: readonly ShortStoryItem[] = [
  {
    id: 'story_sam_cat',
    title: 'Sam and His Cat',
    coverEmoji: '🐱',
    fullStoryText:
      'Sam has a cat. The cat is big. The cat can run. Sam and the cat play in the sun.',
    pages: [
      {
        text: 'Sam has a cat.',
        emoji: '👦',
        words: ['Sam', 'has', 'a', 'cat.'],
      },
      {
        text: 'The cat is big.',
        emoji: '🐱',
        words: ['The', 'cat', 'is', 'big.'],
      },
      {
        text: 'The cat can run.',
        emoji: '🏃',
        words: ['The', 'cat', 'can', 'run.'],
      },
      {
        text: 'Sam and the cat play in the sun.',
        emoji: '☀️',
        words: ['Sam', 'and', 'the', 'cat', 'play', 'in', 'the', 'sun.'],
      },
    ],
    questions: [
      {
        id: 'q_sam_1',
        question: 'Who has a cat?',
        options: ['Sam', 'Ben', 'Tom'],
        answer: 'Sam',
      },
      {
        id: 'q_sam_2',
        question: 'What can the cat do?',
        options: ['Run and play', 'Fly high', 'Swim deep'],
        answer: 'Run and play',
      },
      {
        id: 'q_sam_3',
        question: 'Where do they play?',
        options: ['In the sun', 'In the dark', 'In the rain'],
        answer: 'In the sun',
      },
    ],
  },
  {
    id: 'story_red_bus',
    title: 'The Red Bus',
    coverEmoji: '🚌',
    fullStoryText:
      'I see a red bus. The bus goes beep beep. Many kids sit in the bus. The bus goes to school.',
    pages: [
      {
        text: 'I see a red bus.',
        emoji: '🚌',
        words: ['I', 'see', 'a', 'red', 'bus.'],
      },
      {
        text: 'The bus goes beep beep.',
        emoji: '📢',
        words: ['The', 'bus', 'goes', 'beep', 'beep.'],
      },
      {
        text: 'Many kids sit in the bus.',
        emoji: '👧👦',
        words: ['Many', 'kids', 'sit', 'in', 'the', 'bus.'],
      },
      {
        text: 'The bus goes to school.',
        emoji: '🏫',
        words: ['The', 'bus', 'goes', 'to', 'school.'],
      },
    ],
    questions: [
      {
        id: 'q_bus_1',
        question: 'What color is the bus?',
        options: ['Red', 'Green', 'Yellow'],
        answer: 'Red',
      },
      {
        id: 'q_bus_2',
        question: 'Where does the bus go?',
        options: ['To school', 'To the moon', 'To the zoo'],
        answer: 'To school',
      },
    ],
  },
  {
    id: 'story_fun_dog',
    title: 'A Fun Dog',
    coverEmoji: '🐶',
    fullStoryText:
      'Max is a little dog. Max has a red ball. Max runs fast to get the ball. Good dog Max!',
    pages: [
      {
        text: 'Max is a little dog.',
        emoji: '🐶',
        words: ['Max', 'is', 'a', 'little', 'dog.'],
      },
      {
        text: 'Max has a red ball.',
        emoji: '⚽',
        words: ['Max', 'has', 'a', 'red', 'ball.'],
      },
      {
        text: 'Max runs fast to get the ball.',
        emoji: '🏃',
        words: ['Max', 'runs', 'fast', 'to', 'get', 'the', 'ball.'],
      },
      {
        text: 'Good dog Max!',
        emoji: '⭐',
        words: ['Good', 'dog', 'Max!'],
      },
    ],
    questions: [
      {
        id: 'q_dog_1',
        question: 'What is the dog’s name?',
        options: ['Max', 'Rex', 'Spot'],
        answer: 'Max',
      },
      {
        id: 'q_dog_2',
        question: 'What does Max have?',
        options: ['A red ball', 'A blue fish', 'A green hat'],
        answer: 'A red ball',
      },
    ],
  },
];

// ─── 14. Universal / Sub-module Quiz Questions ────────────────────────────────
export const SUBMODULE_QUIZZES: Record<string, readonly EnglishQuizQuestion[]> =
  {
    alphabet: [
      {
        id: 'q_alpha_1',
        type: 'multiple-choice',
        prompt: 'Which letter comes after A?',
        promptEmoji: '🔤',
        options: [
          {id: 'o1', text: 'B', isCorrect: true},
          {id: 'o2', text: 'D', isCorrect: false},
          {id: 'o3', text: 'M', isCorrect: false},
        ],
        explanation: 'A is followed by B!',
      },
      {
        id: 'q_alpha_2',
        type: 'missing-letter',
        prompt: 'Find the missing letter: A, B, __, D',
        promptEmoji: '🧩',
        options: [
          {id: 'o1', text: 'C', isCorrect: true},
          {id: 'o2', text: 'E', isCorrect: false},
          {id: 'o3', text: 'F', isCorrect: false},
        ],
        explanation: 'A, B, C, D is the correct alphabetical order!',
      },
      {
        id: 'q_alpha_3',
        type: 'image-choice',
        prompt: 'Which letter starts the word Apple?',
        promptEmoji: '🍎',
        options: [
          {id: 'o1', text: 'A', emoji: '🍎', isCorrect: true},
          {id: 'o2', text: 'B', emoji: '⚽', isCorrect: false},
          {id: 'o3', text: 'C', emoji: '🐱', isCorrect: false},
        ],
        explanation: 'Apple begins with the letter A!',
      },
    ],

    capital_small: [
      {
        id: 'q_cs_1',
        type: 'letter-match',
        prompt: 'What is the lowercase letter for G?',
        promptEmoji: '🔠',
        options: [
          {id: 'o1', text: 'g', isCorrect: true},
          {id: 'o2', text: 'q', isCorrect: false},
          {id: 'o3', text: 'p', isCorrect: false},
        ],
        explanation: 'G matches with lowercase g!',
      },
      {
        id: 'q_cs_2',
        type: 'letter-match',
        prompt: 'What is the lowercase letter for B?',
        promptEmoji: '🔠',
        options: [
          {id: 'o1', text: 'b', isCorrect: true},
          {id: 'o2', text: 'd', isCorrect: false},
          {id: 'o3', text: 'p', isCorrect: false},
        ],
        explanation: 'B matches with lowercase b!',
      },
      {
        id: 'q_cs_3',
        type: 'letter-match',
        prompt: 'What is the uppercase letter for m?',
        promptEmoji: '🔠',
        options: [
          {id: 'o1', text: 'M', isCorrect: true},
          {id: 'o2', text: 'W', isCorrect: false},
          {id: 'o3', text: 'N', isCorrect: false},
        ],
        explanation: 'm matches with capital M!',
      },
    ],

    letter_sounds: [
      {
        id: 'q_ls_1',
        type: 'sound-identify',
        prompt: 'Which letter makes the /b/ sound as in Ball?',
        promptEmoji: '⚽',
        targetAudio: 'buh',
        options: [
          {id: 'o1', text: 'B', isCorrect: true},
          {id: 'o2', text: 'T', isCorrect: false},
          {id: 'o3', text: 'M', isCorrect: false},
        ],
        explanation: 'B makes the /b/ sound!',
      },
      {
        id: 'q_ls_2',
        type: 'sound-identify',
        prompt: 'Which letter makes the /s/ sound as in Sun?',
        promptEmoji: '☀️',
        targetAudio: 'sss',
        options: [
          {id: 'o1', text: 'S', isCorrect: true},
          {id: 'o2', text: 'C', isCorrect: false},
          {id: 'o3', text: 'Z', isCorrect: false},
        ],
        explanation: 'S makes the /s/ sound!',
      },
      {
        id: 'q_ls_3',
        type: 'sound-identify',
        prompt: 'Which letter makes the /m/ sound as in Moon?',
        promptEmoji: '🌙',
        targetAudio: 'mmm',
        options: [
          {id: 'o1', text: 'M', isCorrect: true},
          {id: 'o2', text: 'N', isCorrect: false},
          {id: 'o3', text: 'W', isCorrect: false},
        ],
        explanation: 'M makes the /m/ sound!',
      },
    ],

    beginning_sounds: [
      {
        id: 'q_bs_1',
        type: 'sound-identify',
        prompt: 'What sound does Cat start with?',
        promptEmoji: '🐱',
        options: [
          {id: 'o1', text: '/k/ (C)', isCorrect: true},
          {id: 'o2', text: '/m/ (M)', isCorrect: false},
          {id: 'o3', text: '/s/ (S)', isCorrect: false},
        ],
        explanation: 'Cat starts with the /k/ sound!',
      },
      {
        id: 'q_bs_2',
        type: 'image-choice',
        prompt: 'Which word starts with the /d/ sound?',
        promptEmoji: '👂',
        options: [
          {id: 'o1', text: 'Dog', emoji: '🐶', isCorrect: true},
          {id: 'o2', text: 'Fish', emoji: '🐟', isCorrect: false},
          {id: 'o3', text: 'Sun', emoji: '☀️', isCorrect: false},
        ],
        explanation: 'Dog starts with the /d/ sound!',
      },
      {
        id: 'q_bs_3',
        type: 'sound-identify',
        prompt: 'What sound does Sun start with?',
        promptEmoji: '☀️',
        options: [
          {id: 'o1', text: '/s/ (S)', isCorrect: true},
          {id: 'o2', text: '/b/ (B)', isCorrect: false},
          {id: 'o3', text: '/t/ (T)', isCorrect: false},
        ],
        explanation: 'Sun starts with the /s/ sound!',
      },
    ],

    cvc_words: [
      {
        id: 'q_cvc_1',
        type: 'image-choice',
        prompt: 'Read the word: C-A-T. Which picture is it?',
        promptEmoji: '📖',
        options: [
          {id: 'o1', text: 'Cat', emoji: '🐱', isCorrect: true},
          {id: 'o2', text: 'Dog', emoji: '🐶', isCorrect: false},
          {id: 'o3', text: 'Sun', emoji: '☀️', isCorrect: false},
        ],
        explanation: 'C-A-T is CAT!',
      },
      {
        id: 'q_cvc_2',
        type: 'missing-letter',
        prompt: 'Complete the word: D _ G',
        promptEmoji: '🐶',
        options: [
          {id: 'o1', text: 'O', isCorrect: true},
          {id: 'o2', text: 'A', isCorrect: false},
          {id: 'o3', text: 'U', isCorrect: false},
        ],
        explanation: 'D-O-G makes DOG!',
      },
      {
        id: 'q_cvc_3',
        type: 'multiple-choice',
        prompt: 'Which word rhymes with SUN?',
        promptEmoji: '☀️',
        options: [
          {id: 'o1', text: 'RUN', isCorrect: true},
          {id: 'o2', text: 'CAT', isCorrect: false},
          {id: 'o3', text: 'BED', isCorrect: false},
        ],
        explanation: 'SUN and RUN end with the -un sound!',
      },
    ],

    sight_words: [
      {
        id: 'q_sw_1',
        type: 'sentence-completion',
        prompt: 'Complete the sentence: "I ___ a cat."',
        promptEmoji: '🐱',
        options: [
          {id: 'o1', text: 'see', isCorrect: true},
          {id: 'o2', text: 'sun', isCorrect: false},
          {id: 'o3', text: 'hat', isCorrect: false},
        ],
        explanation: '"I see a cat" makes a complete sentence!',
      },
      {
        id: 'q_sw_2',
        type: 'multiple-choice',
        prompt: 'Find the sight word: "THE"',
        promptEmoji: '⭐',
        options: [
          {id: 'o1', text: 'the', isCorrect: true},
          {id: 'o2', text: 'tea', isCorrect: false},
          {id: 'o3', text: 'ten', isCorrect: false},
        ],
        explanation: 't-h-e spells "the"!',
      },
      {
        id: 'q_sw_3',
        type: 'sentence-completion',
        prompt: 'Complete: "The dog ___ run."',
        promptEmoji: '🐶',
        options: [
          {id: 'o1', text: 'can', isCorrect: true},
          {id: 'o2', text: 'cup', isCorrect: false},
          {id: 'o3', text: 'cat', isCorrect: false},
        ],
        explanation: '"The dog can run" is correct!',
      },
    ],

    reading_challenge: [
      {
        id: 'q_rc_1',
        type: 'multiple-choice',
        prompt: 'Read this CVC word: S-U-N. What is it?',
        promptEmoji: '☀️',
        options: [
          {id: 'o1', text: 'SUN', isCorrect: true},
          {id: 'o2', text: 'SON', isCorrect: false},
          {id: 'o3', text: 'SIN', isCorrect: false},
        ],
        explanation: 'S-U-N is SUN!',
      },
      {
        id: 'q_rc_2',
        type: 'sentence-completion',
        prompt: 'Put words in order: "a / I / see / dog."',
        promptEmoji: '🐶',
        options: [
          {id: 'o1', text: 'I see a dog.', isCorrect: true},
          {id: 'o2', text: 'A dog see I.', isCorrect: false},
          {id: 'o3', text: 'See I dog a.', isCorrect: false},
        ],
        explanation: '"I see a dog." is the correct sentence order!',
      },
      {
        id: 'q_rc_3',
        type: 'story-comprehension',
        prompt: 'Read: "The big dog can run." What can the dog do?',
        promptEmoji: '🐕',
        options: [
          {id: 'o1', text: 'Run', isCorrect: true},
          {id: 'o2', text: 'Swim', isCorrect: false},
          {id: 'o3', text: 'Fly', isCorrect: false},
        ],
        explanation: 'The dog can run!',
      },
      {
        id: 'q_rc_4',
        type: 'missing-letter',
        prompt: 'Fill the vowel: C _ T (🐱)',
        promptEmoji: '🐱',
        options: [
          {id: 'o1', text: 'A', isCorrect: true},
          {id: 'o2', text: 'O', isCorrect: false},
          {id: 'o3', text: 'E', isCorrect: false},
        ],
        explanation: 'C-A-T makes CAT!',
      },
      {
        id: 'q_rc_5',
        type: 'multiple-choice',
        prompt: 'Which word is a sight word?',
        promptEmoji: '⭐',
        options: [
          {id: 'o1', text: 'the', isCorrect: true},
          {id: 'o2', text: 'xyz', isCorrect: false},
          {id: 'o3', text: 'qrs', isCorrect: false},
        ],
        explanation: '"the" is one of the most common sight words in English!',
      },
    ],
  };
