import type {
  ChallengeQuestion,
  CodingTopicId,
  CommandMeta,
  ConditionScenario,
  DebuggingPuzzle,
  LoopChallenge,
  RobotMazeLevel,
  SequencingStory,
} from '../entities/codingEntities';

export const COMMAND_METAS: readonly CommandMeta[] = [
  {
    id: 'up',
    labelKey: 'coding.commands.up',
    icon: '⬆️',
    dx: 0,
    dy: -1,
    color: '#3B82F6',
  },
  {
    id: 'down',
    labelKey: 'coding.commands.down',
    icon: '⬇️',
    dx: 0,
    dy: 1,
    color: '#10B981',
  },
  {
    id: 'left',
    labelKey: 'coding.commands.left',
    icon: '⬅️',
    dx: -1,
    dy: 0,
    color: '#F59E0B',
  },
  {
    id: 'right',
    labelKey: 'coding.commands.right',
    icon: '➡️',
    dx: 1,
    dy: 0,
    color: '#8B5CF6',
  },
  {
    id: 'jump',
    labelKey: 'coding.commands.jump',
    icon: '🦘',
    dx: 0,
    dy: 0,
    color: '#EC4899',
  },
  {
    id: 'grab',
    labelKey: 'coding.commands.grab',
    icon: '⛏️',
    dx: 0,
    dy: 0,
    color: '#06B6D4',
  },
];

export const CODING_TOPIC_CARDS: readonly {
  readonly id: CodingTopicId;
  readonly titleKey: string;
  readonly subtitleKey: string;
  readonly emoji: string;
  readonly accentColor: string;
  readonly badgeTag: string;
}[] = [
  {
    id: 'robot',
    titleKey: 'coding.topics.robot.title',
    subtitleKey: 'coding.topics.robot.sub',
    emoji: '🤖',
    accentColor: '#3B82F6',
    badgeTag: 'Interactive Maze',
  },
  {
    id: 'instructions',
    titleKey: 'coding.topics.instructions.title',
    subtitleKey: 'coding.topics.instructions.sub',
    emoji: '➡️',
    accentColor: '#8B5CF6',
    badgeTag: 'Directions',
  },
  {
    id: 'sequencing',
    titleKey: 'coding.topics.sequencing.title',
    subtitleKey: 'coding.topics.sequencing.sub',
    emoji: '🔢',
    accentColor: '#10B981',
    badgeTag: 'Step Order',
  },
  {
    id: 'loops',
    titleKey: 'coding.topics.loops.title',
    subtitleKey: 'coding.topics.loops.sub',
    emoji: '🔁',
    accentColor: '#F59E0B',
    badgeTag: 'Repetition',
  },
  {
    id: 'conditionals',
    titleKey: 'coding.topics.conditionals.title',
    subtitleKey: 'coding.topics.conditionals.sub',
    emoji: '❓',
    accentColor: '#EC4899',
    badgeTag: 'If / Then',
  },
  {
    id: 'debugging',
    titleKey: 'coding.topics.debugging.title',
    subtitleKey: 'coding.topics.debugging.sub',
    emoji: '🐛',
    accentColor: '#EF4444',
    badgeTag: 'Fix the Bug',
  },
  {
    id: 'challenge',
    titleKey: 'coding.topics.challenge.title',
    subtitleKey: 'coding.topics.challenge.sub',
    emoji: '🎯',
    accentColor: '#6366F1',
    badgeTag: 'Master Arena',
  },
];

export const ROBOT_MAZE_LEVELS: readonly RobotMazeLevel[] = [
  // ─── Beginner (2-3 steps, straight paths) ─────────────────────────────────
  {
    id: 'maze-1',
    levelNumber: 1,
    titleKey: 'coding.mazes.level1',
    difficulty: 'beginner',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 1, col: 0},
    goalPos: {row: 1, col: 3},
    obstacles: [
      {row: 0, col: 1},
      {row: 2, col: 2},
    ],
    starsTarget: 3,
    maxCommands: 4,
    hintCommands: ['right', 'right', 'right'],
    theme: 'space',
  },
  {
    id: 'maze-2',
    levelNumber: 2,
    titleKey: 'coding.mazes.level2',
    difficulty: 'beginner',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 1},
    goalPos: {row: 3, col: 1},
    obstacles: [
      {row: 1, col: 0},
      {row: 2, col: 2},
    ],
    starsTarget: 3,
    maxCommands: 4,
    hintCommands: ['down', 'down', 'down'],
    theme: 'forest',
  },
  {
    id: 'maze-3',
    levelNumber: 3,
    titleKey: 'coding.mazes.level3',
    difficulty: 'beginner',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 0},
    goalPos: {row: 2, col: 2},
    obstacles: [
      {row: 0, col: 1},
      {row: 1, col: 0},
    ],
    starsTarget: 3,
    maxCommands: 5,
    hintCommands: ['down', 'down', 'right', 'right'],
    theme: 'treasure',
  },

  // ─── Intermediate (4-5 steps, 1-2 turns, obstacles) ───────────────────────
  {
    id: 'maze-4',
    levelNumber: 4,
    titleKey: 'coding.mazes.level4',
    difficulty: 'intermediate',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 0},
    goalPos: {row: 3, col: 3},
    obstacles: [
      {row: 1, col: 1},
      {row: 2, col: 2},
      {row: 0, col: 2},
    ],
    starsTarget: 3,
    maxCommands: 7,
    hintCommands: ['down', 'down', 'down', 'right', 'right', 'right'],
    theme: 'castle',
  },
  {
    id: 'maze-5',
    levelNumber: 5,
    titleKey: 'coding.mazes.level5',
    difficulty: 'intermediate',
    gridSize: {rows: 5, cols: 5},
    startPos: {row: 0, col: 2},
    goalPos: {row: 4, col: 4},
    obstacles: [
      {row: 1, col: 2},
      {row: 2, col: 2},
      {row: 3, col: 3},
    ],
    starsTarget: 3,
    maxCommands: 8,
    hintCommands: ['left', 'down', 'down', 'right', 'right', 'down', 'down'],
    theme: 'space',
  },
  {
    id: 'maze-6',
    levelNumber: 6,
    titleKey: 'coding.mazes.level6',
    difficulty: 'intermediate',
    gridSize: {rows: 5, cols: 5},
    startPos: {row: 4, col: 0},
    goalPos: {row: 0, col: 4},
    obstacles: [
      {row: 3, col: 1},
      {row: 2, col: 2},
      {row: 1, col: 3},
    ],
    starsTarget: 3,
    maxCommands: 9,
    hintCommands: ['right', 'right', 'right', 'right', 'up', 'up', 'up', 'up'],
    theme: 'forest',
  },

  // ─── Advanced (5x5 grid, zig-zag, loops) ──────────────────────────────────
  {
    id: 'maze-7',
    levelNumber: 7,
    titleKey: 'coding.mazes.level7',
    difficulty: 'advanced',
    gridSize: {rows: 5, cols: 5},
    startPos: {row: 0, col: 0},
    goalPos: {row: 4, col: 4},
    obstacles: [
      {row: 0, col: 1},
      {row: 1, col: 1},
      {row: 2, col: 1},
      {row: 2, col: 3},
      {row: 3, col: 3},
    ],
    starsTarget: 3,
    maxCommands: 10,
    theme: 'treasure',
    loopAllowed: true,
  },
  {
    id: 'maze-8',
    levelNumber: 8,
    titleKey: 'coding.mazes.level8',
    difficulty: 'advanced',
    gridSize: {rows: 5, cols: 5},
    startPos: {row: 2, col: 0},
    goalPos: {row: 2, col: 4},
    obstacles: [
      {row: 2, col: 1},
      {row: 2, col: 2},
      {row: 2, col: 3},
    ],
    starsTarget: 3,
    maxCommands: 9,
    theme: 'castle',
    loopAllowed: true,
  },
  {
    id: 'maze-9',
    levelNumber: 9,
    titleKey: 'coding.mazes.level9',
    difficulty: 'advanced',
    gridSize: {rows: 5, cols: 5},
    startPos: {row: 4, col: 4},
    goalPos: {row: 0, col: 0},
    obstacles: [
      {row: 3, col: 3},
      {row: 2, col: 2},
      {row: 1, col: 1},
    ],
    starsTarget: 3,
    maxCommands: 10,
    theme: 'space',
    loopAllowed: true,
  },
];

export const SEQUENCING_STORIES: readonly SequencingStory[] = [
  {
    id: 'seq-morning',
    titleKey: 'coding.sequencing.morningTitle',
    category: 'daily',
    steps: [
      {
        id: 's1',
        stepNumber: 1,
        textKey: 'coding.sequencing.steps.wakeUp',
        icon: '⏰',
      },
      {
        id: 's2',
        stepNumber: 2,
        textKey: 'coding.sequencing.steps.brushTeeth',
        icon: '🪥',
      },
      {
        id: 's3',
        stepNumber: 3,
        textKey: 'coding.sequencing.steps.eatBreakfast',
        icon: '🥣',
      },
      {
        id: 's4',
        stepNumber: 4,
        textKey: 'coding.sequencing.steps.goSchool',
        icon: '🎒',
      },
    ],
    correctOrder: ['s1', 's2', 's3', 's4'],
    storySummaryKey: 'coding.sequencing.morningSummary',
  },
  {
    id: 'seq-plant',
    titleKey: 'coding.sequencing.plantTitle',
    category: 'nature',
    steps: [
      {
        id: 'p1',
        stepNumber: 1,
        textKey: 'coding.sequencing.steps.plantSeed',
        icon: '🌱',
      },
      {
        id: 'p2',
        stepNumber: 2,
        textKey: 'coding.sequencing.steps.waterSeed',
        icon: '💧',
      },
      {
        id: 'p3',
        stepNumber: 3,
        textKey: 'coding.sequencing.steps.sunShines',
        icon: '☀️',
      },
      {
        id: 'p4',
        stepNumber: 4,
        textKey: 'coding.sequencing.steps.flowerBlooms',
        icon: '🌸',
      },
    ],
    correctOrder: ['p1', 'p2', 'p3', 'p4'],
    storySummaryKey: 'coding.sequencing.plantSummary',
  },
  {
    id: 'seq-sandwich',
    titleKey: 'coding.sequencing.sandwichTitle',
    category: 'cooking',
    steps: [
      {
        id: 'w1',
        stepNumber: 1,
        textKey: 'coding.sequencing.steps.getBread',
        icon: '🍞',
      },
      {
        id: 'w2',
        stepNumber: 2,
        textKey: 'coding.sequencing.steps.spreadJam',
        icon: '🍓',
      },
      {
        id: 'w3',
        stepNumber: 3,
        textKey: 'coding.sequencing.steps.closeBread',
        icon: '🥪',
      },
      {
        id: 'w4',
        stepNumber: 4,
        textKey: 'coding.sequencing.steps.eatBite',
        icon: '😋',
      },
    ],
    correctOrder: ['w1', 'w2', 'w3', 'w4'],
    storySummaryKey: 'coding.sequencing.sandwichSummary',
  },
  {
    id: 'seq-hands',
    titleKey: 'coding.sequencing.handsTitle',
    category: 'health',
    steps: [
      {
        id: 'h1',
        stepNumber: 1,
        textKey: 'coding.sequencing.steps.wetHands',
        icon: '🚰',
      },
      {
        id: 'h2',
        stepNumber: 2,
        textKey: 'coding.sequencing.steps.applySoap',
        icon: '🧼',
      },
      {
        id: 'h3',
        stepNumber: 3,
        textKey: 'coding.sequencing.steps.rubHands',
        icon: '🤲',
      },
      {
        id: 'h4',
        stepNumber: 4,
        textKey: 'coding.sequencing.steps.dryTowel',
        icon: '🧖',
      },
    ],
    correctOrder: ['h1', 'h2', 'h3', 'h4'],
    storySummaryKey: 'coding.sequencing.handsSummary',
  },
  {
    id: 'seq-snowman',
    titleKey: 'coding.sequencing.snowmanTitle',
    category: 'daily',
    steps: [
      {
        id: 'm1',
        stepNumber: 1,
        textKey: 'coding.sequencing.steps.rollSnowball',
        icon: '⚪',
      },
      {
        id: 'm2',
        stepNumber: 2,
        textKey: 'coding.sequencing.steps.addHead',
        icon: '⛄',
      },
      {
        id: 'm3',
        stepNumber: 3,
        textKey: 'coding.sequencing.steps.carrotNose',
        icon: '🥕',
      },
      {
        id: 'm4',
        stepNumber: 4,
        textKey: 'coding.sequencing.steps.putHat',
        icon: '🎩',
      },
    ],
    correctOrder: ['m1', 'm2', 'm3', 'm4'],
    storySummaryKey: 'coding.sequencing.snowmanSummary',
  },
];

export const LOOP_CHALLENGES: readonly LoopChallenge[] = [
  {
    id: 'loop-1',
    titleKey: 'coding.loops.bunnyTitle',
    descriptionKey: 'coding.loops.bunnyDesc',
    repeatCount: 3,
    loopCommand: 'right',
    targetDistance: 3,
    themeEmoji: '🐰',
    options: [
      {count: 3, cmd: 'right', isCorrect: true},
      {count: 2, cmd: 'right', isCorrect: false},
      {count: 4, cmd: 'up', isCorrect: false},
    ],
  },
  {
    id: 'loop-2',
    titleKey: 'coding.loops.rocketTitle',
    descriptionKey: 'coding.loops.rocketDesc',
    repeatCount: 4,
    loopCommand: 'up',
    targetDistance: 4,
    themeEmoji: '🚀',
    options: [
      {count: 2, cmd: 'up', isCorrect: false},
      {count: 4, cmd: 'up', isCorrect: true},
      {count: 4, cmd: 'down', isCorrect: false},
    ],
  },
  {
    id: 'loop-3',
    titleKey: 'coding.loops.frogTitle',
    descriptionKey: 'coding.loops.frogDesc',
    repeatCount: 5,
    loopCommand: 'jump',
    targetDistance: 5,
    themeEmoji: '🐸',
    options: [
      {count: 3, cmd: 'jump', isCorrect: false},
      {count: 5, cmd: 'jump', isCorrect: true},
      {count: 5, cmd: 'right', isCorrect: false},
    ],
  },
  {
    id: 'loop-4',
    titleKey: 'coding.loops.dancerTitle',
    descriptionKey: 'coding.loops.dancerDesc',
    repeatCount: 2,
    loopCommand: 'right',
    targetDistance: 2,
    themeEmoji: '💃',
    options: [
      {count: 2, cmd: 'right', isCorrect: true},
      {count: 1, cmd: 'right', isCorrect: false},
      {count: 3, cmd: 'left', isCorrect: false},
    ],
  },
  {
    id: 'loop-5',
    titleKey: 'coding.loops.beadsTitle',
    descriptionKey: 'coding.loops.beadsDesc',
    repeatCount: 4,
    loopCommand: 'grab',
    targetDistance: 4,
    themeEmoji: '📿',
    options: [
      {count: 4, cmd: 'grab', isCorrect: true},
      {count: 2, cmd: 'grab', isCorrect: false},
      {count: 5, cmd: 'grab', isCorrect: false},
    ],
  },
];

export const CONDITION_SCENARIOS: readonly ConditionScenario[] = [
  {
    id: 'cond-rain',
    ifConditionKey: 'coding.conditionals.ifRain',
    ifIcon: '🌧️',
    correctThenKey: 'coding.conditionals.thenUmbrella',
    correctThenIcon: '☔',
    distractorThens: [
      {textKey: 'coding.conditionals.thenSunglasses', icon: '🕶️'},
      {textKey: 'coding.conditionals.thenIceCream', icon: '🍦'},
    ],
  },
  {
    id: 'cond-redlight',
    ifConditionKey: 'coding.conditionals.ifRedLight',
    ifIcon: '🚦',
    correctThenKey: 'coding.conditionals.thenStop',
    correctThenIcon: '🛑',
    distractorThens: [
      {textKey: 'coding.conditionals.thenSpeedUp', icon: '🏎️'},
      {textKey: 'coding.conditionals.thenDance', icon: '💃'},
    ],
  },
  {
    id: 'cond-greenlight',
    ifConditionKey: 'coding.conditionals.ifGreenLight',
    ifIcon: '🟢',
    correctThenKey: 'coding.conditionals.thenGo',
    correctThenIcon: '🚗',
    distractorThens: [
      {textKey: 'coding.conditionals.thenStop', icon: '🛑'},
      {textKey: 'coding.conditionals.thenSleep', icon: '😴'},
    ],
  },
  {
    id: 'cond-night',
    ifConditionKey: 'coding.conditionals.ifNight',
    ifIcon: '🌙',
    correctThenKey: 'coding.conditionals.thenSleep',
    correctThenIcon: '😴',
    distractorThens: [
      {textKey: 'coding.conditionals.thenSunbathe', icon: '🏖️'},
      {textKey: 'coding.conditionals.thenFlyKite', icon: '🪁'},
    ],
  },
  {
    id: 'cond-battery',
    ifConditionKey: 'coding.conditionals.ifLowBattery',
    ifIcon: '🪫',
    correctThenKey: 'coding.conditionals.thenRecharge',
    correctThenIcon: '🔋',
    distractorThens: [
      {textKey: 'coding.conditionals.thenJump', icon: '🦘'},
      {textKey: 'coding.conditionals.thenSing', icon: '🎤'},
    ],
  },
  {
    id: 'cond-locked',
    ifConditionKey: 'coding.conditionals.ifDoorLocked',
    ifIcon: '🔒',
    correctThenKey: 'coding.conditionals.thenUseKey',
    correctThenIcon: '🔑',
    distractorThens: [
      {textKey: 'coding.conditionals.thenPaint', icon: '🎨'},
      {textKey: 'coding.conditionals.thenWaterPlant', icon: '💧'},
    ],
  },
];

export const DEBUGGING_PUZZLES: readonly DebuggingPuzzle[] = [
  {
    id: 'bug-1',
    titleKey: 'coding.debugging.p1Title',
    promptKey: 'coding.debugging.p1Prompt',
    gridSize: {rows: 3, cols: 3},
    startPos: {row: 1, col: 0},
    goalPos: {row: 1, col: 2},
    obstacles: [{row: 0, col: 1}],
    initialCode: ['right', 'up', 'right'],
    buggyIndex: 1,
    correctCommand: 'right',
    explanationKey: 'coding.debugging.p1Expl',
  },
  {
    id: 'bug-2',
    titleKey: 'coding.debugging.p2Title',
    promptKey: 'coding.debugging.p2Prompt',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 0},
    goalPos: {row: 2, col: 0},
    obstacles: [{row: 0, col: 1}],
    initialCode: ['down', 'left', 'down'],
    buggyIndex: 1,
    correctCommand: 'down',
    explanationKey: 'coding.debugging.p2Expl',
  },
  {
    id: 'bug-3',
    titleKey: 'coding.debugging.p3Title',
    promptKey: 'coding.debugging.p3Prompt',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 0},
    goalPos: {row: 2, col: 2},
    obstacles: [
      {row: 1, col: 0},
      {row: 0, col: 2},
    ],
    initialCode: ['right', 'up', 'down', 'right'],
    buggyIndex: 1,
    correctCommand: 'right',
    explanationKey: 'coding.debugging.p3Expl',
  },
  {
    id: 'bug-4',
    titleKey: 'coding.debugging.p4Title',
    promptKey: 'coding.debugging.p4Prompt',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 3, col: 1},
    goalPos: {row: 1, col: 1},
    obstacles: [{row: 3, col: 2}],
    initialCode: ['up', 'down'],
    buggyIndex: 1,
    correctCommand: 'up',
    explanationKey: 'coding.debugging.p4Expl',
  },
  {
    id: 'bug-5',
    titleKey: 'coding.debugging.p5Title',
    promptKey: 'coding.debugging.p5Prompt',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 1, col: 3},
    goalPos: {row: 1, col: 0},
    obstacles: [{row: 0, col: 2}],
    initialCode: ['left', 'right', 'left'],
    buggyIndex: 1,
    correctCommand: 'left',
    explanationKey: 'coding.debugging.p5Expl',
  },
  {
    id: 'bug-6',
    titleKey: 'coding.debugging.p6Title',
    promptKey: 'coding.debugging.p6Prompt',
    gridSize: {rows: 4, cols: 4},
    startPos: {row: 0, col: 1},
    goalPos: {row: 3, col: 1},
    obstacles: [{row: 1, col: 2}],
    initialCode: ['down', 'down', 'left', 'down'],
    buggyIndex: 2,
    correctCommand: 'down',
    explanationKey: 'coding.debugging.p6Expl',
  },
];

export const CODING_CHALLENGE_QUESTIONS: readonly ChallengeQuestion[] = [
  {
    id: 'cq-1',
    category: 'instructions',
    questionKey: 'coding.quiz.q1',
    promptEmoji: '🤖 ➔ ❓ ➔ ⭐',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.commands.right',
        icon: '➡️',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.commands.up',
        icon: '⬆️',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.commands.down',
        icon: '⬇️',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q1Expl',
  },
  {
    id: 'cq-2',
    category: 'sequencing',
    questionKey: 'coding.quiz.q2',
    promptEmoji: '🌱 ➔ 💧 ➔ ❓',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.sequencing.steps.flowerBlooms',
        icon: '🌸',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.sequencing.steps.plantSeed',
        icon: '🌱',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.sequencing.steps.eatBreakfast',
        icon: '🥣',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q2Expl',
  },
  {
    id: 'cq-3',
    category: 'loops',
    questionKey: 'coding.quiz.q3',
    promptEmoji: '➡️ ➡️ ➡️ ➡️',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.repeat4Right',
        icon: '🔁 4x ➡️',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.repeat2Right',
        icon: '🔁 2x ➡️',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.repeat4Up',
        icon: '🔁 4x ⬆️',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q3Expl',
  },
  {
    id: 'cq-4',
    category: 'conditionals',
    questionKey: 'coding.quiz.q4',
    promptEmoji: '🌧️',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.conditionals.thenUmbrella',
        icon: '☔',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.conditionals.thenSunglasses',
        icon: '🕶️',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.conditionals.thenIceCream',
        icon: '🍦',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q4Expl',
  },
  {
    id: 'cq-5',
    category: 'debugging',
    questionKey: 'coding.quiz.q5',
    promptEmoji: '🐛',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.fixMistake',
        icon: '🔧',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.breakCode',
        icon: '💥',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.ignoreBug',
        icon: '🙈',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q5Expl',
  },
  {
    id: 'cq-6',
    category: 'instructions',
    questionKey: 'coding.quiz.q6',
    promptEmoji: '🧭',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.stepByStep',
        icon: '🪜',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.allAtOnce',
        icon: '⚡',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.randomJump',
        icon: '🎲',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q6Expl',
  },
  {
    id: 'cq-7',
    category: 'conditionals',
    questionKey: 'coding.quiz.q7',
    promptEmoji: '🚦 🔴',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.conditionals.thenStop',
        icon: '🛑',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.conditionals.thenGo',
        icon: '🚗',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.conditionals.thenDance',
        icon: '💃',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q7Expl',
  },
  {
    id: 'cq-8',
    category: 'loops',
    questionKey: 'coding.quiz.q8',
    promptEmoji: '🔁 3x 🦘',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.jump3Times',
        icon: '🦘 🦘 🦘',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.jump1Time',
        icon: '🦘',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.walkLeft',
        icon: '⬅️ ⬅️',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q8Expl',
  },
  {
    id: 'cq-9',
    category: 'sequencing',
    questionKey: 'coding.quiz.q9',
    promptEmoji: '🪥 🥣 ⏰',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.wakeBrushEat',
        icon: '⏰ ➔ 🪥 ➔ 🥣',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.eatWakeBrush',
        icon: '🥣 ➔ ⏰ ➔ 🪥',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.brushEatWake',
        icon: '🪥 ➔ 🥣 ➔ ⏰',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q9Expl',
  },
  {
    id: 'cq-10',
    category: 'robot',
    questionKey: 'coding.quiz.q10',
    promptEmoji: '🤖 🌟',
    options: [
      {
        id: 'opt-1',
        textKey: 'coding.quiz.givesReward',
        icon: '⭐ 🏆',
        isCorrect: true,
      },
      {
        id: 'opt-2',
        textKey: 'coding.quiz.robotSleeps',
        icon: '💤',
        isCorrect: false,
      },
      {
        id: 'opt-3',
        textKey: 'coding.quiz.robotDeletes',
        icon: '🗑️',
        isCorrect: false,
      },
    ],
    explanationKey: 'coding.quiz.q10Expl',
  },
];
